### ISSUE TITLE
Reduce api calls

### ISSUE THREAD

**Issue by mikey-57** [AdyRock/com.somfy.tahoma#10]
Somfy wrote email about the api usage. If there are to much api calls in a short period of time, they start blocking the service after 31th october. 

Text:

Dear customer,
 
In an ongoing effort to provide the best services to our users, we monitor the traffic generated by our applications and Smart Home boxes (TaHoma and Connexoon). It appears that you are using a third-party solution, either developed by yourself or provided by an external entity (developer or community of developers not working for Somfy). Such developments are made without our willingness and, sometimes, do not respect our usage guidelines.

We are contacting you today to update the way your script or your application behaves with our API as it is overconsuming our backend resources for your own installation. To do so, please contact the provider of your solution or update your code by October 31st.

We are asking all third-party scripts or application to reduce their polling activity on our API. In particular, the GET /setup endpoint is meant to be used once and only once by end-user session and not to regularly refresh the devices data.

As we do not want every TaHoma and Connexoon users be impacted by the overuse of some individuals, we will react in the coming months and set up rate limiters and automated bans if such changes are not applied.

Thank you for your understanding.

**Comment by JMHuls** [comment]
I received the same email!
Hope it can be solved before the 31st...

**Comment by AdyRock** [comment]
The app has always used the /setup endpoint so the timing is coincidental. I am investigation alternatives.

**Comment by runely** [comment]
I did also receive this email today

**Comment by AdyRock** [comment]
Update: the latest version (2.1.7) uses a new method to get the state updates. It also has an option to switch off polling. If you only control covers and don't need feedback when they are moved externally then I recommend turning off polling.

I'm still awaiting an answer from Somfy to clarify if these measure are sufficient but I don't know of any other options.
