### ISSUE TITLE
App tahoma homey ne trouve pas mes volets io

### ISSUE THREAD

**Issue by Micklyd** [AdyRock/com.somfy.tahoma#100]
J'ai 8 volets io smofy à mon domicile liés à l'application tahoma via connexoon.
J'ai installé l'app tahoma sur homey pro avec mes codes d'accès.
Un seul volet sur les 8 est retrouvé par l'app tahomahomey.
Comment appairer
![Screenshot_20230330_175012_Homey](https://user-images.githubusercontent.com/129505737/229100924-a458f988-f2f7-456d-ae5e-6a1bafa8570d.jpg)
![Screenshot_20230330_174956_TaHoma](https://user-images.githubusercontent.com/129505737/229100929-00f346ad-635b-472e-bd55-01216c9d14df.jpg)
 les autres svp?

**Comment by AdyRock** [comment]
Can you open the Configure app screen, select the Device Log tab, click on Get Log and then click on Send Log. I will then be able to see what devices are reported and what type they are.

**Comment by Micklyd** [comment]
Bonjour. Merci pour votre retour.
J'ai trouvé le problème.les 7 volets étaient des roller sauter quiet mode et un seul en roller shutter.
Tout est ok maintenant
