### ISSUE TITLE
Somfy connectivity kit VELUX automatic window??

### ISSUE THREAD

**Issue by DWinters1979** [AdyRock/com.somfy.tahoma#101]
Dear Adrian,

I have got a Homey pro 2019 and I want to use it with my VELUX roof window.
I know that the Tahooma Somfy hub will work to automate the window, but it’s quite expensive to use it only for one VELUX roof window.
Is it possible that the cheaper version the Connectivity kit can work with it?

Hope you can add it and thank you for the help.

kind regards,

Remon

**Comment by AdyRock** [comment]
Unfortunately I don't know if the Velux windows work with the Connectivity kit, so you will need to ask the window supplier or Somfy that question. 

If they do then they should work with the Homey app.

**Comment by DWinters1979** [comment]
Thanks Adrian,I will ask the supplier what kind of motor they used.Kind regards,RemonVerstuurd vanaf mijn iPhoneOp 11 apr. 2023 om 15:47 heeft Adrian Rockall ***@***.***> het volgende geschreven:﻿
Unfortunately I don't know if the Velux windows work with the Connectivity kit, so you will need to ask the window supplier or Somfy that question.
If they do then they should work with the Homey app.
