### ISSUE TITLE
Cannor add pergola (IO)

### ISSUE THREAD

**Issue by wrutjes** [AdyRock/com.somfy.tahoma#105]
Hello, I cannot add my pergola 

I have a tahoma device and I can add all the devices from the tahoma into homey except for the pergola. I also tried it with the other option (buiten zonwering / pergola io) but that didn't work either. I see that it tries to login but then nothing happend.
I also eneble the developer ode but that didn't help.

I also made a log from within you app and sent it 5 minutes ago or so.

![Screenshot_20230524_111910_TaHoma](https://github.com/AdyRock/com.somfy.tahoma/assets/9075779/c18ba512-2a76-4049-9b75-5ff0d78831f4)

Hope to hear from you.

Kind regards,
Wilfried

**Comment by wrutjes** [comment]
I also instaled the /test version, but that didn't work either. I thought you'll never know :-)

**Comment by AdyRock** [comment]
The "Pergola scherm" will be found under "Exterior blind (io)".  Hope that helps.

**Comment by wrutjes** [comment]
Hello, thx for your reply. Ik already tried that but that didn't work either.

**Comment by wrutjes** [comment]
Here you see what happens.

https://github.com/AdyRock/com.somfy.tahoma/assets/9075779/147581c7-210f-4fb9-b034-3657b8e9321e

**Comment by AdyRock** [comment]
You need to select the "Exterior blind (io)"
![image](https://github.com/AdyRock/com.somfy.tahoma/assets/38184396/7ddaeb63-3a60-45a2-bd52-1cc97eb4887c)

Then it will appear. This is from the log you sent in my simulator:
![image](https://github.com/AdyRock/com.somfy.tahoma/assets/38184396/59b9bd61-2977-4d6b-bc24-b9683f616bbb)

**Comment by wrutjes** [comment]
hahaha, ok Thanks, that worked.

**Comment by AdyRock** [comment]
It looks like I forgot to change the translation for Dutch, so it is "Verticale buitenzonwering (io)"
