### ISSUE TITLE
Somfy Tahoma portail et porte de garage

### ISSUE THREAD

**Issue by Leburineurdescarpates** [AdyRock/com.somfy.tahoma#106]
Bonjour,

Sur ma Homey, je n'ai pas accès à mon portail somfy ni ma porte de garage, comment puis-je faire ?

Bien cordialement,

**Comment by AdyRock** [comment]
Do you have Homey (cloud) or a Homey Pro?

**Comment by Leburineurdescarpates** [comment]
Pro :-)

Cdt,

Mickaël Verdenal

11 Rue Pierre Curie - 54110 Varangéville

📱 0616993021
✉️ ***@***.***

------- Original Message -------

**Comment by AdyRock** [comment]
Can you open the Configure App screen, select the Device log tab, tap on the Get Log button, then when the list is full, tap on the Send Log button.
From that information I can either let you know what device it comes under or add support if it is a new one to the app.

**Comment by Leburineurdescarpates** [comment]
Voilà c'est fait :)

Cdt,

Mickaël Verdenal

11 Rue Pierre Curie - 54110 Varangéville

📱 0616993021
✉️ ***@***.***

------- Original Message -------

**Comment by AdyRock** [comment]
The 'Portail' can be added using the 'Sliding gate (io)' device.
The "Porte de garage" can be added using the "Garage Door with Position Control (io)".

**Comment by Leburineurdescarpates** [comment]
Top merci beaucoup !

Cdt,

Mickaël Verdenal

11 Rue Pierre Curie - 54110 Varangéville

📱 0616993021
✉️ ***@***.***

------- Original Message -------
