### ISSUE TITLE
Can´t find my IO exterior blinds

### ISSUE THREAD

**Issue by jlgnav** [AdyRock/com.somfy.tahoma#107]
Hi!

I have a Tahoma Switch and a few exterior blinds that I can control with my Tahoma app. However, the app in Homey cant find them. Can you help me? I have sent you a log through the app. 

Thanks,

John

**Comment by AdyRock** [comment]
They are found with the "Awning / Pergola (io)" device.

**Comment by jlgnav** [comment]
Thanks, it works!
