### ISSUE TITLE
Problem with "state Down" condition for awning

### ISSUE THREAD

**Issue by Thorarin** [AdyRock/com.somfy.tahoma#109]
There seems to be a problem with the "state" condition card for IO awnings. Namely, when I use the condition "The state is Down" for the awning, **that condition never seems to evaluate to true**.

App version: 4.0.24
Tahoma Switch version: 1.18

### Example Flow
Case in point, the advanced flow I created below (which doesn't really need to be an advanced flow, but that's beside the point):

![image](https://github.com/AdyRock/com.somfy.tahoma/assets/1827726/039ba189-11a0-4747-8830-6f3a29252924)

I can work around the issue using the logic card instead, as shown in this flow, but it's much less user friendly.

Note that doing the "Set state Up" action will change the position variable to 0. As expected, "Set state Down" changes it to 1.
In **both** situations the "state is Down" condition will evaluate to false though.

### Something I've noticed that may be vaguely related to this bug:
There appears to be some inconsistency in how the position values are used across various devices. Not just in your Homey app, but **also in the Somfy app** itself. I have two shutters which show up in the Homey device list as "greyed out" when they're completely closed/deployed, but the awning is the opposite: it is shown as greyed out when it's completely retracted. Also the UI sliders (for partial deployment) work in the opposite way and it always messes with my head.

Same issue in the Somfy app. Both the shutters and the awning are retracted. Shutters are white, awning is grey 🙄 
![image](https://github.com/AdyRock/com.somfy.tahoma/assets/1827726/d6753e66-8bef-4e4f-b563-5bfe39fb69b3)

**Comment by Thorarin** [comment]
I looked at some of the app code and found out about the invert options, which I never configured myself, but all of them are enabled for the awning.

**The card seems to work more or less as I expect when I DISABLE invert up/down**, except then it's concept of down and up is the wrong way around 🙂 I can't find an obvious flaw in this code here though: https://github.com/AdyRock/com.somfy.tahoma/blob/95180faeeecf48162396299df260ff2c86b136b3/drivers/WindowCoveringsDevice.js#L39. The code seems repeated another time, but I also don't see an immediate problem there: https://github.com/AdyRock/com.somfy.tahoma/blob/95180faeeecf48162396299df260ff2c86b136b3/drivers/WindowCoveringsDevice.js#L102

Edit:
It appears these mappings are potentially overriden in a subclass as well, although I think it's using the defaults from the parent class in my case. The awning is using the `io_horizontal_awning` driver, and the controllableName is `io:HorizontalAwningIOComponent`.

**Comment by AdyRock** [comment]
Sorry for taking so long to get back to you, but I have only just found your post. I'm not sure why the email notification didn't come through.

Is the issue still just the AND card is not working for state is down?
As the device is using the built in "windowcoverings_state", those cards are provided by Athom, so I have no control over them.
What version of Homey are you using?
