### ISSUE TITLE
TaHoma API usage warning

### ISSUE THREAD

**Issue by richardberlijn** [AdyRock/com.somfy.tahoma#11]
somfy send me this: Dear customer,
 
In an ongoing effort to provide the best services to our users, we monitor the traffic generated by our applications and Smart Home boxes (TaHoma and Connexoon). It appears that you are using a third-party solution, either developed by yourself or provided by an external entity (developer or community of developers not working for Somfy). Such developments are made without our willingness and, sometimes, do not respect our usage guidelines.

We are contacting you today to update the way your script or your application behaves with our API as it is overconsuming our backend resources for your own installation. To do so, please contact the provider of your solution or update your code by October 31st.

We are asking all third-party scripts or application to reduce their polling activity on our API. In particular, the GET /setup endpoint is meant to be used once and only once by end-user session and not to regularly refresh the devices data.

As we do not want every TaHoma and Connexoon users be impacted by the overuse of some individuals, we will react in the coming months and set up rate limiters and automated bans if such changes are not applied.

Thank you for your understanding.

**Comment by AdyRock** [comment]
The app has always used the /setup endpoint so the timing is coincidental. I am investigation alternatives.

**Comment by runely** [comment]
I did also receive this email today

**Comment by AdyRock** [comment]
I have heard that Home Assistant users are also getting the same email.
I hopefully have a fix in the mix.

**Comment by biemond** [comment]
yep me too.

**Comment by CyberRATTLER** [comment]
Also got the same message.

Let me know if I can help with any troubleshooting or information you might require

**Comment by biemond** [comment]
currently testing your new version

**Comment by bentrotro** [comment]
I’ve called somfy support today : they will close the API on october 31. End of Tahoma integration... :(

**Comment by biemond** [comment]
really, it is like some excuse, like we warned you. 

also got some 401 errors and after killing the homey app it works again. no problems with the test version.

**Comment by heidivan** [comment]
Where do you get a test version

**Comment by heidivan** [comment]
> really, it is like some excuse, like we warned you.
> 
> also got some 401 errors and after killing the homey app it works again. no problems with the test version.

Where do you get the test version

**Comment by AdyRock** [comment]
You can get it by adding test to the end of the normal link so:
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&-Connexoon/test/
Hope it works for you.

**Comment by AdyRock** [comment]
Update: the latest version (2.1.7) uses a new method to get the state updates. It also has an option to switch off polling. If you only control covers and don't need feedback when they are moved externally then I recommend turning off polling.

I'm still awaiting an answer from Somfy to clarify if these measure are sufficient but I don't know of any other options.
