### ISSUE TITLE
Somfy Rollixo IO

### ISSUE THREAD

**Issue by bvirlet** [AdyRock/com.somfy.tahoma#111]
Hello,

I have a Somfy Rollixo IO garage door (https://service.somfy.com/downloads/ro_v5/5108208a004rollixo_io_en-web-.pdf). It's configured in the Tahoma Switch but Homey doesn't see it when I add the "Garage Door Open and Close (io)" or "Garage Door with Position Control (io)".

Does this need additional support? 

If so, I'd happily send you some logs but I don't think the instructions here (https://community.homey.app/t/app-cloud-pro-somfy-tahoma-connexoon-v4-0-24-test-v4-0-30/35206) apply to the latest version of the Homey app.

Thanks!
Bruno

**Comment by AdyRock** [comment]
The instructions should be valid for the Homey Pro. The way to get to the settings keeps changing in updates to the Homey mobile app but are similar. 

If you are using Homey cloud then try to add the device and then as quickly as possible send a Diagnostics Log.

**Comment by bvirlet** [comment]
Wow! That was a quick reply! Thank you Adrian.

> The instructions should be valid for the Homey Pro. The way to get to the settings keeps changing in updates to the Homey mobile app but are similar.
> 
> If you are using Homey cloud then try to add the device and then as quickly as possible send a Diagnostics Log.

I've tried adding it twice and here are the diagnostics identifiers:

bacd7427-3069-45c3-b21f-fa644fb95cf0
7a9f718e-fe28-4bee-8465-3d059aa6666b

**Comment by AdyRock** [comment]
Could you update to the test version as I'm not seeing the device list in the logs. Just go to the app in the store and add /test to the end of the URL then install the app from there.

**Comment by bvirlet** [comment]
Hi Adrian,

Here is the new identifier: 599108b4-7681-4a91-ad68-a15ed3a7755f

**Comment by bvirlet** [comment]
Hi Adrian,

I have received a Homey Pro and was able to do the Send Log. I was able to see a `io:DiscreteGarageOpenerIOComponent` entry in the JSON, if that helps.

**Comment by AdyRock** [comment]
I have published a new Test version with support for your garage door.

**Comment by bvirlet** [comment]
Thank you!
