### ISSUE TITLE
Unable to add device on Homey Pro (Early 2023)

### ISSUE THREAD

**Issue by arnoudquanjer** [AdyRock/com.somfy.tahoma#116]
I've installed the Somfy TaHoma & Connexoon App on my Homey Pro (Early 2023). I've configured my Tahoma login settings for my Tahoma Switch and when I save the settings the app displays a message that the login was succesful. I've enabled the developer mode for my Tahoma Switch on the Somfy website. So far so good....

The problem starts when I try to add devices in the Homey App. No matter what kind of device I select I get the message 'queryAaaa ENOTFOUND gateway-xxxx-xxxx-xxxx.local' where xxxx is my tahoma switch PIN-number. I guess Homey App can't connect to my Switch. Any ideas what might be the problem? I've sent you the event and device logs via the App.

Kind regards,
Arnoud

Hard-/software versions
--------------------------
Homey Pro (Early 2023) - Firmware 10.0.0-rc.110
Homey App (version 7.1.0.1208)
Tahoma Switch 1.18
Tahoma Switch connected through Ethernet not WiFi

**Comment by AdyRock** [comment]
That is caused by an issue with the HP2023 mDNS. It is fixed in later firmware, which is still experimental. So either enable experimental updates or wait until the new firmware is released to the normal channel.

**Comment by arnoudquanjer** [comment]
Thanks for the quick reply! I'll enable experimental updates and give it another try.

**Comment by arnoudquanjer** [comment]
Problem has been resolved by installing the experimental update.

Thanks again for your help!
