### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by zkrasnay** [AdyRock/com.somfy.tahoma#12]
Hello Adrian,
I don't know whether it is related with the Tahoma warrning message I also received yesterday, but today the app stopped working with Error in the subject. I am pretty sure, that the Connexoon box is working, as I can use regular mobile application, but my Homey lost connection. I have sent the error log, recently. Did they block the API already ?

**Comment by antoinek** [comment]
Hi Adrian,
I have never been able to use the application, always get an error 401 in reauthenticate. TaHoma is working fine and I can connect to it via somfy-connect.
Thanks for your help

**Comment by AdyRock** [comment]
I don't think the problem is a result of the email as they say we have until the end of the month. 
However, I think Somfy have been changing the authentication method they use from simple user id an password to OAuth. Have you tried turning on the new method in the app configuration page?

**Comment by antoinek** [comment]
I can confirm that this has nothing to do with the email about usage of /setup end point. Somfy’s support have confirmed they have an issue with authentication on Tahomalink.com which is desynced... Apprently for some users changing their password will resync but not for all. They have no idea when this will be fixed.

I see on GitHub that you’re on version 2.0.9, I am not able to download a more recent app that 2.0.3.

**Comment by AdyRock** [comment]
Thanks for the information about the authentication issue. 
The newer version are still in test so you just need to add /test to the end of the app url in the store.

**Comment by antoinek** [comment]
2.0.10 installed, could log in, apparently no problem.
But then every get request gets a “token expired” message leading to logging on again, and always fails to logout. I sent you the logs.

Antoine • antoine@pobox.com

**Comment by bentrotro** [comment]
I’ve installed 2.0.13 version (test version). Doesn’t work. Error 401 when trying to authenticate (save credentials)...

**Comment by zkrasnay** [comment]
I think we can close this issue, as in version 2.1.7 it doesn't appear. Added OAuth method can solve this Error 401. Even the token expiration seems to be solved. Thanks Adrian!
