### ISSUE TITLE
Fail to log in (again) after new 2.1.7 update

### ISSUE THREAD

**Issue by bentrotro** [AdyRock/com.somfy.tahoma#13]
Previous update was ok.
This one fails to log in.

**Comment by JMHuls** [comment]
Same here... on all 3 url's.

**Comment by AdyRock** [comment]
Could you turn on the Information log, then select the default URL and try logging in again. After the login message appears could you send me the Information log.

**Comment by bentrotro** [comment]
Hello. I’ve turned on all logs. Then tried to log in : « Attempting to log in... » message during few’seconds, then an iOs window « error ». No logs. Everything is empty ...

**Comment by AdyRock** [comment]
So after trying to log in, this screen is still empty?
![Screenshot_20201020-121259_Homey](https://user-images.githubusercontent.com/38184396/96578890-db31c600-12cd-11eb-84ec-18ba5434463e.jpg)
And the box was ticked before trying to log in?

**Comment by JMHuls** [comment]
Only got this 
![Screenshot_20201020-132223_Homey](https://user-images.githubusercontent.com/45454427/96579731-a296ea00-12d7-11eb-9bba-f0f9d37e6857.jpg)
Nothing in the log-screen, even after trying all 3 url's

**Comment by bentrotro** [comment]
yes, still empty

**Comment by AdyRock** [comment]
I don't understand how the log can be empty so I am struggling to get to the bottom of this.
I have logged out and back in again many times now to try and replicate this but I never get an issue.

Could one of you try the option Create Diagnostics Report after trying to log in to see if any errors show up in my developers panel.

**Comment by derkd** [comment]
I could also not login. Flows are not working anymore and logs do not show anything with al the check marks enabled ![image](https://user-images.githubusercontent.com/839617/97267853-2ba7a700-182b-11eb-851c-befff2e24255.png)

**Comment by AdyRock** [comment]
Could you try the latest test version 2.1.10.
I found a situation where failed logins could get stuck in a loop so I have put a timeout on that. I don't know how it could get into that situation but at least now it can get out of it.

**Comment by basvdploeg** [comment]
Got the same error message last night, and I wasn't able to login anymore.

I installed the test version (2.1.10) but it crashed immediately after startup (see screenshot).

**BUT:** Then I installed the public version from the Homey App Store again, and  **logging in worked without a problem**. No idea how that is possible, but it did the trick for me.

![IMG_6006](https://user-images.githubusercontent.com/4628469/97277031-3ddc1200-1838-11eb-8a3a-de54fa54db38.PNG)

**Comment by AdyRock** [comment]
axios is the module I use for the http. I don't have the node libraries on GitHub so if you run it via the CLI you would have to do a npm update first to get them.

**Comment by derkd** [comment]
> Could you try the latest test version 2.1.10.
> 
> I found a situation where failed logins could get stuck in a loop so I have put a timeout on that. I don't know how it could get into that situation but at least now it can get out of it.

How can I install this 2.1.10 version on Homey?

**Comment by AdyRock** [comment]
You add /test to the end of the normal app url to get test versions.
https://homey.app/a/com.somfy.tahoma/test/

**Comment by JMHuls** [comment]
Downloaded and installed version 2.1.10.
First attempt to login failed. Tried again after turning logs on and then this happened:
![sketch-1603955651443](https://user-images.githubusercontent.com/45454427/97537223-bec51600-19be-11eb-8efd-6b9c12ef5a0d.jpg)
Me happy! 😀 Thanks Adrian! _(Didn't test the shutters yet, I'm at work now)_

**Comment by derkd** [comment]
> You add /test to the end of the normal app url to get test versions.
> 
> https://homey.app/a/com.somfy.tahoma/test/

It works!

**Comment by bentrotro** [comment]
Test version 2.1.11 works!
Thank you, really great support Adrian
👍🏻
