### ISSUE TITLE
No support for Somfy controlled Pleated blinds ?

### ISSUE THREAD

**Issue by Psicor1** [AdyRock/com.somfy.tahoma#131]
Hi.

Aiming to use your Homey app to see if i can control my 3 Velux windows in our new built house we just moved into - crossing my fingers, but I understand this should be doable.
However, we also Just bought a motorized pleated blind from the company "Powered Blinds", in the hopes that your app might also be able to control that, since it uses Somfy, and it's remotes.
But it seems you do not have any pleated blinds devices on your list, so we were wondering if you had any plans on adding support for such devices that have 2 motors in them (One for the top bar and one for the bottom bar) in general, and this brand in particular? :-)

URL for these:
https://www.poweredblinds.dk/plissegardiner/

Let me know if you need more info :-)

Thanks alot for your great work,

**Comment by AdyRock** [comment]
Could you send the device log from the app settings page. That will show me the internal names of the motors and the commands they use.

**Comment by Psicor1** [comment]
But isn't that in the homey app you mean in regards to the log? I guess it
somehow needs to be added to homey first before anything is visible in the
log?
If so, how can I add it there if it is not yet supported by the app? (sorry
for the rookie question, but have not used your great app before, but will
use it for both inside and outside shutters, Velux skylights and awnings).

On another note, Also not yet having luck adding my 3 Velux skylight to
homey, as first I need to add it to Tahoma I think, and Tahoma asks me to
hit an "add" button on the device, which I am not sure how to find / get to.
Or do I need to buy and use Velux own gateway (with netatmo) instead of
Tahoma switch, in order to add it to homey?

Anywhere one can support your work with donation?

All the best.




lør. 29. jul. 2023 23.01 skrev Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
Sorry for the delay getting back to you.
The log is populated when you go through the add device option of Homey. It will be filled with all the devices that were detected during the discovery. So when adding a device, select any option and the app will fetch the list of all devices, so even though it may fail, the list will still be updated.

For the Velux skylight, I have seen logs from users that have added that type of thing but I don't know the process they used to add them to Tahoma.

**Comment by Psicor1** [comment]
Ok.
Hopefully i did it correctly now. I clicked the "send log" within the app.
👍

Hmm..ok, I will try and do some digging in regards to the Velux, and get
back if their version are not supported, also :-)

Thanks again.
Again, if there is any way i can donate a little to your work, please let
me know how/where.

Br
Dennis

**Comment by AdyRock** [comment]
OK, I have the log and I can see the devices. I will add them to the the RTS Blind device in Homey and upload a new test version soon.

**Comment by AdyRock** [comment]
It appears there is an issue with the Athom servers at the moment so I can't publish the update. I will try again in the morning.

**Comment by AdyRock** [comment]
New test version is now published

**Comment by olanaaa** [comment]
Hi @AdyRock . Great app! 
I too have some pleated blinds that is not discovered in Homey. I have sent the device log. Hopefulle I have done it correctly and you can add them also. Thanks.
