### ISSUE TITLE
Somfy doesn’t work with Homey Pro 23

### ISSUE THREAD

**Issue by PatrikPmr** [AdyRock/com.somfy.tahoma#132]
If I wan’t to use Somfy with Homey Pro, it’s neccesary to register and it requires pin code from the bottom side of somfy gateway. Does it mean I have to buy one of Somfy gateway even I have Homey Pro already? 

![IMG_8333](https://github.com/AdyRock/com.somfy.tahoma/assets/141433622/72290c73-1bbe-48ee-af48-f671baad97c0)
![IMG_8334](https://github.com/AdyRock/com.somfy.tahoma/assets/141433622/5feb7483-6317-4abe-8986-28b6fdc15f77)

**Comment by AdyRock** [comment]
If you have RTS devices then use the Somfy RTS Homey app. 
If you have IO devices then you will need a Somfy gateway.

**Comment by DavidOliver** [comment]
@PatrikPmr, in case you want to be able to use the local API, which enables use when your internet connection is down, I think the choice of gateway is important. For example, I think I read that the Connectivity Kit can't use the local API.

**Comment by PatrikPmr** [comment]
Yes I have io, thanks for advices.

**Comment by AdyRock** [comment]
IO is a licensed protocol. It's encrypted and on a radio frequency that is not built into Homey and Somfy are very protective over it.
So a Somfy bridge is the only option.
The Connectivity kit is the cheapest option but as @DavidOliver said it doesn't support local connections. Tahoma and Connexoon both support local access, but even they require an Internet connection to obtain an access token, so are not completely free from external access. 

I hope that helps.

**Comment by DavidOliver** [comment]
@AdyRock, thanks. Does the access token need to be periodically renewed over the internet, or is it valid indefinitely?

**Comment by AdyRock** [comment]
It was expired are a month but I believe that was going to be changed although I haven't checked it.
If you have an Internet connection you won't notice the refresh.
Also, some devices aren't supported locally. The only one I know of for sure is the radiator valve, which can get updates locally but can only be controlled via the Internet. I have reported that, so maybe one day it will be fixed.
