### ISSUE TITLE
Somfy switch | Dom Roc doorlock 

### ISSUE THREAD

**Issue by Barney1977** [AdyRock/com.somfy.tahoma#134]
Hi,
I have installed a pilot DomRoc doorlock Which already is integrated by somfy. Today I got a Somfy TaHoma switch and installed it directly it’s supporting this doorlock. 
what to do to also add it into my homey (pro 2023). Is this possible?

**Comment by AdyRock** [comment]
Can you open the Apps settings page and select the Detected tab and then tap on Get Log, then send. I will look at the information to see if it's already supported and if not I will try to add it.

**Comment by Barney1977** [comment]
Hiadrian, from which app you mean?
Somfy TaHoma?

**Comment by AdyRock** [comment]
In the Homey Somfy app.

**Comment by Barney1977** [comment]
If allright you got it

**Comment by Barney1977** [comment]
Added value of integration into homey would be:
Possibility to adjust function of central pushbutton. 
set nightmode. 
set everlock

**Comment by AdyRock** [comment]
The only option available via the API are Lock and Unlock. I have added the device to the new test version so you can install that by finding the app in the Athom App store and then add test to the end of the URL.

**Comment by Barney1977** [comment]
great, it seems to work. I Will contact Dom/Somfy to request other options in API.
