### ISSUE TITLE
Flows do not work since 4.0.59

### ISSUE THREAD

**Issue by SlyNL** [AdyRock/com.somfy.tahoma#136]
Flows do not work any more since last update

cb296c94-6a43-49eb-940c-9064740d3cea

**Comment by AdyRock** [comment]
The error in the log is a 401, which means not authorised. 
Can you try logging in again from the app settings page to see if that fixes it.

**Comment by SlyNL** [comment]
Wow thanks for the quick response, I renewed my password and it works again.

**Comment by SlyNL** [comment]
Wrong password
