### ISSUE TITLE
Connexion problèmes 

### ISSUE THREAD

**Issue by goussetg2** [AdyRock/com.somfy.tahoma#137]
Good morning.  I have a recurring problem.  after each update of your application I must log in to my tahoma account in the settings of your application.  Today I realize that sometimes my Somfy equipment does not work and I have to log in to my account again even though there have been no updates.  Is it normal to have to log in so often even though my login details are saved in the settings?

**Comment by AdyRock** [comment]
No, that's not normal. I haven't had to login for several years. 
Do you have a Homey Pro or a Homey cloud account?

**Comment by goussetg2** [comment]
I have a Homey Pro account and use the Homey Pro 2023. I have developer mode activated on HP23 and on the Tahoma SwitchEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Adrian Rockall ***@***.***> Date : 31/08/2023  13:35  (GMT+01:00) À : "AdyRock/com.somfy.tahoma" ***@***.***> Cc : goussetg2 ***@***.***>, Author ***@***.***> Objet : Re: [AdyRock/com.somfy.tahoma] Connexion problèmes  (Issue #137) 
No, that's not normal. I haven't had to login for several years.
Do you have a Homey Pro or a Homey cloud account?

**Comment by AdyRock** [comment]
When it next fails and you need to login again, could you open the app settings page, select the Information log tab and then tap on Send Log. 
Then clear the log and tick the log enabled option, which will make the app collect more detailed information. Then login to your Somfy account and once connected, go back and send the log again.

**Comment by goussetg2** [comment]
clarification: I am not disconnected but it's just that all my Somfy equipment becomes inactive.  Any action on a tile has no effect on the equipment and therefore I am forced to log in again to my Somfy account to refresh or update my equipment and for the tiles to work againEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Adrian Rockall ***@***.***> Date : 31/08/2023  14:38  (GMT+01:00) À : "AdyRock/com.somfy.tahoma" ***@***.***> Cc : goussetg2 ***@***.***>, Author ***@***.***> Objet : Re: [AdyRock/com.somfy.tahoma] Connexion problèmes  (Issue #137) 
When it next fails and you need to login again, could you open the app settings page, select the Information log tab and then tap on Send Log.
Then clear the log and tick the log enabled option, which will make the app collect more detailed information. Then login to your Somfy account and once connected, go back and send the log again.

**Comment by AdyRock** [comment]
Ok, I understand. So when it stops working, then send the log.

**Comment by goussetg2** [comment]
OK.  thank you for your responsiveness and for your help 👍Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Adrian Rockall ***@***.***> Date : 31/08/2023  22:01  (GMT+01:00) À : "AdyRock/com.somfy.tahoma" ***@***.***> Cc : goussetg2 ***@***.***>, Author ***@***.***> Objet : Re: [AdyRock/com.somfy.tahoma] Connexion problèmes  (Issue #137) 
Ok, I understand. So when it stops working, then send the log.

**Comment by goussetg2** [comment]
Good morning.  today problems with the control of my somfy equipment.. I have just followed your procedure and have just sent you the logs.  connecting to my somfy account was not possible and I had to restart your application for everything to work again.Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Adrian Rockall ***@***.***> Date : 31/08/2023  22:01  (GMT+01:00) À : "AdyRock/com.somfy.tahoma" ***@***.***> Cc : goussetg2 ***@***.***>, Author ***@***.***> Objet : Re: [AdyRock/com.somfy.tahoma] Connexion problèmes  (Issue #137) 
Ok, I understand. So when it stops working, then send the log.

**Comment by AdyRock** [comment]
Thanks for the logs.
The first one shows the app can't connect as the box is not found (ENOTFOUND). The second log shows it's connecting again. 
As the URL is the same, it seems the DNS is giving the wrong information back. I'm not sure if Homey caches the DNS information and the IP address is changing.
Could you try fixing the IP address of your Somfy box via your router to see if that solves the problem. 
I will also contact Athom to see if they have any advice.

**Comment by goussetg2** [comment]
Thank you very much for your quick response.  I don't really know what to do with the IP address of my switch.  I understand where the problem comes from but I don't know how to repair the IP.. I bought an ethernet adapter for the switch to see if that solves the problem.  I also did something on my router.  to be continuedEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Adrian Rockall ***@***.***> Date : 04/09/2023  14:19  (GMT+01:00) À : "AdyRock/com.somfy.tahoma" ***@***.***> Cc : goussetg2 ***@***.***>, Author ***@***.***> Objet : Re: [AdyRock/com.somfy.tahoma] Connexion problèmes  (Issue #137) 
Thanks for the logs.
The first one shows the app can't connect as the box is not found (ENOTFOUND). The second log shows it's connecting again.
As the URL is the same, it seems the DNS is giving the wrong information back. I'm not sure if Homey caches the DNS information and the IP address is changing.
Could you try fixing the IP address of your Somfy box via your router to see if that solves the problem.
I will also contact Athom to see if they have any advice.

**Comment by AdyRock** [comment]
On most routers you can configure them to always reserve an IP address for the same device.  The router uses the device mac address to recognise it. 
I have asked Athom if they know of an issue with caches, but no idea when or if they will answer.

**Comment by goussetg2** [comment]
All right !  I'm going to deepen my research on this side 👍 once again I thank you for what you do, you are great 👍👍 I will make a donation to you during the day!  Thanks a lotEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Adrian Rockall ***@***.***> Date : 04/09/2023  22:38  (GMT+01:00) À : "AdyRock/com.somfy.tahoma" ***@***.***> Cc : goussetg2 ***@***.***>, Author ***@***.***> Objet : Re: [AdyRock/com.somfy.tahoma] Connexion problèmes  (Issue #137) 
On most routers you can configure them to always reserve an IP address for the same device.  The router uses the device mac address to recognise it.
I have asked Athom if they know of an issue with caches, but no idea when or if they will answer.

**Comment by goussetg2** [comment]
sorry but it's not possible for me to thank you on the homey app site and don't make a donation thereEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Adrian Rockall ***@***.***> Date : 04/09/2023  22:38  (GMT+01:00) À : "AdyRock/com.somfy.tahoma" ***@***.***> Cc : goussetg2 ***@***.***>, Author ***@***.***> Objet : Re: [AdyRock/com.somfy.tahoma] Connexion problèmes  (Issue #137) 
On most routers you can configure them to always reserve an IP address for the same device.  The router uses the device mac address to recognise it.
I have asked Athom if they know of an issue with caches, but no idea when or if they will answer.
