### ISSUE TITLE
RTS curtains connection error

### ISSUE THREAD

**Issue by stefanrenne** [AdyRock/com.somfy.tahoma#139]
Every time I open the curtains since a few days it shows this error, all other IO devices (like blinds) don't show an error.
Device logs have been send and the Tahoma and Homey are in the same vlan

![IMG_2713](https://github.com/AdyRock/com.somfy.tahoma/assets/1297864/056ce499-c792-4dd4-9234-65b559e6e2e9)

**Comment by AdyRock** [comment]
Cab you try the new test version that Ii will publish today.

**Comment by stefanrenne** [comment]
I will install the test version but in all hostly I haven't seen this error in the last week so it hard for me to give you valid feedback
