### ISSUE TITLE
Error: request failed with status code 401 after update 2.1.12

### ISSUE THREAD

**Issue by Sjefke40** [AdyRock/com.somfy.tahoma#14]
After the update 7 hours ago i can't login. The app was working perfectly the last weeks.

Any ideas of what I should do?

**Comment by AdyRock** [comment]
The update has not worked well and I have had an email from Somfy about an issue it is causing. In sight of that I have published a new test version that should roll out ASAP.
I would be grateful if you could try the test version to see if it fixes the problems.
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&-Connexoon/test/

**Comment by Sjefke40** [comment]
I installed 2.1.13

It has the same error when i am trying to login.

**Comment by AdyRock** [comment]
Could you enable the Information log and send it to me when it has captured some data?

**Comment by Sjefke40** [comment]
> Could you enable the Information log and send it to me when it has captured some data?

Oke, I just did.

**Comment by AdyRock** [comment]
I have updated all the libraries and pushed 2.1.14. Could you try that.
Just out of interest what is your Homey firmware version?

**Comment by Sjefke40** [comment]
I installed 2.1.14

Still the same problem. My firmware is 4.2.0. I have send you the log

**Comment by AdyRock** [comment]
Sorry it has been so long since I have got back to you.
Do you still have the problems with the latest version in the Athom app store?

**Comment by Sjefke40** [comment]
No, everything ia working fine

Op di 19 jan. 2021 13:15 schreef Adrian Rockall <notifications@github.com>:
