### ISSUE TITLE
BugReport: Since Last update none of my Door Window Sensors are Working

### ISSUE THREAD

**Issue by HSA1963** [AdyRock/com.somfy.tahoma#140]
I have tried to use the beta version also this version does not allow to add my door  window sensors to be added. I dont even see a log. Is there a possibility to use the older version instead of the latest version because at that moment it worked. I don't want to go into the dark when I open my celler. I changed that into zigbee juist to have more information and an attention signal when the door is opened.

**Comment by AdyRock** [comment]
I'm not sure why they aren't working as I don't think anything has changed for those devices. 
I presume you can still see them in the Tahoma app?
If so could you send the Device log and the information log from the app settings page. Make sure you trigger the sensors about 30 seconds before sending the information log.

**Comment by HSA1963** [comment]
7ae32387-7389-4bd2-b554-f6e93ee14c02 this is the code of the bug report app. And device report "119FA252"

**Comment by AdyRock** [comment]
Do you have a Homey Pro or a Homey cloud?
If it's the Pro then can you send the logs from the app settings page.
I haven't had any Homey logs through.

**Comment by HSA1963** [comment]
I have a Homey Pro. Regarding your message, I think I did something wrong. Can you guide me to sent you the right information..

**Comment by AdyRock** [comment]
Press the more button n the bottom right corner of the Homey app, select apps and then the Somfy Tahoma and Connexoon app. Tap on the gear ⚙️ in the top right corner and then App Settings. Tap on the Device Log tab and then tap on the Get Log button. Once the list box is filled, tap on Send Log. 
Next, select the Information log and make sure the Log Enable is ticked. Then trigger the sensors and wait 30 seconds or so. Finally tap on the Send Log button.

**Comment by HSA1963** [comment]
I think I mixed up. I had the wrong thread. I had only that ZigBee door Window sensors are not shown in the Homey. But that is a request not a Bug. One of my other posts
