### ISSUE TITLE
My shutters fail to go down / or up

### ISSUE THREAD

**Issue by severiti** [AdyRock/com.somfy.tahoma#141]
Hi,

I have some issues with the app :
1. I have around 11 shutters. I’m not able to let them go up or down all at once only with a “wait” of 30 sec after 6 shutters have changed. 
2. not all shutters take the position they should take. I have 1 that will always tinto the “my” mode when it should be closed. 
3. often they just don’t react to a flow(I get my “if error” message. 

I have created a diagnostic report. 7b89ede5-4a5f-482e-bf8f-c7d7eb6c274e

**Comment by AdyRock** [comment]
I'm not sure if there is a limit to the number of commands that can be queued, so maybe that is the reason.
Could you send me the Information log from the app setting page as the Homey Diagnostic log doesn't contain much information.

**Comment by severiti** [comment]
Thx,

You should have it now.

Really strange behavior, past 2 weeks it was fine. Again having trouble
since Friday evening

Regards

Tim

Op zo 15 okt 2023 om 14:37 schreef Adrian Rockall ***@***.***>

**Comment by severiti** [comment]
Additionally, i notice that when I restart my homey i always need to
"repair" one shutter in order to get the flows running again.

So it seems like it doesn't remind my login credentials in the app ?

Op zo 15 okt 2023 om 18:42 schreef Tim Severijns ***@***.***>:

**Comment by severiti** [comment]
any update please ?

**Comment by AdyRock** [comment]
Sorry, it's been hectic with catching up after my holiday. I have looked at the logs on the 15th and there is just one for Tahoma, so I presume that is from you. However, it just show that the app is not logged in.
Can you make sure you are using the test version as that will override the normal login if the sync loop keeps detecting that it's not logged in. It also adds a bit more diagnostics information to the log.
When you send a log with the test version it will show an ID, so can you let me know what that is and then I can be sure I am looking at the log from you.

**Comment by severiti** [comment]
Thx Adrian, what do you mean with test version ? I'm using version 4.0.65.
For Homey I'm using the beta still (i believe)

Where to download the test version ?

Op ma 23 okt 2023 om 14:36 schreef Adrian Rockall ***@***.***

**Comment by AdyRock** [comment]
Find the app in the store and then add /test to the end of the URL. 
The current test version is 4.0.67

**Comment by severiti** [comment]
Thx, downloaded the test version will use it for some time and if the error
occurs I will let you know

Op ma 23 okt 2023 om 14:56 schreef Adrian Rockall ***@***.***

**Comment by severiti** [comment]
just have sent you a new log 1554860170.

To overcome the issue of sending all commands at once (11 shutters) i have build a flow where 6 of them start at the beginning of the flow ; for the others there is a "wait" of 30 secs before the command is sent. 

Closing seems to go well ; opening not (some do not go up at all ; some stop half way...)

Ideally i don't have put the "wait" argument in there at all

**Comment by AdyRock** [comment]
My first observation is you seem to be sending the commands to each shutter 3 times in very quick succession. I haven't investigated if this is an app issue yet but could you check if the flow is being triggered multiple times?
In the mean time, I'm still analysing at the log and the app,

This is the extract from the log for one shutter so you can see the time stamp of each command.
```
  {
    "time": "2023-10-25T05:52:14.170Z",
    "elapsed": 0.02,
    "source": "rolluik Boo voorkant: Send command io://####-####-####/######",
    "data": "command: {
                "name": "open",
                "parameters": []
              }"
  },
  {
    "time": "2023-10-25T05:52:14.720Z",
    "elapsed": 0.023,
    "source": "rolluik Boo voorkant: Send command io://####-####-####/######",
    "data": "command: {
                "name": "open",
                "parameters": []
              }"
  },
  {
    "time": "2023-10-25T05:52:15.444Z",
    "elapsed": 0.023,
    "source": "rolluik Boo voorkant: Send command io://####-####-####/######",
    "data": "command: {
                "name": "open",
                "parameters": []
              }"
  },

```

**Comment by severiti** [comment]
this is the flow ; it's only triggered at a specific time or based on sunset

![Screenshot 2023-10-25 095204](https://github.com/AdyRock/com.somfy.tahoma/assets/65543685/64616105-140b-48f8-aab1-07dae498ca42)

**Comment by AdyRock** [comment]
Could you show the flows that trigger that flow?
I have safeguards in the code to ignore duplicate commands, but the timing of the requests is so quick that it seems to be fooling them.
I will try to find a way to reduce the time between checks a registration.

**Comment by severiti** [comment]
here you go 
![image](https://github.com/AdyRock/com.somfy.tahoma/assets/65543685/937c8300-d8b9-4dce-bfee-bbe514ed0503)

**Comment by AdyRock** [comment]
So, by looking at the flows and the timings in the log, it appears you opened the Badkamer at 7:52 and that triggered the second flow to run the open blinds blinds flow:

```
  {
    "time": "2023-10-25T05:52:13.893Z",
    "elapsed": 0.145,
    "source": "Cloud Fetching Events",
    "data": "{
                "message": "Complete",
                "stack": [
                  {
                    "timestamp": 1698213124118,
                    "setupOID": "10043139-b416-4bfd-91be-43b688fc3396",
                    "deviceURL": "",
                    "deviceStates": [
                      {
                        "name": "core:ManufacturerSettingsState",
                        "type": 3
                      },
                      {
                        "name": "core:OpenClosedState",
                        "type": 3,
                        "value": "open"
                      },
                      {
                        "name": "core:ClosureState",
                        "type": 1,
                        "value": "96"
                      },
                      {
                        "name": "core:TargetClosureState",
                        "type": 1,
                        "value": "0"
                      },
                      {
                        "name": "core:MovingState",
                        "type": 6,
                        "value": "true"
                      }
                    ],
                    "name": "DeviceStateChangedEvent"
                  }
                ]
              }"
  },

```

So, now I wonder if the state change trigger can fire multiple times while the shutter is moving.

**Comment by severiti** [comment]
if you want to ; i can close the shutters ; set a timer for 11h00 cet and then send another report ?
might help in understanding the behaviour ?

**Comment by AdyRock** [comment]
I'm rearranging the code so the command is recorded immediately after it is checked. The current version records the command after it has been successfully sent, so there is a relatively large window of opportunity to allow duplicate commands. I just have to ensure the recorded command is cleared properly so it doesn't block valid commands later.
I will also add a log message to the trigger code so we can see if that is being fired multiple times.
I will let you know when there is an update ready.

**Comment by AdyRock** [comment]
I have published a new test version. As I only have RTS blinds I can't test the changes thoroughly but I have tried to simulate it as best I can, so I hope it works OK.

**Comment by severiti** [comment]
should i download again, or will it automatically be updated ?

Op wo 25 okt 2023 om 13:26 schreef Adrian Rockall ***@***.***

**Comment by AdyRock** [comment]
In theory, if you already had a test version installed it should auto-update.

**Comment by severiti** [comment]
I've tested it. and have send you the log files again
1. as per original flow (including the "wait") shutters go down and up without a problem
2. as per new flow without "wait" always 1 shutter doesn't perform the action (so i believe that might refer to what you mentioned earlier) This is actually not a showstopper so for me the initial test is ok.

I will monitor in the coming days and keep you posted .
Thanks already !

**Comment by AdyRock** [comment]
I'm not seeing any CMDCANCELLED events which is good.

**Comment by severiti** [comment]
Ady, testing looks ok for now ; I'm closing this.

Thank you very much for your help !
Happy to help you forward in case you need to have something tested in the future...
