### ISSUE TITLE
Roller shutter is not recognized

### ISSUE THREAD

**Issue by rubenlucas86** [AdyRock/com.somfy.tahoma#147]
My Roller Shutter is not recognized/found in the Somfy TaHoma & Connexoon app. I have a Somfy brige on which the roller shutter does work.

I have sent the log through Homey.

**Comment by AdyRock** [comment]
Thanks for the log. I will look into it as soon as I return from Holiday.

**Comment by rubenlucas86** [comment]
Thank you!

**Comment by AdyRock** [comment]
Can you let me know what name the roller shutter has in the Tahoma app?

**Comment by rubenlucas86** [comment]
Hi 

Of course. It's called OXIMO 40 SOLAR

**Comment by Mjng** [comment]
Hi, i have 4 RTS shutters but they are not listed and i tried all RTS devices. Maybe you just received the log? (different email)
Is it possible to put all RTS shutters under one device.
Or can you add my type of device e.g. Rolluik 1

**Comment by AdyRock** [comment]
I have added you shutter type to the 'Blind or Shutter (RTS)' device. 
The new test version is in the store now.

**Comment by Mjng** [comment]
Version 74? Still 73, prob waiting for update.
Bedankt alvast
________________________________

**Comment by AdyRock** [comment]
Version 77. You will need to find the app in the store, then add \test to the end of the URL and install that version.

**Comment by Mjng** [comment]
Thank you, tested and working both RTS and IO screen /shutters
Greetz Martin

________________________________

**Comment by rubenlucas86** [comment]
For me, it works again. Thx AndyRock
