### ISSUE TITLE
Error 401 cannot logon 

### ISSUE THREAD

**Issue by FPPMvB** [AdyRock/com.somfy.tahoma#15]
Since today it is no longer possible to logon to the Tahoma box
Error 401
Using app cersion 2.1.14 since last week, error occured today

30ca3929-5be1-42fd-a9b9-2834316d2c8d

**Comment by AdyRock** [comment]
Can you try the latest test version 2.1.22 https://homey.app/a/com.somfy.tahoma/test/

**Comment by FPPMvB** [comment]
Yes. This seems to work. Thxzzz

Met vriendelijke Groeten,
Frank van Berkel
