### ISSUE TITLE
New blinds are not recognized 

### ISSUE THREAD

**Issue by olanaaa** [AdyRock/com.somfy.tahoma#150]
First of all: Great app!

I have some pleated blinds that is not discovered in Homey. I have sent the device log. Hopefulle I have done it correctly and you can add them also. Thanks.

**Comment by AdyRock** [comment]
I have published a new test version with rts:CellularBlindRTSComponent added.

**Comment by olanaaa** [comment]
Thank you :) 

How do I install the test version to try?

**Comment by AdyRock** [comment]
Find the app in the store and then add /test to the end of the URL

**Comment by olanaaa** [comment]
It works now. Thank you!
