### ISSUE TITLE
Softly blind not detected

### ISSUE THREAD

**Issue by JanPedersen777** [AdyRock/com.somfy.tahoma#153]
I have a TaHoma Switch and a softly blind.
The program cannot detect the blind
Used the "Blind or shutter (RTS)"

Device log send from homey pro.
Device name in tahome app on iphone is "stue"

**Comment by AdyRock** [comment]
That device was added to version 4.0.67 so you will need to update to the test version as you are using version 4.0.65.
To install the test version, just find the app in the store and then add /test to the URL.

**Comment by JanPedersen777** [comment]
Thank you 👍 
I worked great :-)
