### ISSUE TITLE
Somfy io Roller shutter with Solar panel and Lux sensor

### ISSUE THREAD

**Issue by RicoCardo** [AdyRock/com.somfy.tahoma#159]
Hello there,

new member of the homey comunnity, facing problems with connecting my roller shutters. 

i see the shutters in homey, but i dont have possibility's to choose when to open on an "X" value of lux. 

i have those options in the tahoma hub, but not in the homey app itself. 
im using the "somfy tahoma & connexoon" from Adrian Rockal.

is there a possibility to add these options? 

thanks in advance.

**Comment by AdyRock** [comment]
Have you added the Lux sensor to Homey?

**Comment by RicoCardo** [comment]
Thanks for the short advice! didnt knew i had to add the lux sensor apart from the shutters..... lack of knowledge,

thanks in advance, tried it yesterday and the sensors are added to homey!
