### ISSUE TITLE
Automatically Logged out everyday

### ISSUE THREAD

**Issue by derkd** [AdyRock/com.somfy.tahoma#16]
I'm getting logged out every day. After logging in my flows work again. Does this have something to do with the sync in seconds? Maybe too short. It was set to 300s.

**Comment by AdyRock** [comment]
Somfy have agreed to 30 seconds for the sync time so provided you don't go shorter than that it should be OK.

Are you running the test version (2.1.33) as that should prevent the polling time being too short. It should also be better at logging in.

**Comment by derkd** [comment]
No I'm using the 2.1.14 version. Will try the 2.1.33

**Comment by derkd** [comment]
It works!
