### ISSUE TITLE
CONNEXOON Window not recognized 

### ISSUE THREAD

**Issue by StefanVersleeuwen** [AdyRock/com.somfy.tahoma#160]
Hi there,

I'm quite new here on the Homey platform. I used Homebridge before. 

Now, I'm trying to add my outdoor "CONNEXOON Window" screen via my Connexoon Hub, but I cannot get it to work. When I add the hub on the Homey, it only gives me a LED dimming bar, which obviously doesn't work. 

It works (worked)  on my Homebridge, it works via the TaHoma app, but I can't get it to work on my Homey.

I put the device in developer mode and I can see that it gets a token. I deactivated the plugin on Homebridge. What more options do I have?

Thanks for all the effort you put in this app! I will share the information log right now (ID 308577269).

Stefan

**Comment by AdyRock** [comment]
The log is showing errors for the local login. 
For the screen you need to add them to Homey as a separate device.

**Comment by StefanVersleeuwen** [comment]
Which device should I use? All devices, except for the hub, return as no devices found.

**Comment by AdyRock** [comment]
For me to see what device types you have and advise on the driver to select, could you send the Device Log from the app settings page.

**Comment by StefanVersleeuwen** [comment]
Sure! I just sent it, ID 308577269

**Comment by AdyRock** [comment]
From the information in your log I can see there is a "Awning / Pergola (io)" device.
(Dutch is "Buitenzonwering / Pergola (io)" and German is "Markise / Pergola (io)")

**Comment by StefanVersleeuwen** [comment]
Great, it worked. Thank you so much!
