### ISSUE TITLE
Homey flows can only set status or "move to MY position" in "then". Not open or close the roller blinds!

### ISSUE THREAD

**Issue by Kuhlwein1969** [AdyRock/com.somfy.tahoma#163]
I have several somfy rts roller blinds that are controlled manually with Situo 1/5 remote controls.
They can easily be created as a unit in Homey, but they cannot be scrolled down or up in a "flow". Flows can only set status or "move to MY position" in "then", - Not open or close the roller blinds! Thus, the integration to Somfy is useless!

**Comment by AdyRock** [comment]
You need to use the set state card and select either up or down from the list.

**Comment by Kuhlwein1969** [comment]
Yes, I have got it. The text in the app is translated incredibly poorly into Danish.

**Comment by AdyRock** [comment]
Unfortunately that is one of the built-in Homey capabilities so Athom do that translation.
