### ISSUE TITLE
Flow action for tilting Venetian blinds

### ISSUE THREAD

**Issue by JeroenHauser** [AdyRock/com.somfy.tahoma#168]
Good morning,

First, thanks for developing a great Tahoma <> Homey app! Very convenient in managing my Somfy home automations :)

I however experience one issue: while it is possible to tilt my Venetian blinds on the device actions screen, it is not possible to use the tilting action in a flow. Not sure if this is an issue or a missing / not implemented feature?

I'd very much would like to be able to tilt my Venetian blinds when executing a flow. Would you be so kind to make this possible?

![deviceActions](https://github.com/AdyRock/com.somfy.tahoma/assets/1898106/6c4b9f84-6d59-4159-af79-307a0bf4da19)

![tiltingMissingInFlow](https://github.com/AdyRock/com.somfy.tahoma/assets/1898106/a7d4a338-c3f3-497e-aaa1-95629bcfdc65)

**Comment by JeroenHauser** [comment]
Hi @AdyRock! Just informing, how do you think about making "Tilt up" and "Tilt down" actions available to flows? I'd love to include these actions into my morning and evening routines. Thanks!

**Comment by AdyRock** [comment]
The latest version does have a card for that:
![Screenshot_20240625_112359_Homey.jpg](https://github.com/AdyRock/com.somfy.tahoma/assets/38184396/124abb2d-1f49-41b5-bf14-892dc1963ca1)

However, as there is no feedback from the blinds and no command to set a specific position, it is a bit hit and miss. The command just sends one nudge command, the same as the buttons do.

**Comment by JeroenHauser** [comment]
Ah great! Looks like exactly what I was aiming for. And yes, I’m aware that RTS doesn’t feedback.

However, for some reason I don’t see the new action card yet. Has it been released to Homey already? I just double checked: I have automatic updates enabled. My “Somfy TaHoma & Connexoon” currently is at version 4.0.81.

**Comment by AdyRock** [comment]
It's currently in the test version. You can get that from the store by adding /test to the end of the url.
