### ISSUE TITLE
ExteriorScreen

### ISSUE THREAD

**Issue by keolse** [AdyRock/com.somfy.tahoma#17]
Possible to get support for exteriorscreen rts? Have sent you a log file.

**Comment by AdyRock** [comment]
Yes, no problem. Looks pretty straightforward to do that one.

**Comment by AdyRock** [comment]
There is a new test version with support for the external RTS blind.
I have also added support for the zwave motion detectors, light sensors and temperature sensors. As the basic support was already there it was only a matter of adding the controllable names.

**Comment by keolse** [comment]
Hello loaded app, and it crashed :/

**Comment by AdyRock** [comment]
How did you load it, was it downloaded from the store?
I don't have any crash reports in my portal so wondering if you loaded via the CLI?

**Comment by keolse** [comment]
Yes, with cli. Looks like file is just 7 mb. When i download from github.

**Comment by AdyRock** [comment]
Have used npm update to get the node_js libraries as I don't' store them on Github?

**Comment by AdyRock** [comment]
Either that or install it from the Athom store. Just add /test to the end of the URL.

**Comment by keolse** [comment]
hello, added /test in url. Working now :)

**Comment by keolse** [comment]
Would it be possible to make have up/down activ when pushed?

**Comment by AdyRock** [comment]
I presume you mean the tile?
If so, then not really. As it is RTS there is no feedback to get the active state so there is no way to know if the tile should move up or down when pressed.

**Comment by keolse** [comment]
Yes, okay. Thanks for fast reply! :)
