### ISSUE TITLE
Somfy motor in Sunsetter awning

### ISSUE THREAD

**Issue by Netwitz** [AdyRock/com.somfy.tahoma#170]
I have a Sunsetter brand retractable awning in the United States. According to the Sunsetter website, it uses a Somfy motor. Is there any way to use your app to integrate my awning if it isn’t an actual Somfy awning, but just the motor?

**Comment by AdyRock** [comment]
The app only works with one of the Somfy hubs, but if the awning can be added to one of those then it will work with the app.
the supported hubs are Tahoma, Connexoon and the Connectivity kit. You will need to find out if the motor uses RTS or IO as some of the hubs come with support for one or the other. Tahoma will support both types.
