### ISSUE TITLE
Somfy Smart 800 io garage door motor.

### ISSUE THREAD

**Issue by 26081971** [AdyRock/com.somfy.tahoma#171]
Hi,
I have some issue to connect my Somfy connectivity kit to Somfy app in Homey pro 2023. I have just sendt you a log from the Homey app. When I try to add device in the app. I just get a replay, cannot find new device.

Kindly ask you for support.

Best regards
Kurt

**Comment by AdyRock** [comment]
I have added your garage Door to the 'Garage Door - Open and Close (io)'.
Let me know if there are any issues.

**Comment by 26081971** [comment]
Hi, it works. Thanks for the help.
Best regards Kurt
