### ISSUE TITLE
Somfy IO sun screens cannot be added to Homey Pro (android)

### ISSUE THREAD

**Issue by Sdee007** [AdyRock/com.somfy.tahoma#176]
Recently installed Somfy IO screens which are paired with Situo 5 IO pure II remote and Tahoma app. Screens works fine with remote and Tahoma app. But I cannot add any screens to the Homey Pro via Somfy & Connexoon App. Here the workflow

1) Added screens to Tahoma app on android (Window coverings > Exterior shades > Shutters
(When installed they are shown as Valances in the app)
2) Installed Somfy & Connexoon App in Homey Pro
3) Add Device > Select Somfy & Connexoon App > Select "Exterior blind (io)" under Sunshade category
4) click Connect on next dialog
5) Login with Tahoma account credentials (only first time)
6) Get the message "No new devices have been found"

Note:
I can add "Tahoma/Connexoon" hub though. But it dosn't seem to have any useful feature to control screens

**Comment by AdyRock** [comment]
Can you try other device options in Homey as manufactures mix and match motors these days, so it may appear as a Velux screen, etc.
If still you can't find it then send me the Device log from the app settings screen. You will need to tap on the Get Log button first and, once the list is filled, tap on the Send Log button.

**Comment by Sdee007** [comment]
Thanks for the super fast response. I have tried several options and finally managed to get them in with "Awning/Pergola (io)" option. You can close the issue.

Btw: Im seeing a minor UX issue where up and down buttons work in opposite way. (i.e. down button makes the screens go up and up button makes the screen go down). Hope you can fix it in a future release

**Comment by AdyRock** [comment]
You should be able to reverse the direction in the device advanced settings page.

**Comment by Sdee007** [comment]
Perfect.
