### ISSUE TITLE
cant login in to the app on homey

### ISSUE THREAD

**Issue by wollie27** [AdyRock/com.somfy.tahoma#177]
hi, 

I try to login in to the app on homey because I want to connect my 2 sun screens. 
I got this fault code .. log ID: -825494690

hope you can help me @AdyRock

**Comment by AdyRock** [comment]
The error code 401 means unauthorised. Check to make sure you have entered the correct credentials for your Tahoma account when adding devices.

**Comment by wollie27** [comment]
hi,

I use the same credentials to log in to the website?

**Comment by AdyRock** [comment]
Sorry I can't help more, but from the error code, Somfy is rejecting your credentials. 
Make sure you enter them exactly as you set them up. Also, make sure you have selected the correct region ![Screenshot_20240527_094004_Homey.jpg](https://github.com/AdyRock/com.somfy.tahoma/assets/38184396/1e412ae0-0dd8-417a-bc1f-3b0fd8dcf04e)

**Comment by JcsinFL** [comment]
I am having the same issue. I definitely have the correct user password and the correct region is set. Wollie, did you get yours working?
