### ISSUE TITLE
Store in Tahoma app but not in homey

### ISSUE THREAD

**Issue by valafay** [AdyRock/com.somfy.tahoma#179]
Hi, I got an issue where I got 4 io blind in my Tahoma app but I cannot have them in the homey app.

I send the journal using -231178666 the blind missing on my homey app are named 

"trapeze nono"
"trapeze Julia"
"grand store nono"
"grand store Julia"

thanks in advance.

**Comment by AdyRock** [comment]
The device are RTS according to the type reported in the log, so use the 'Blind or Shutter (RTS)'
```
        "label": "trapeze nono",
        "controllableName": "rts:RollerShutterRTSComponent",

```

**Comment by valafay** [comment]
perfect =) you made my day thanks a lot =) have a great day and weekend
