### ISSUE TITLE
Somfy Tahoma app not finding any devices

### ISSUE THREAD

**Issue by suma1010** [AdyRock/com.somfy.tahoma#182]
Hello
I recently bought a Somfy Tahoma box to control my four Somfu IO exterior screens. I am able to log into my Somfy account in the app, but I am not able to locate any devices. Nor the remote. The Somfy standalone app itself works great. I have sent a devide log with ID 671434207. Hope this helps.

**Comment by suma1010** [comment]
Homey Somfy app was able to add my "Box", but I was not able to locate any of my screens/the remote. Edit: I have enabled "advanced mode" in the Somfy account.

**Comment by AdyRock** [comment]
Try the "Awning / Pergola (io)" device. Hopefully, that should find your screen.

**Comment by suma1010** [comment]
That solution worked. Thank you very much!
