### ISSUE TITLE
Lux data not visible in the homey app

### ISSUE THREAD

**Issue by wannes62** [AdyRock/com.somfy.tahoma#188]
I could install the sunis io in the tahoma box and it works fine, but the lux data is not visible in the homey.
Is there a solution for it?

**Comment by AdyRock** [comment]
Have you added the sunis to Homey?

**Comment by wannes62** [comment]
***@***.***

Van: Adrian Rockall ***@***.***>
Verzonden: maandag 19 augustus 2024 22:18
Aan: AdyRock/com.somfy.tahoma ***@***.***>
CC: wannes62 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.somfy.tahoma] Lux data not visible in the homey app (Issue #188)


Have you added the sunis to Homey?

**Comment by AdyRock** [comment]
Sorry, Github doesn't handle replies via email very well so I can't understand. Could you open Github and reply that way please.

**Comment by wannes62** [comment]
![Schermafbeelding 2024-08-19 231336](https://github.com/user-attachments/assets/90a4e900-5531-4b1f-8b0b-2d407db7caa8)

**Comment by AdyRock** [comment]
If you restart the app, do you then see a value?
The app only requests data at start up and when a device is added. After that it relies on notifications via events and data is only passed via events when it changes. So, if the fetch failed when the device was added, it won't update until the next event after a value change. I presume it was dark when you added the sunis, so it won't provide any further data until it starts to get light again. 

If you still don't have any value displayed tomorrow then could you open the app settings page and select the Information Log tab, then enable the Log and reboot the app. After it has started up, go back to the log and Send it.

**Comment by wannes62** [comment]
I deleted the app from the homey and installed it again.
After that the problem was fixed.
