### ISSUE TITLE
Somfy radiator valve

### ISSUE THREAD

**Issue by IvoRoersma** [AdyRock/com.somfy.tahoma#19]
Is it possible to add this product in the somfy app in the homey ?
![image](https://user-images.githubusercontent.com/27553281/106595764-5143fb00-6554-11eb-9381-c96fdb1afdc5.jpg)

Somfy Thermostatic Radiator Valve

[Somfy manuel](https://www.somfy.nl/file.cfm/Somfy_TRV_NL.pdf?contentid=446902)

**Comment by AdyRock** [comment]
Can you send me the Device Log from the App - Configure App screen?

**Comment by IvoRoersma** [comment]
Yes,done! Thank you!

**Comment by AdyRock** [comment]
I have had a look at the log and it is going to take a bit of time to work out what features can be added. I have also got a bit of a queue of difficult devices that I am working through. If a simple one crops up that just needs an id added to a table then I add them quickly. However, these types required a complete new driver and custom capabilities, plus I have to try and mary up read and write properties so takes a bit longer.

**Comment by IvoRoersma** [comment]
Any luck so far ? Ps I did update my TaHoma

**Comment by AdyRock** [comment]
I haven't forgotten, just got a lot on at the moment. 
I will try and add it in tomorrow.

**Comment by IvoRoersma** [comment]
Thank you !

**Comment by AdyRock** [comment]
Can you tell me what temperatures you can set via the Tahom app?

The interface has a command to set 4 temperatures, but there are 8 temperatures reported. As the information does not specify what the 4 temperatures are (the command just takes 4 parameters), I have no idea what they will set or in what order they should be. So this bit is going to be a 'trial and error' method.

**Comment by IvoRoersma** [comment]
@Home 20
Night 16
Out home 16
Frost protection 12
Perhaps the two others ar (valves settings (minimum 5 & maximum 26)

Ps. Did a new report :

4e6db485-7530-4fce-8d9b-0e9bf2062d11

**Comment by AdyRock** [comment]
That sort of helps. The parameters reported in the previous log are:
--> core:ComfortRoomTemperatureState					= 20
--> core:DerogatedTargetTemperatureState					= 22
--> core:EcoTargetTemperatureState						= 16
--> core:FrostProtectionRoomTemperatureState				= 16

--> io:AwayModeTargetTemperatureState					= 16
--> io:ManualModeTargetTemperatureState					= 22
--> io:OpenWindowDetectedTargetTemperatureState			= 8
--> io:GeofencingModeTargetTemperatureState				= 20

I guess you sent the new report via the Athom method, but unfortunately that doesn't show me the information I need. I need the Device Log from the Configure App screen.

**Comment by IvoRoersma** [comment]
Where do I make that report?  In the TaHoma link.com  can't find it there...

**Comment by AdyRock** [comment]
It's the one you sent at the start, so the Somfy & Connexoon app in the Homey app, tap on Configure application, select the Device log tab and then Get Log and then on Send Log once the list is populated.

I have nearly finished a first attempt. Are you happy to download the app from Github and then run it from the CLI?
It will save me publishing a test version to the store, but if you are not comfortable then don't worry.

**Comment by IvoRoersma** [comment]
Log is send

**Comment by IvoRoersma** [comment]
Yes please ;-)

**Comment by AdyRock** [comment]
OK, I have pushed the new version to Github.

I still have a few images to sort out but hopefully it should be a working solution.

As I mention, I'm not sure about the temperature settings and also the Derogation Mode and Operating Type are set via an array.
If you check that the correct temperatures are displayed by changing them in the Somfy app, waiting for the "Update Interval" time period to elapse and then see if the correct value has changed in the Homey app. If there is a discrepancy then let me know which if any of the Homey temperatures change when you change a Somfy temperature. I would recommend changing one setting at a time so it is easier to see the cause and effect.
If all the Somfy to Homey temperatures seems to match, then check the other way around by changing a value in Homey and make sure it changes the correct value in Somfy.

**Comment by IvoRoersma** [comment]
Can't get cli working on my Mac :-(

**Comment by AdyRock** [comment]
I can't say I know much about Mac's but what is the issue?

**Comment by IvoRoersma** [comment]
Get a error with permission in the command prompt when I try to instal

**Comment by AdyRock** [comment]
Is that when you try to install the app on Homey?
Have you tried to run 'npm update'?

**Comment by AdyRock** [comment]
Have you managed to get the CLI working or do you want me to publish a test version?

**Comment by IvoRoersma** [comment]
Nop no succes with the cli
If you can put it online then please 😇

**Comment by AdyRock** [comment]
It's there:
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

**Comment by IvoRoersma** [comment]
Sorry did not had much time. But just did the install. 
1.He don't see the current temp. And also not the temp.that was set.

2.Valve state, when you clic on it. I get the message"fail to send command"

3.In the TaHoma I have 5options: away,at-home,night,manual,frost-protection.(and the auto-progamming / manual-forcing > until new order)
![image](https://user-images.githubusercontent.com/27553281/108642799-9a2e0600-74a7-11eb-9a3a-ed9b73738ade.png)
![image](https://user-images.githubusercontent.com/27553281/108642814-b16cf380-74a7-11eb-85c3-74020253bcc0.png)

4. I don't really understand this. Window open/ heating mode ?

5. Battery status, 😃

6. Flow

Hope you can do something with this feed back ?

Many Thanks,
Ivo

**Comment by AdyRock** [comment]
I have posted a new test version.
1. Added what I think might be the current temperature. Unfortunately, the status description is not very clear. The set temperatures are all shown on the first page. Use the drop list to select each one.
2. The command must be for something different, so I have changed it to a status indication only.
3. To view / change the modes, select the option from the drop list on the second page. I have renamed the items to hopefully match the ones ones you show in Tahoma.
4. Me neither, but they are reported so i show them ;-)
5. 👍 
6. Flows take a long time to configure, so I will add them once we have got the interface working. No point me spending hours on them when they could all change :-)

If things still don't work as expected then I will need you to log the commands sent by Tahoma. To do that, enable the logging in my app, on the configuration page, operate a valve from Tahoma, wait for the log to capture the commands, send me the log.
It would be best if you could send a seperate log for each change you make in Tahoma amd then let me know what was changed.
I'm not sure if you are aware of https://developer.athom.com/tools/app-settings. But this might be the easiest way to log the data.
If we get to that point then we can discuss it more if you need help.

**Comment by AdyRock** [comment]
I got your log.
I forgot to mention you will need to delete the valves and add them back in to remap the new capabilities.

**Comment by AdyRock** [comment]
I'm just looking back at open issues and I wonder if you could remind me if there is anything else I need to do on this one. My memory is not so good these days unfortunately.
