### ISSUE TITLE
TaHoma on Homey does not work

### ISSUE THREAD

**Issue by ghost** [AdyRock/com.somfy.tahoma#190]
Hi, I've just included my Tahoma Connexoon Box to my Homey Bridge.
Inclusion completed successfully but the device does not respond to any command by Homey (whilst it perfectly works by its official app TaHoma Somfy).
Can you help me?
Thanks for your cooperation, best regards.

**Comment by AdyRock** [comment]
When you say Homey Bridge, do you mean you have a Homey cloud account?
What have you included that isn't working?

**Comment by ghost** [comment]
Yes I have a Homey Premium Account.I included a TaHoma Connexoon Box that isn't working by Homey App (but still working by its official app TaHoma Somfy)Francesco SantavenereInviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Adrian Rockall ***@***.***> Data: 13/09/24  17:36  (GMT+01:00) A: "AdyRock/com.somfy.tahoma" ***@***.***> Cc: Santacruz4 ***@***.***>, Author ***@***.***> Oggetto: Re: [AdyRock/com.somfy.tahoma] TaHoma on Homey does not work (Issue #190) 
When you say Homey Bridge, do you mean you have a Homey cloud account?
What have you included that isn't working?

**Comment by AdyRock** [comment]
Sorry, you will need to provide more details than 'it isn't working' because that leaves it open to a million possibilities.
At least say what you have tried and in what way it failed.

**Comment by ghost** [comment]
I have a Connexxonn Box to handle an electric curtain.With the app TaHoma Sofmy I can handle it with no problems, I can open and close the curtain.Recently I added the Connexxonn Box to my Homey account. Therefore I first added your app to Homey and then added my Connexxoon Box successfully.But when I try to use it through Homey the Box does not respond to my commands. I try to open the curtain but no reaction, whilst the same command coming from the TaHoma Sofmy app works properly.What kind of additional information should I give you?Francesco SantavenereInviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Adrian Rockall ***@***.***> Data: 13/09/24  21:07  (GMT+01:00) A: "AdyRock/com.somfy.tahoma" ***@***.***> Cc: Santacruz4 ***@***.***>, Author ***@***.***> Oggetto: Re: [AdyRock/com.somfy.tahoma] TaHoma on Homey does not work (Issue #190) 
Sorry, you will need to provide more details than 'it isn't working' because that leaves it open to a million possibilities.
At least say what you have tried and in what way it failed.

**Comment by AdyRock** [comment]
You say you added the box, but have you added the curtain to Homey?

**Comment by ghost** [comment]
Ok sorry I thought that adding the box automatically Homey would have added the curtain.I added the curtain as well so problem solved.Thank you guys.Francesco SantavenereInviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Adrian Rockall ***@***.***> Data: 13/09/24  22:19  (GMT+01:00) A: "AdyRock/com.somfy.tahoma" ***@***.***> Cc: Santacruz4 ***@***.***>, Author ***@***.***> Oggetto: Re: [AdyRock/com.somfy.tahoma] TaHoma on Homey does not work (Issue #190) 
You say you added the box, but have you added the curtain to Homey?
