### ISSUE TITLE
Error logging in after update

### ISSUE THREAD

**Issue by signalpower** [AdyRock/com.somfy.tahoma#194]
Hi.

Since v4.0.95 I’m unable to log in. I lost connection with my devices. The app settings was warning on my login info, so I tried logging out and entered my credentials again.

Now I get error `Failed to log in. Error: Cannot read properties of null (reading ‘authenticated’)`.
![IMG_3431](https://github.com/user-attachments/assets/e249db6f-3704-4873-94ba-f6fbb1674ddf)

There is no information in any logs in the app.

I have verified the login works on Somy website.
My setup is TaHoma Switch with IO devices.

A diagnostic report has been sent: 71ae1f38-e810-4476-8530-f719a51f2666

**Comment by signalpower** [comment]
Update: I rebooted the Homey Pro. The Somfy app did not start after reboot. I uninstalled an reinstalled it, and now it won’t start any more.

**Comment by AdyRock** [comment]
What do you mean by it won't start?

**Comment by signalpower** [comment]
> What do you mean by it won't start?

The app just shows as `Starting...`

![image](https://github.com/user-attachments/assets/1de75fcb-c1f7-461f-b6c1-d7bfe90c1a6d)

I have restarted the Homey Pro, uninstalled, then restarted and reinstalled and still it will not start. I'm also opening a support request with Homey support to see if they might be able to help me.

**Comment by signalpower** [comment]
After connecting my Homey Pro directly to my computer and reinstalling the firmware it started working again, so this was a Homey issue, and not the app.
