### ISSUE TITLE
Information IO motors somfy 

### ISSUE THREAD

**Issue by SVDK331** [AdyRock/com.somfy.tahoma#2]
{
         "creationTime":1593528977000,
         "lastUpdateTime":1593528977000,
         "label":"Tuin Rechts",
         "deviceURL":"///",
         "shortcut":false,
         "controllableName":"io:VerticalInteriorBlindGenericIOComponent",
         "definition":{
            "commands":[
               {
                  "commandName":"close",
                  "nparams":0
               },
               {
                  "commandName":"delayedStopIdentify",
                  "nparams":1
               },
               {
                  "commandName":"down",
                  "nparams":0
               },
               {
                  "commandName":"getName",
                  "nparams":0
               },
               {
                  "commandName":"identify",
                  "nparams":0
               },
               {
                  "commandName":"my",
                  "nparams":0
               },
               {
                  "commandName":"open",
                  "nparams":0
               },
               {
                  "commandName":"refreshMemorized1Position",
                  "nparams":0
               },
               {
                  "commandName":"setClosure",
                  "nparams":1
               },
               {
                  "commandName":"setMemorized1Position",
                  "nparams":1
               },
               {
                  "commandName":"setName",
                  "nparams":1
               },
               {
                  "commandName":"setPosition",
                  "nparams":1
               },
               {
                  "commandName":"setSecuredPosition",
                  "nparams":1
               },
               {
                  "commandName":"startIdentify",
                  "nparams":0
               },
               {
                  "commandName":"stop",
                  "nparams":0
               },
               {
                  "commandName":"stopIdentify",
                  "nparams":0
               },
               {
                  "commandName":"up",
                  "nparams":0
               },
               {
                  "commandName":"wink",
                  "nparams":1
               },
               {
                  "commandName":"pairOneWayController",
                  "nparams":2
               },
               {
                  "commandName":"unpairAllOneWayControllers",
                  "nparams":0
               },
               {
                  "commandName":"unpairOneWayController",
                  "nparams":2
               }
            ],
            "states":[
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:ClosureState"
               },
               {
                  "values":[
                     "good",
                     "low",
                     "normal",
                     "verylow"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:DiscreteRSSILevelState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:Memorized1PositionState"
               },
               {
                  "type":"DataState",
                  "qualifiedName":"core:NameState"
               },
               {
                  "values":[
                     "closed",
                     "open"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:OpenClosedState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:PriorityLockTimerState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:RSSILevelState"
               },
               {
                  "type":"ContinuousState",
                  "qualifiedName":"core:SecuredPositionState"
               },
               {
                  "values":[
                     "available",
                     "unavailable"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"core:StatusState"
               },
               {
                  "values":[
                     "comfortLevel1",
                     "comfortLevel2",
                     "comfortLevel3",
                     "comfortLevel4",
                     "environmentProtection",
                     "humanProtection",
                     "userLevel1",
                     "userLevel2"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"io:PriorityLockLevelState"
               },
               {
                  "values":[
                     "LSC",
                     "SAAC",
                     "SFC",
                     "UPS",
                     "externalGateway",
                     "localUser",
                     "myself",
                     "rain",
                     "security",
                     "temperature",
                     "timer",
                     "user",
                     "wind"
                  ],
                  "type":"DiscreteState",
                  "qualifiedName":"io:PriorityLockOriginatorState"
               }
            ],
            "dataProperties":[
               {
                  "value":"500",
                  "qualifiedName":"core:identifyInterval"
               }
            ],
            "widgetName":"PositionableScreen",
            "uiClass":"Screen",
            "qualifiedName":"io:VerticalInteriorBlindGenericIOComponent",
            "type":"ACTUATOR"
         },
         "states":[
            {
               "name":"core:NameState",
               "type":3,
               "value":"Tuin Rechts"
            },
            {
               "name":"core:PriorityLockTimerState",
               "type":1,
               "value":0
            },
            {
               "name":"core:StatusState",
               "type":3,
               "value":"available"
            },
            {
               "name":"core:DiscreteRSSILevelState",
               "type":3,
               "value":"normal"
            },
            {
               "name":"core:RSSILevelState",
               "type":2,
               "value":78.0
            },
            {
               "name":"core:ClosureState",
               "type":1,
               "value":98
            },
            {
               "name":"core:OpenClosedState",
               "type":3,
               "value":"open"
            }
         ],
         "available":true,
         "enabled":true,
         "placeOID":"///",
         "widget":"PositionableScreen",
         "type":1,
         "oid":"///",
         "uiClass":"Screen"
      },
     

-------
{
   "startTime":1597853744869,
   "owner":"///",
   "actionGroup":{
      "label":"Tuin Rechts - Sluiten - TaHoma PC",
      "shortcut":false,
      "notificationTypeMask":0,
      "notificationCondition":"NEVER",
      "actions":[
         {
            "deviceURL":"///",
            "commands":[
               {
                  "type":1,
                  "name":"close",
                  "parameters":[

                  ]
               }
            ]
         }
      ]
   },
   "description":"Execution : Tuin Rechts - Sluiten - TaHoma PC",
   "id":"07813ee3-ac10-3e01-2775-8dbb088861a8",
   "state":"IN_PROGRESS",
   "executionType":"Immediate execution",
   "executionSubType":"MANUAL_CONTROL"
}

**Comment by AdyRock** [comment]
This should be working in the version 1.6.15 available on the HCS https://store.homey.community/app/com.somfy.tahoma
Let me know if there are any issues.

**Comment by AdyRock** [comment]
Is this working OK?
Just wondering if it is OK to close the issue?
