### ISSUE TITLE
Water sensor

### ISSUE THREAD

**Issue by jkinformatik** [AdyRock/com.somfy.tahoma#20]
Please add the water sensor

device log

326373f1-c0cc-4a20-9b83-5289c227b958

**Comment by AdyRock** [comment]
Unfortunately the log I need is the Device Log. This is on a tab in the Configure App screen (which is the screen where you entered your log in details).

When the tab is selected you will see a button with 'Get Log' on it. Tap on that and this list will fill up. Then tap on the 'Send Log' button to send the information to me.
The information shows me the required commands and status names to use for each device. I can also use that information as simulated input to partially test the code works.

**Comment by jkinformatik** [comment]
I have sent the log now ...

**Comment by AdyRock** [comment]
I received several logs yesterday but I can't find one that has anything that looks like a water sensor.
What is the name of the sensor in your Tahoma app?

**Comment by jkinformatik** [comment]
The name is "Waschküche-Wasser" in Tahoma

**Comment by AdyRock** [comment]
Aha, found it. The log was so big it didn't all fit in my email viewer :-)
After searching for the name it loaded a different section.

**Comment by jkinformatik** [comment]
LIKE!
Do you think you can implement it?

**Comment by AdyRock** [comment]
Yep, no problem.

**Comment by AdyRock** [comment]
I need to provide an image of the device for the Athom store. Can you give me  a link to a web page that shows it?

**Comment by jkinformatik** [comment]
here you can see the product https://shop.somfy.de/funk-wassermelder.html

**Comment by AdyRock** [comment]
I have published a test version with support for the sensor:
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

**Comment by jkinformatik** [comment]
I think it's running

**Comment by jkinformatik** [comment]
In this version I get a lot of events, that a I/o open-close-detector (name: "Garagentor") changes his status !!!???
That wasn't before

**Comment by AdyRock** [comment]
Where are you seeing the events?

**Comment by jkinformatik** [comment]
in the homey app

**Comment by jkinformatik** [comment]
every few minutes

**Comment by AdyRock** [comment]
Where in the app?

**Comment by jkinformatik** [comment]
homepage - timeline

**Comment by AdyRock** [comment]
Is the sensor active all the time?
Could you enable the Information Log in the app configuration screen, wait for a few minutes and then send the log?

**Comment by jkinformatik** [comment]
yes it's active, I will send the log ...

**Comment by jkinformatik** [comment]
When I try to send the log I get the message "ERROR" - I alrady tried it 5 times ...

**Comment by jkinformatik** [comment]
By trying to send the log in the log was the information "connection timeout" ...

**Comment by jkinformatik** [comment]
sorry - here is the log:

[
  {
    "time": "2021-02-16T13:47:59.096Z",
    "source": "Register Events",
    "data": "Starting"
  },
  {
    "time": "2021-02-16T13:49:59.211Z",
    "source": "Register Events",
    "data": "Starting"
  },
  {
    "time": "2021-02-16T13:51:59.368Z",
    "source": "Register Events",
    "data": "Starting"
  },
  {
    "time": "2021-02-16T13:51:59.372Z",
    "source": "Tahoma Login",
    "data": {
      "message": "Start Simple Login",
      "stack": {
        "linkURL": "default"
      }
    }
  },
  {
    "time": "2021-02-16T13:52:00.194Z",
    "source": "Tahoma Simple Login",
    "data": {
      "message": "Successful",
      "stack": {
        "success": true,
        "roles": [
          {
            "name": "ENDUSER"
          }
        ]
      }
    }
  },
  {
    "time": "2021-02-16T13:52:00.200Z",
    "source": "post",
    "data": "/events/register"
  },
  {
    "time": "2021-02-16T13:52:00.632Z",
    "source": "Register Events",
    "data": {
      "message": "Success",
      "stack": {
        "id": "ab1cb21a-ac10-3e01-0169-e76274df8874"
      }
    }
  },
  {
    "time": "2021-02-16T13:52:00.641Z",
    "source": "Device status update",
    "data": "Renewing"
  },
  {
    "time": "2021-02-16T13:52:00.644Z",
    "source": "Device initial sync.",
    "data": "Schlafzimmer Rollo"
  },
  {
    "time": "2021-02-16T13:52:00.647Z",
    "source": "Device initial sync.",
    "data": "Wohnzimmer Rollo"
  },
  {
    "time": "2021-02-16T13:52:00.684Z",
    "source": "Device initial sync.",
    "data": "Garagentor"
  },
  {
    "time": "2021-02-16T13:52:00.710Z",
    "source": "Device initial sync.",
    "data": "Tür Technikbereich"
  },
  {
    "time": "2021-02-16T13:52:00.744Z",
    "source": "Device initial sync.",
    "data": "Keller Bewegungsm"
  },
  {
    "time": "2021-02-16T13:52:00.788Z",
    "source": "Device initial sync.",
    "data": "Flur Bewegungsm"
  },
  {
    "time": "2021-02-16T13:52:00.803Z",
    "source": "Device initial sync.",
    "data": "Eingang Bewegungsm"
  },
  {
    "time": "2021-02-16T13:52:00.830Z",
    "source": "Device initial sync.",
    "data": "Link"
  },
  {
    "time": "2021-02-16T13:52:00.834Z",
    "source": "Device initial sync.",
    "data": "Büro Simulator"
  },
  {
    "time": "2021-02-16T13:52:00.848Z",
    "source": "Device initial sync.",
    "data": "Terrasse Licht"
  },
  {
    "time": "2021-02-16T13:52:00.860Z",
    "source": "Device initial sync.",
    "data": "Wohnzimmer Stehlampe"
  },
  {
    "time": "2021-02-16T13:52:00.888Z",
    "source": "Device initial sync.",
    "data": "Büro Luftfilter"
  },
  {
    "time": "2021-02-16T13:52:00.897Z",
    "source": "Device initial sync.",
    "data": "Wohnzimmer Licht"
  },
  {
    "time": "2021-02-16T13:52:00.911Z",
    "source": "Device initial sync.",
    "data": "Küche Licht"
  },
  {
    "time": "2021-02-16T13:52:00.915Z",
    "source": "Device initial sync.",
    "data": "Keller Licht"
  },
  {
    "time": "2021-02-16T13:52:00.951Z",
    "source": "Device initial sync.",
    "data": "Büro Rauch"
  },
  {
    "time": "2021-02-16T13:52:00.955Z",
    "source": "Device initial sync.",
    "data": "Fitness Rauch"
  },
  {
    "time": "2021-02-16T13:52:00.987Z",
    "source": "Device initial sync.",
    "data": "Esszimmer Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.009Z",
    "source": "Device initial sync.",
    "data": "OG Vorraum Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.013Z",
    "source": "Device initial sync.",
    "data": "Waschküche Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.088Z",
    "source": "Device initial sync.",
    "data": "Wellness Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.112Z",
    "source": "Device initial sync.",
    "data": "Gäste Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.115Z",
    "source": "Device initial sync.",
    "data": "Küche Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.175Z",
    "source": "Device initial sync.",
    "data": "Schlafzimmer Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.196Z",
    "source": "Device initial sync.",
    "data": "Flur Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.210Z",
    "source": "Device initial sync.",
    "data": "Party Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.232Z",
    "source": "Device initial sync.",
    "data": "Basteln Rauch"
  },
  {
    "time": "2021-02-16T13:52:01.291Z",
    "source": "Device initial sync.",
    "data": "Waschküche-Wasser"
  },
  {
    "time": "2021-02-16T13:52:01.326Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F12981937/states"
  },
  {
    "time": "2021-02-16T13:52:01.334Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F14732749/states"
  },
  {
    "time": "2021-02-16T13:52:01.342Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F13257908/states"
  },
  {
    "time": "2021-02-16T13:52:01.409Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F13775896/states"
  },
  {
    "time": "2021-02-16T13:52:01.460Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F9294409/states"
  },
  {
    "time": "2021-02-16T13:52:01.492Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F8857217/states"
  },
  {
    "time": "2021-02-16T13:52:01.537Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F16341065/states"
  },
  {
    "time": "2021-02-16T13:52:01.558Z",
    "source": "get",
    "data": "/setup/devices/myfox%3A%2F%2FSOMFY_PROTECT-Nu9pqzYqmteU5AATZv6Od0BL4VzeaRIO%2Fsite_alarm/states"
  },
  {
    "time": "2021-02-16T13:52:01.564Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F14977928/states"
  },
  {
    "time": "2021-02-16T13:52:01.571Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F10871801/states"
  },
  {
    "time": "2021-02-16T13:52:01.583Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F13517341/states"
  },
  {
    "time": "2021-02-16T13:52:01.600Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F7030015/states"
  },
  {
    "time": "2021-02-16T13:52:01.613Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F12382131/states"
  },
  {
    "time": "2021-02-16T13:52:01.623Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F6434699/states"
  },
  {
    "time": "2021-02-16T13:52:01.638Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F1624675/states"
  },
  {
    "time": "2021-02-16T13:52:01.656Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F5485514/states"
  },
  {
    "time": "2021-02-16T13:52:01.672Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F9683478/states"
  },
  {
    "time": "2021-02-16T13:52:01.687Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F8942964/states"
  },
  {
    "time": "2021-02-16T13:52:01.703Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F8968889/states"
  },
  {
    "time": "2021-02-16T13:52:01.724Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F8965220/states"
  },
  {
    "time": "2021-02-16T13:52:01.739Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F9615648/states"
  },
  {
    "time": "2021-02-16T13:52:01.755Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F13137065/states"
  },
  {
    "time": "2021-02-16T13:52:01.774Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F7583593/states"
  },
  {
    "time": "2021-02-16T13:52:01.791Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F7474795/states"
  },
  {
    "time": "2021-02-16T13:52:01.833Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F10453931/states"
  },
  {
    "time": "2021-02-16T13:52:01.858Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F12476801/states"
  },
  {
    "time": "2021-02-16T13:52:01.881Z",
    "source": "get",
    "data": "/setup/devices/io%3A%2F%2F1232-2810-9860%2F2399629/states"
  },
  {
    "time": "2021-02-16T13:52:01.887Z",
    "source": "get",
    "data": "/setup/devices/rtds%3A%2F%2F1232-2810-9860%2F721810/states"
  },
  {
    "time": "2021-02-16T13:52:06.303Z",
    "source": "Device status update",
    "data": "Complete"
  },
  {
    "time": "2021-02-16T13:54:14.214Z",
    "source": "Send log error",
    "data": {
      "message": "Connection timeout",
      "stack": "Error: Connection timeout
                at SMTPConnection._formatError (/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
                at SMTPConnection._onError (/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
                at Timeout.<anonymous> (/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
                at listOnTimeout (internal/timers.js:549:17)
                at processTimers (internal/timers.js:492:7)"
    }
  },
  {
    "time": "2021-02-16T13:56:07.476Z",
    "source": "Fetch Events",
    "data": {
      "message": "Request failed with status code 400",
      "stack": "Error: Request failed with status code 400
                at createError (/node_modules/axios/lib/core/createError.js:16:15)
                at settle (/node_modules/axios/lib/core/settle.js:17:12)
                at /node_modules/axios-cookiejar-support/lib/interceptors/response.js:83:25
                at new Promise (<anonymous>)
                at responseInterceptor (/node_modules/axios-cookiejar-support/lib/interceptors/response.js:82:9)
                at /node_modules/axios-cookiejar-support/lib/index.js:130:67
                at processTicksAndRejections (internal/process/task_queues.js:97:5)
                at async HttpHelper.post (/lib/HttpHelper.js:218:34)
                at async Function.getEvents (/lib/Tahoma.js:410:36)
                at async myApp.syncLoop (/app.js:595:36)"
    }
  },
  {
    "time": "2021-02-16T13:56:07.509Z",
    "source": "syncLoop",
    "data": "Request failed with status code 400"
  },
  {
    "time": "2021-02-16T13:56:20.392Z",
    "source": "Send log error",
    "data": {
      "message": "Connection timeout",
      "stack": "Error: Connection timeout
                at SMTPConnection._formatError (/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
                at SMTPConnection._onError (/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
                at Timeout.<anonymous> (/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
                at listOnTimeout (internal/timers.js:549:17)
                at processTimers (internal/timers.js:492:7)"
    }
  },
  {
    "time": "2021-02-16T13:59:10.300Z",
    "source": "Send log error",
    "data": {
      "message": "Connection timeout",
      "stack": "Error: Connection timeout
                at SMTPConnection._formatError (/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
                at SMTPConnection._onError (/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
                at Timeout.<anonymous> (/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
                at listOnTimeout (internal/timers.js:549:17)
                at processTimers (internal/timers.js:492:7)"
    }
  },
  {
    "time": "2021-02-16T13:59:49.012Z",
    "source": "Send log error",
    "data": {
      "message": "Connection timeout",
      "stack": "Error: Connection timeout
                at SMTPConnection._formatError (/node_modules/nodemailer/lib/smtp-connection/index.js:774:19)
                at SMTPConnection._onError (/node_modules/nodemailer/lib/smtp-connection/index.js:760:20)
                at Timeout.<anonymous> (/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
                at listOnTimeout (internal/timers.js:549:17)
                at processTimers (internal/timers.js:492:7)"
    }
  }
]

**Comment by AdyRock** [comment]
I got the log and deleted it from here just in case someone finds the device ID's useful. Can't use them without your loggin but I would rather be safe.
What do you have your Update Interval set to? It looks like it's 2 minutes. If so, then maybe reduce that to about 30 second.
If the session is idle for too long it is closed by the server. That means homey has to log in again and do a full fetch of the data as it would have missed the event notifications.

**Comment by jkinformatik** [comment]
it looks better

**Comment by AdyRock** [comment]
I presume this is OK now but please get back to me if you still have problems.
