### ISSUE TITLE
IO Plug

### ISSUE THREAD

**Issue by Auraya83** [AdyRock/com.somfy.tahoma#21]
Thanks for the Product.
I Miss something.
Actually The App  currently finds all IO PLUGs & Izymo UP on / off as Lamps. But there also consumers (subwoofers). Maybe you can insert this as a socket?

**Comment by AdyRock** [comment]
I sure if there is enough information is the returned information to automatically determine that but I can probably add an option in the advanced setting to change the device class.
Could you send me your Device log so I can investigate and simulate this?

**Comment by Auraya83** [comment]
Do you have become the log? I became an error. "Name is "Subwoofer" ("Plug io")

**Comment by AdyRock** [comment]
I didn't get the log but I have tracked down the cause of that so could you send it again please?

**Comment by Auraya83** [comment]
OK. now it worked.

**Comment by AdyRock** [comment]
Just out of interest, what is the issue with them being inserted as lights?

I only ask as when I change the class to socket, it behaves exactly the same. The only difference is there is no orange circle shown in the tile.
Yes, you can select a sub class, but apart from the orange circle when you select a light subclass, it has no effect that I can see.

So I'm just wondering what you are trying to achieve so I can see if I can make that possible.

**Comment by Auraya83** [comment]
I Would Subwoofer, Pc... , Notebook Plug as On/Off Plug.

**Comment by AdyRock** [comment]
Very Sorry, but I don't understand?
