### ISSUE TITLE
Tahoma update

### ISSUE THREAD

**Issue by FPPMvB** [AdyRock/com.somfy.tahoma#22]
After the Tahoma Update from this weekend the old issue is back. 
Data from the Sunris is no longer shared with Homey. So no lightsensor information.
Adrian please check, you have done wonders before, hope you can ve of some help.

Thxzz Frank

**Comment by AdyRock** [comment]
Hmm, still working for me.
Could you enable the Information log, let it capture data for a while (10 minutes or so) and then send the log.
Also it might be useful to get the Device log. So click on the Get log button, wait for the list to fill and then click on Send Log.

**Comment by FPPMvB** [comment]
It looks like the login is no longer working. "Error Failed to authenticate" but LOGIN and PW are correct (checked it 5 times)

**Comment by FPPMvB** [comment]
And also checked the same PW on the Tahoma box it is working there so what has changed?
I'm using the 2.1.54 app version

**Comment by FPPMvB** [comment]
And when I push the logout button, also error message:

Uitloggen niet gelukt.
usernameEl.val is not a function. (In 'usernameEl.val('')', 'usernameEl.val' is undefined)

**Comment by FPPMvB** [comment]
Log send at 16:42

**Comment by FPPMvB** [comment]
I don't know how, but after the 24th attempt the app logged on

**Comment by AdyRock** [comment]
> And when I push the logout button, also error message:
> 
> Uitloggen niet gelukt.
> usernameEl.val is not a function. (In 'usernameEl.val('')', 'usernameEl.val' is undefined)

I have fixed that one now so will be in the next update.

**Comment by AdyRock** [comment]
I see you are not using the default connection, is that because you found it didn't work or because you have a Connexoon RTS box?

It might be worth trying the default to see if it is better.
