### ISSUE TITLE
Re-boot Homey,

### ISSUE THREAD

**Issue by FPPMvB** [AdyRock/com.somfy.tahoma#23]
Hi Ady, tofay again after the re-boot of my home i can no longer logon to the app
Login snd PW haven't changed but login diesn't work anymore. I will send the logfiles seperatly
Frank

**Comment by AdyRock** [comment]
I can't see anything unusual about the login but the 401 error code comes back from Somfy which is the unauthorised response. 
I do get this myself occasionally and it normally sorts itself out after a while. 
I  can only put it down to a temporary issue on the server. Unfortunately as the app uses the unofficial API, even though it's now allowed, Somfy don't give any support.

**Comment by FPPMvB** [comment]
Hi Adrian,
Thanks for the quick response, and yes after a while the issue solved itselve
Thanks

Met vriendelijke Groeten,
Frank van Berkel

**Comment by AdyRock** [comment]
The great, thanks for letting me know.
