### ISSUE TITLE
Dependency on Somfy Box?

### ISSUE THREAD

**Issue by ultimate-tester** [AdyRock/com.somfy.tahoma#25]
Hi AdyRock,

I just wanted to verify quickly: Do you or do you not need a TaHoma box or Connexoon IO box to make this app work? 
The reason I'm asking is because I would like to prevent any additional boxes to Homey itself. In other words I'm deciding between Somfy RTS and Somfy IO and whether IO needs boxes would eliminate this option.

Could you help me out to understand it properly? Thanks in advance!

**Comment by AdyRock** [comment]
This app **does** need either the Tahoma or Connexoon box.
Somfy IO **does** need either the Tahoma or Connexxon IO box.
Somfy RTS can use either the Tahoma or Connexoon RTS box or Homey directly via the Somfy RTS app.

Homey can not directly control any IO devices.

Hope that answers your questions?

**Comment by ultimate-tester** [comment]
Hi AdyRock, thanks for the quick reply. That indeed answers the question, I will have to go the RTS route if I don't want to add additional boxes. 

I am curious however, why the Homey cannot control IO devices directly. Is it because Homey has trouble to intercept messages on the frequency or is it because the data is encrypted and we don't have the keys to encrypt/decrypt the communication?

**Comment by AdyRock** [comment]
The IO protocol is a licensed comercial protocol. So, yes, it is encrypted and we don't have the encryption details plus a licence would have to be purchased to use it (legally). I believe the actual encryption and decryption is performed by a specific chip so that would have to be designed into Homey.
