### ISSUE TITLE
"Invalid data" and "Failed to send command"

### ISSUE THREAD

**Issue by Xuntar** [AdyRock/com.somfy.tahoma#26]
Hi!

First: thank you so much for this app! It's insanely useful!
I do seem to be having 2 issues lately (and I'm not sure if they're connected somehow).
I sometimes get the error "Failed to send command" when wanting to open or close a screen. Then when I check the logs, it also has a lot of "Invalid data" messages.

I've just sent you the log through the app. One of the timestamps with the error is "2021-05-17T09:01:58.961Z".

Please let me know if and how I can help.

**Comment by AdyRock** [comment]
I haven't seen those errors before. Can you try pausing the app for about 15 minutes and then restarting it?
That should force a new login just in case it has got out of sync in some way.

**Comment by Xuntar** [comment]
The odd thing is, this usually resolves itself after a couple of hours without any action on my part.
I'm trying your suggestion atm, and I'll keep you posted.
Thanks for the quick reply!

**Comment by AdyRock** [comment]
I will try checking for that error and make it trigger a log off and on cycle to see if that helps.

**Comment by Xuntar** [comment]
It started working again immediately after turning the app back on again. I'll keep you updated if it happens again.

Just one more small question if you don't mind. One of my screens is apparently installed differently than the app expects and is somehow "reversed" (if it's open, the app says it's closed and the other way around). In the official apps, the screen is actually listed as a horizontal awning instead of a vertical sunscreen (I'm guessing the installer used a different motor then normally used for a vertical screen, probably because the screen is rather large).
In the official app, the reversal problem is not there. Would it be a lot of work to add a setting enabling us to "reverse" the action on a per screen basis? This is definitely not urgent, but I figured it's worth asking ;-)

**Comment by AdyRock** [comment]
That option should already be in the app. Open the screen (long press on tile) in the app, then tap on the gear wheel in the top right corner. Select the Advanced Settings and there should be an option to Invert Up / Down. Tap on that and then change the toggle. then tap on the back arrow in the top left and finally click on the tick in the top right.

**Comment by Xuntar** [comment]
Thanks AdyRock! Can't believe I missed that option!
Didn't get the "Invalid data" message anymore recently. Still do get the "not authenticated" error every now and then, which resolves after a couple of minutes.
Thanks again for your work on this project!
