### ISSUE TITLE
Somfy Eolis 3D Wirefree RTS and IO sunscreen protection device

### ISSUE THREAD

**Issue by JeroenMeijer75** [AdyRock/com.somfy.tahoma#27]
Hi Adrian, I send you the question about the 'Eolis 3D Wirefree RTS and IO sunscreen protection device'. I'm just starting to use my Homey and I do not know what you mean bij 'Can you send me the Device log from the Configure App section'. Where do I find that? Thank in advance, Jeroen

**Comment by AdyRock** [comment]
Hi,
Thanks for reaching out to me. Welcome to Homey, I hope you are enjoying using it.

So, you can do this on either the Homey phone app or a desktop by connecting to the Athom developer site:

### Phone app method.
1. Open the Homey phone app,
2. Tap on the ... More button,
3. Tap on Apps,
4. Scroll down to the Somfy Tahoma & Connexoon app and tap on it,
5. Tap on the "Configure App" text,
6. Tap on the "Device Log" tab,
7. Tap on "Get Log" and wait a few seconds for the list to fill up,
8. Tap on the "Send Log" button.

### Desktop method
1. Open you web browser and go to https://tools.developer.homey.app/
2. Log in with your Homey username and password
3. Expand the "Tools" option,
4. Click on "App settings",
5. Optionally select a bigger phone screen in the Simulator drop down,
6. In the "Select an App" window, scroll down to the Somfy Tahoma & Connexoon app and click on it,
7. Click on the "Device Log" tab,
8. Tap on "Get Log" and wait a few seconds for the list to fill up,
9. Tap on the "Send Log" button.

The log contains the information shown in the list and is sent directly to me and lists all the details required to add your devices. There is no personal information in the log so i am not able to control any of your devices, etc.

If you could then let me know what names you assigned to the devices in you Somfy app so it is easier for me to locate the details.
