### ISSUE TITLE
Status horizontal awning (io)

### ISSUE THREAD

**Issue by JMHuls** [AdyRock/com.somfy.tahoma#28]
Last days I receive messages that my horizontal awning is still open. This evening I already got 10 messages (still counting) that Homey is going to close it. 5 min later agian, again, again...
Status is idle. In my flow I check if it is up or not. Looks like status is not comming through...
Can this be fixed? Would be great, cause Somfy hates it when their API is being used 😉

**Comment by AdyRock** [comment]
Is the awning actually closing via Homey?
Are you using the latest version of the app?
Could you send me the log from the App - Configure App screen.
You could try to disable the app for about 15 minutes and then enable it again. In theory, the latest version does a similar thing if it gets login failures.

**Comment by JMHuls** [comment]
Finally time to answer. Sorry that it took so long.

I had to restart Homey later that evening for another issue. That also killed the messages I kept receiving.

But still every evening I get 2 messages from Homey that it will close the awning. 

This flow starts the closing: https://homey.app/f/JvUTTD
This flow actually closes the awning: https://homey.app/f/QXfUTD

The 1st time I get the alert the awning closes, 5min later I receive a 2nd message. But when we close it manually (with remote) I only get 1 message.

Not a big issue anymore, but there seems to go something wrong... Hope this can help you for optimising the app.

It's IO protocol, via Connexoon. Using your latest test-app on Homey

**Comment by AdyRock** [comment]
In your flow you don't need to set both position to zero and state to up. Just one or the other will be fine, but not sure if that is causing a problem.

Once the command is sent it can take  a few seconds after the awning has finished moving before the state will report back as being up. While it is moving the state will still be reported as open as the position needs to be at 0 before the state changes to up.
