### ISSUE TITLE
Tahoma 2021

### ISSUE THREAD

**Issue by JukkaVdB** [AdyRock/com.somfy.tahoma#31]
Hi, is the app compatible with the new Tahoma 2021?

**Comment by AdyRock** [comment]
Hi, sorry for the late reply but I have only just seen the message so I'm not sure why I wasn't emailed when you wrote it.
I haven't heard any reports of it not working but to be honest I wasn't aware there was a new version. I will do some investigating to find out more.

**Comment by AdyRock** [comment]
If you mean the Tahoma Switch then the answer is yes, it is compatible.
