### ISSUE TITLE
Somfy TaHoma Switch

### ISSUE THREAD

**Issue by RobinSikking** [AdyRock/com.somfy.tahoma#32]
Hi. Is the application compatible with the new Somfy TaHoma Switch? If no, are there plans to support it in the future?

**Comment by AdyRock** [comment]
As far as I know it is as one or two users have mentioned it on the forum https://community.athom.com/t/somfy-tahoma-switch-new-device/48953/7?u=adrian_rockall

**Comment by RobinSikking** [comment]
Ah great. Didn't find that post. Thanks.
