### ISSUE TITLE
how to re-install io screen

### ISSUE THREAD

**Issue by mvduuren57** [AdyRock/com.somfy.tahoma#33]
With te replacement of my screen the somfy motor had to be re-installed in the my TaHoma environment. In that environment the sunscreen is recognized and works fine in the somfy app. Now I wanted to re-install the sunscreen to the Homey app.  I deleted in the Homey Somfy ToHoma& Connexoon app the former sunscreen. Then I tried to add a new Somfy device (select the 'horizontale buitenzomwering io') with the result ' no new devices detected'. (er zijn geen nieuwe apparaten gevonden). In the Homey Somfy TaHoma app i logged out and in again but same result. Do you have suggestions? thx in advance. Maarten

**Comment by AdyRock** [comment]
Can you open the More > Apps  > Somfy Tahoma and Connexoon > Configure App and select the Device Log tab. Then tap on Get Log and finally Send Log. If you then let me know the name of the sunscreen as it is shown in the Tahoma app and I will see it is mapped.

**Comment by mvduuren57** [comment]
Thx for the quick response. The name in the com.somfy.TaHoma is ‘ Zonnescherm. ‘ 

Regards Maarten

**Comment by AdyRock** [comment]
OK, it is mapped into the "Exterior blind (io)" or "Verticale buitenzonwering (io)" device.
If it still doesn't show up when adding then maybe it is still using the same id as before so is connected in Homey?

**Comment by mvduuren57** [comment]
Ah it works! I added the screen as a verticale buitenzonwering and detected in the Homey app again.

tanks!!

regards

Maarten
