### ISSUE TITLE
SLIM IO RECEIVER SCREEN + PLUG not recognized  in Homey

### ISSUE THREAD

**Issue by Beat540** [AdyRock/com.somfy.tahoma#35]
Hello, I am using a SLIM IO RECEIVER SCREEN + PLUG. The receiver controls vertical sun blinds. Unfortunately it is not recognized by the plug-in. Thanks for your help

**Comment by AdyRock** [comment]
I presume it shows up in the Tahoma software?
If it does can you send me the Device log from the Configure App screen so I can add it to the app.

**Comment by Beat540** [comment]
yes in Tahoma software, I have sent the device log

**Comment by Beat540** [comment]
it affects the blinds "3 Ost" and "2 Ost"

**Comment by AdyRock** [comment]
OK, I have added it in but it has a few twists so I want to do some more testing tomorrow when I am more awake.
I have added it under the "Roller shutter (io)" device as that is what it has most in common with.
I presume the device has no feedback to the actual position?

**Comment by Beat540** [comment]
No new devices were found in "Roller shutter (io)". These devices have feedback.

**Comment by AdyRock** [comment]
I have submitted the new version to the store:
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

**Comment by Beat540** [comment]
Hello Adrian
Thank you, the two blinds are integrated and work!
The feedback also works
Thank you very much
Beat


Von: Adrian Rockall ***@***.***>
Gesendet: Samstag, 28. August 2021 12:53
An: AdyRock/com.somfy.tahoma ***@***.***>
Cc: Beat Ineichen ***@***.***>; Author ***@***.***>
Betreff: Re: [AdyRock/com.somfy.tahoma] SLIM IO RECEIVER SCREEN + PLUG not recognized in Homey (#35)


I have submitted the new version to the store:
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

**Comment by AdyRock** [comment]
You're welcome.

**Comment by Beat540** [comment]
Hello Adrian
with the update 3.0.1 my blinds were deactivated. These previously worked with the test link.
Thanks for the help

Von: Adrian Rockall ***@***.***>
Gesendet: Samstag, 28. August 2021 12:53
An: AdyRock/com.somfy.tahoma ***@***.***>
Cc: Beat Ineichen ***@***.***>; Author ***@***.***>
Betreff: Re: [AdyRock/com.somfy.tahoma] SLIM IO RECEIVER SCREEN + PLUG not recognized in Homey (#35)


I have submitted the new version to the store:
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

**Comment by AdyRock** [comment]
In what way were they deactivated?
Is the app not logging in?
Could you enabled the Information log (blue tick) in the More > Apps > Somfy Tahoma & Connexoon > Configure App > Information log. If nothing shows up in the log after about a minute then restart the app and the go back to the log. Then could you send the log so I can see why it is not working.

**Comment by AdyRock** [comment]
Also, could you try to login via the repair option on one of the Somfy devices. Open the device, tap on the cog in the top right corner, tap on Maintenance, tap on Try to Repair. Then log in again from there.

**Comment by Beat540** [comment]
The 3 SLIM IO receivers show a! and the blinds are no longer accessible. i sent the log



Von: Adrian Rockall ***@***.***>
Gesendet: Mittwoch, 3. November 2021 18:07
An: AdyRock/com.somfy.tahoma ***@***.***>
Cc: Beat Ineichen ***@***.***>; Author ***@***.***>
Betreff: Re: [AdyRock/com.somfy.tahoma] SLIM IO RECEIVER SCREEN + PLUG not recognized in Homey (#35)


In what way were they deactivated?
Is the app not logging in?
Could you enabled the Information log (blue tick) in the More > Apps > Somfy Tahoma & Connexoon > Configure App > Information log. If nothing shows up in the log after about a minute then restart the app and the go back to the log. Then could you send the log so I can see why it is not working.

**Comment by Beat540** [comment]
The repair didn't change anything

Von: Adrian Rockall ***@***.***>
Gesendet: Mittwoch, 3. November 2021 18:13
An: AdyRock/com.somfy.tahoma ***@***.***>
Cc: Beat Ineichen ***@***.***>; Author ***@***.***>
Betreff: Re: [AdyRock/com.somfy.tahoma] SLIM IO RECEIVER SCREEN + PLUG not recognized in Homey (#35)


Also, could you try to login via the repair option on one of the Somfy devices. Open the device, tap on the cog in the top right corner, tap on Maintenance, tap on Try to Repair. Then log in again from there.

**Comment by AdyRock** [comment]
All reported issues should now be fixed in 3.0.2 in \test

**Comment by Beat540** [comment]
Super thank you! Should I deactivate the auto update for the app?

Von: Adrian Rockall ***@***.***>
Gesendet: Mittwoch, 3. November 2021 20:10
An: AdyRock/com.somfy.tahoma ***@***.***>
Cc: Beat Ineichen ***@***.***>; Author ***@***.***>
Betreff: Re: [AdyRock/com.somfy.tahoma] SLIM IO RECEIVER SCREEN + PLUG not recognized in Homey (#35)


All reported issues should now be fixed in 3.0.2 in \test

**Comment by AdyRock** [comment]
The version 3 update was a big change so I'm not surprised there were a few issues. But it helps having a few users that get the test versions as it digs them out before it gets rolled out to about 3500 regular users.
So I appreciate you might want to disable updates if it is critical to you but I do try to fix issues that arise as soon as I can.
