### ISSUE TITLE
“Set scene” card, does not actually set the scene

### ISSUE THREAD

**Issue by Nnk2** [AdyRock/com.somfy.tahoma#38]
The "Set scene" card on version of the Somfy TaHoma & Connexoon app finds all my scenes ok, but does not actually run/set them.

Setting the scene in Somfy's own iOS app works fine
Controlling individual (or all) Somfy devices from your app works fine too.

App version: 2.1.71
Homey FW: 7.1.1 
Homey HW: Pro (early 2019)
Somfy hardware: Somfy Connexoon RTS

**Comment by AdyRock** [comment]
I will check it out and let you know if I find anything or need more information.

**Comment by Nnk2** [comment]
Thank you again;

It could be something in the Somfy API itself though: IFTTT seems to be suffering the same issue ... (scenes not actually running when triggered externally on the somfy connexoon window RTS hub). No visible errors generated: connection seems to work, but the hub does nothing.

**Comment by AdyRock** [comment]
I have been playing with the scenes and as far as i can see they are working OK on my Tahoma.
Maybe contact Somfy support to see if there is a problem with you account.

**Comment by jeesnl** [comment]
I have the same issue here.

**Comment by AdyRock** [comment]
I'm not sure how to solve this one as it is working fine for me.
Is it all Scenarios that fail or just some?
