### ISSUE TITLE
Request: Please add card to turn on/off “Timer” switch

### ISSUE THREAD

**Issue by Nnk2** [AdyRock/com.somfy.tahoma#39]
Somfy iOS app has a "Timer" switch that controls timed automation on a Connexoon RTS hub.

Can you pls consider adding a card to turn that on or off in a Homey flow?

**Comment by AdyRock** [comment]
Could you send me the device log from the Homey app, More > Apps > Somfy Tahoma and Connexoon > Configure App > Device Log, get log then send log. If I can see a reference to the timer switch I will try to add it in.
I don't see anything like that in my Somfy Tahoma app.

**Comment by Nnk2** [comment]
Thank you, Adrian;

I have uploaded the log.

I have also posted a picture of the "Timer" switch I'd like to control below:  

![image](https://user-images.githubusercontent.com/17811489/132087045-075b93aa-4052-4eaf-94c0-2567b4f9b20c.jpeg)

It can be found in the "Timer" tab of the Somfy Window Connexoon RTS app for iOS.

Thank you for your help!

**Comment by AdyRock** [comment]
I have received the log thank you.
In my Tahoma app I don't see the same as you but I do have an Agenda that has an on / off switch so I wonder if that is the equivalent feature.
![Screenshot_20210904-090109_TaHoma](https://user-images.githubusercontent.com/38184396/132087840-a5bdbe78-7120-4fa9-a9a9-2ad1ac0875e8.jpg)

Looking a your log and my log, I can see that the hubs have commands to activate and deactivate the calendar so maybe that is the one to use.

I will try adding support for the hub device with those options available to see if it works.

**Comment by AdyRock** [comment]
I have published a new test version with support for the Tahoma schedule and hopefully the Connexoon Timer.
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/
You will need to add the Tahoma / Connexoon Hub device.

**Comment by Nnk2** [comment]
Hello Adrian,

Adding the "box" works, login (default, tahomalink) works too,but I get a
"Failed to send command" error on my Somfy Connexoon window RTS box if I run the card in a homey flow:

![image](https://user-images.githubusercontent.com/17811489/132730704-0c3b70ee-8ee9-46cc-b746-4d2e040cfca9.jpeg)

(I sent you the log just now)

**Comment by AdyRock** [comment]
Do the buttons work in the device tile?

I tested it with my Tahoma and it worked with that for the scheduling. 

Also could you enable the Information log and try the command again, then send the log?

**Comment by AdyRock** [comment]
I am only getting the errors through but I have just had a though, In the information log page is the Log Enabled tick blue?
Homey’s format is a grey tick for disabled and a blue tick for enabled. When the tick is grey the log only captures errors and when it is blue it captures everything.
With the tick blue, can you change the setting in the Somfy app and then send me the information log. In theory that should capture the format of the commands that the Somfy app sends to the box.

**Comment by Nnk2** [comment]
Done (= set information log to blue, clicked all tabs in the somfy app and enabled the schedule) and sent again … 
Buttons work fine ….

**Comment by Nnk2** [comment]
(Last log also includes the homey workflow).
Thank you for all your help/time! 
I really appreciate it!

**Comment by AdyRock** [comment]
Aha, I think I have found the problem. I will post a new test version (2.1.76) in a few minutes

**Comment by Nnk2** [comment]
Hello Adrian,

Version 2.1.76 did the trick: it works now 😃!

Thank you for adding this functionality!

**Comment by AdyRock** [comment]
That's good, thanks for letting me know. 
You are welcome.
