### ISSUE TITLE
Problem with velve

### ISSUE THREAD

**Issue by jkinformatik** [AdyRock/com.somfy.tahoma#40]
I have a problem with the heating velve. I get the message: failed to sent command

**Comment by AdyRock** [comment]
The valve is work in progress. As it was being difficult I purchased one which arrived on Sunday. Since then I have made progress and will hopefully publish a new test version tomorrow.

**Comment by AdyRock** [comment]
OK, there is a new test version in the store.

I recommend that you set the polling interval in the Homey app to 30 seconds to ensure that Homey stays in sync with the valve as best it can.
As you mentioned there is also the delay waiting for the valve to wake up. I have set the device warning to indicate the command is queued and that will be cleared when the valve wakes up and accepts the command and Homey has then polled for the next status update (hence setting the polling to 30 seconds).
Also the sensor capabilities will update at that point.

I was hoping to be able to set the Window Open mode from homey so a Homey contact sensor could be used to trigger it, but it seems that is only an internal state of the valve. So the next best thing is to change to Frost Protection mode when Homey detects an open window and then set it back to Auto or At Home mode when it is closed.

Let me know how you get on or if you think of anything else.

**Comment by jkinformatik** [comment]
I do not find a new version

**Comment by AdyRock** [comment]
You need to add test to the end of the URL.

**Comment by AdyRock** [comment]
I presume you found the test version https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

I will close the issue now but please get back to me if there any problems.
