### ISSUE TITLE
Support for Garagedoor RTS

### ISSUE THREAD

**Issue by Karlglad** [AdyRock/com.somfy.tahoma#41]
Is it possible to get my somfy dexxo optimo rts garage door added to the app?

**Comment by AdyRock** [comment]
Could you send me the device log from the app

**Comment by AdyRock** [comment]
This should be available in the new test version https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/
It will be found with the "Open / Close (RTS)" device in the pairing wizard.
