### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by jaboh** [AdyRock/com.somfy.tahoma#45]
My installation includes a Somfy Connexoon and three devices (sun/windscreens). For weeks after the initial setup these devices have worked flawlessly. Since then, any command has a huge delay, frequently resulting in a time-out. The Somfy standalone app (not related to Homey) continues to work correctly. All non-Somfy devices controlled by Homey work fine. 
I tried reinstalling the app and the devices, rebooting the Homey Pro, nothing helps.
Thanks for any suggestions.
Best regards- Jan

**Comment by AdyRock** [comment]
Could you send me the Information Log so I can see what is going on. To enable the log go to More > Apps > Somfy Tahoma and Connexoon > Configure Application > Information Log and then make sure the Enable Log has a blue tick.
Then control a device so you get the time delay / timeout. Once you have seen that, go back to the Information log and tap on Send Log button.
Hopefully I should be able to see why there is a delay in the communications.

**Comment by jaboh** [comment]
Thanks, Adrian.
Since I had opened the issue I had not tried anymore, relying on Somfy’s hub only.
It seems that one of the latest updates has fixed the problem: the screens operate normally without delay now.
I will close the issue and open a new one should the problem reoccur.
