### ISSUE TITLE
Not compatible with Homey Bridge

### ISSUE THREAD

**Issue by Ounihoun** [AdyRock/com.somfy.tahoma#51]
Hello, are there any plans to make the app compatible with Homey Bridge ?
Thanks

**Comment by AdyRock** [comment]
There is a test version that supports Homey (cloud), no bridge is required.
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

**Comment by Ounihoun** [comment]
Ok thank you
