### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by Loek69** [AdyRock/com.somfy.tahoma#52]
Hi, via Homey bridge, Somfy Tahoma device cannot be reached since a week.
Somfy works individually via Tahoma bridge.
Repairing device requires login to Somfy. Somehow account and password is not accepted (it is via tahoma bridge).
I know it is a test app of Somfy, still it worked for a long time.

**Comment by AdyRock** [comment]
It is a known problem with Homey (cloud) and Somfy. It is being discussed in the forum starting here https://community.homey.app/t/app-pro-somfy-tahoma-connexoon-v2-1-71-test-v3-0-6/35206/920?u=adrian_rockall

**Comment by AdyRock** [comment]
Has this issue been resolved for you?
The new version should be more robust with regards to this issue.

**Comment by Loek69** [comment]
Hi Adrian,
Thanks for your message. Been busy with otter things lately.
Yes, it seems more stable! Have had no more issues last weeks.
Thanks
Loek

Op ma 2 mei 2022 18:12 schreef Adrian Rockall ***@***.***>:
