### ISSUE TITLE
Ik probeer een Somfy Connexoon IO te koppelen aan mn homey pro. Maar hij krijgt hem niet gevonden. Kan iemand me vertellen hoe dit moet ?

### ISSUE THREAD

**Issue by wvervoort** [AdyRock/com.somfy.tahoma#53]

**Comment by AdyRock** [comment]
The app has to talk to the Somfy servers so you need to provide you Somfy log in details.
If you are using the latest test version you are prompted to do that when adding a device.
If you are using an earlier version the you need to open the More > Apps > Somfy Tahoma and Connexoon > Configure App to enter your credentials.

**Comment by wvervoort** [comment]
Hello Ady,

I found it. It works now. thanx for the input
