### ISSUE TITLE
Terrace heater with Somfy io controller

### ISSUE THREAD

**Issue by ReidarRoen** [AdyRock/com.somfy.tahoma#55]
Good afternoon.

I have a terrace heater (Solamagic) with Somfy controller. The heater is controlled by io remote and the Tahoma app on iPhone (via the Tahoma Switch), but I can't get it as a device in the Somfy TaHoma & Connexoon Homey app. I've sent a log if that could be at help.

Regards
Reidar Roen

**Comment by AdyRock** [comment]
I will have a look this evening.

**Comment by AdyRock** [comment]
Hopefully, this should be fully working now.
