### ISSUE TITLE
Howto connect Homey Connexoon

### ISSUE THREAD

**Issue by DonMart** [AdyRock/com.somfy.tahoma#56]
Hi Ady,
Last week I got 6 sunscreens with Somfy IO motors. 
I can operate these screens with the Somfy Terrace app. 
I have installed your plugin on my Homey. 
I have completed the configuration. 
The config page shows: login correct. 
but when I try to add the Connexoon to Homey. It only add ‘box’. 
some kind of a LED switch. 
I have send you the logs a few minutes ago. 
Do you know how to solve this problem?
Thanks in advance. 
Mart

**Comment by AdyRock** [comment]
I'm not sure what you mean exactly, but you don't need to add the Connexoon box to Homey to add the sunscreens; just add the sunscreens. 
I will check the logs to make sure your screens are supported when I get home.

**Comment by AdyRock** [comment]
Also, could you install the test version 3.0.18 as that has support for a lot more devices and better error handling.

**Comment by AdyRock** [comment]
So, to add your screens you need to select "Exterior blind (io)" and "Horizontal Awning (io)" when adding them to Homey.
Also it seems the your Connexoon box only supports switch the LED on / off and not dim so I need to fix that.

**Comment by DonMart** [comment]
I managed to add my exterior blinds and awning to Homey. And it is working!
I have tried to update the app to the latest version,  but I need some help with that please.
I found a youtube instruction video about adding a app with the CLI method.
This is what I tried:
Downloaded Node.js
Download latest version of your app from Github as Zip file.
Unzip
Start Node.js command prompt
'npm install -g homey'
'athom login'
with 'cd '  change to directory with the latest version of your app
 'athom app install'
It startes a lot of actions. At the end there are some error codes.
This is the end of the tutorial.
I rebooted my homey.
But when I go to 'settings', 'apps' 'Somfy Tahoma & Connexoon' 
it still says 'version 2.1.77'
I tried to delete the app. And re-install.
But it seems the same.
What did I do wrong?
Thanks for your reply

**Comment by AdyRock** [comment]
Sorry, all you need to do is install it from the Athom store but put \test on the end of the URL:
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

**Comment by DonMart** [comment]
;-) thanks
