### ISSUE TITLE
Couldn't connect with Tahoma Connexoon after update

### ISSUE THREAD

**Issue by HarryKroezen** [AdyRock/com.somfy.tahoma#59]
Good evening @AdyRock ,
Had an update of the Connexoon box from TaHoma today.
From that moment on, your Homey App can no longer log in.
Your app has version 2.1.77.

TaHoma has version 3.18.5.
With the TaHoma app I can log in with the same credentials.

What do you need to see what's going wrong?

Yours sincerely,
Harry Kroezen

**Comment by AdyRock** [comment]
Could you send the Information log from the Configure App screen so I can see the responses to the login requests.

**Comment by AdyRock** [comment]
Also, it might be worth trying the test version of the app.

**Comment by HarryKroezen** [comment]
Very strange, after trying to log in several times tonight, it suddenly works again.
It looks like it's working again, but I won't be able to see that properly until tomorrow morning, because it all has to respond to a light sensor, and it's too dark now, so no more changes can take place.

**Comment by AdyRock** [comment]
Fingers crossed it was just a temporary fault. The test version does have a lot of optimisations during login to try and make it more robust so it might be worth updating if the problem happens again.
