### ISSUE TITLE
Tilting venetian blinds

### ISSUE THREAD

**Issue by troeste** [AdyRock/com.somfy.tahoma#6]
Hello, I have several venetian blinds with Somfy IO motors that I want to control from Homey using the tahoma plugin. It works for basic operations for running the blinds up and down, but I miss the possibility to tilt the blinds using the Window Coverings Tilt Set capability.

Does the protocol used with Tahoma support tilting the blinds?

-Trygve

**Comment by AdyRock** [comment]
Sorry for the delay but I didn't get notified of your post for some reason.

Tahoma does support tilting for some blinds so hopefully it can be added.

If you are using my version of the app from the Homey Community Store (https://store.homey.community/app/com.somfy.tahoma) then there is a Device Log tab in the Somfy Tahoma - Configure App page.
Select the tab, 
Set the tick on Log Enabled and wait for the data to appear.
Then tap on Send Log. If that fails to send then copy the contents of the panel and paste it here. The log removes all sensitive data so there is no security risk in doing this.

The information will show me what features are available for you devices and allow me to add the necessary parsing and commands for them.

**Comment by AdyRock** [comment]
Sorry for the long delay getting back to you.
Has the new version in the Athom store solved this issue?

**Comment by troeste** [comment]
Hello Adrian,


I have not tested the new version yet since I had to disable the plugin after getting a mail from Somfy (see below). Have you made some changes to the software to make it acceptable for Somfy?


-Trygve


Dear customer,

In an ongoing effort to provide the best services to our users, we monitor the traffic generated by our applications and Smart Home boxes (TaHoma and Connexoon). It appears that you are using a third-party solution, either developed by yourself or provided by an external entity (developer or community of developers not working for Somfy). Such developments are made without our willingness and, sometimes, do not respect our usage guidelines.

We are contacting you today to update the way your script or your application behaves with our API as it is overconsuming our backend resources for your own installation. To do so, please contact the provider of your solution or update your code by October 31st.

We are asking all third-party scripts or application to reduce their polling activity on our API. In particular, the GET /setup endpoint is meant to be used once and only once by end-user session and not to regularly refresh the devices data.

As we do not want every TaHoma and Connexoon users be impacted by the overuse of some individuals, we will react in the coming months and set up rate limiters and automated bans if such changes are not applied.

Thank you for your understanding



________________________________
Fra: Adrian Rockall <notifications@github.com>
Sendt: tirsdag 19. januar 2021 13:18
Til: AdyRock/com.somfy.tahoma
Kopi: Trygve Røste; Author
Emne: Re: [AdyRock/com.somfy.tahoma] Tilting venetian blinds (#6)


Sorry for the long delay getting back to you.
Has the new version in the Athom store solved this issue?

**Comment by AdyRock** [comment]
Yes, the latest version is complying with Somfy's new rules. The developers of Home Assistant and myself had discussions with them and they agreed the terms under which we could use their API.
The new version is complete rewrite of the methods used to get status updates and it has a minimum polling time of 30 seconds.

P.S. This new version is also in the Athom store as I have now been officially hand the app.

**Comment by AdyRock** [comment]
I presume everything is OK with the new app so I will close this off now. Please get back to me if you need any more help.
