### ISSUE TITLE
Problem Dexxo Smart - Connexoon - Homey

### ISSUE THREAD

**Issue by joakimroer** [AdyRock/com.somfy.tahoma#60]
Hi
I've got a new Dexxo Smart 800 and I'm using Connexoon hub.
Problem is when I'm using Keygo or Smoove to control the garage door, it update status in Homey too slow.
I nerd to controll my garage light the garage door is open/closed.
When I use Homey to control it updates quick.

Second I missing some flow card in Homey.
I can't connect Dexxo via the normal Garage door device only the "Partial" version.

BR
Joakim Roer

**Comment by AdyRock** [comment]
Unfortunately there is nothing I can do about the speed as Somfy limit the polling to 30 seconds. I'm allowed to boost it to 3 seconds while a command is in progress but if I make it shorter than 30 seconds permanently, Somfy would block your account. 
As for the door connection, could you send me the device log from the Configure App screen so I can see the capabilities. If it supports more then I can add them.

**Comment by joakimroer** [comment]
Thanks for answer.
I case, I can use an door sensor.

I clicked send log and it said log is sent to developer.
Did you get it?
Or i need to copy/paste it to email?



Mvh Joakim Roer
41475363



-------- Opprinnelig melding --------
Fra: Adrian Rockall ***@***.***>
Dato: 04.04.2022 14:09 (GMT+01:00)
Til: "AdyRock/com.somfy.tahoma" ***@***.***>
Ko: joakimroer ***@***.***>, Author ***@***.***>
Emne: Re: [AdyRock/com.somfy.tahoma] Problem Dexxo Smart - Connexoon - Homey (Issue #60)


Unfortunately there is nothing I can do about the speed as Somfy limit the polling to 30 seconds. I'm allowed to boost it to 3 seconds while a command is in progress but if I make it shorter than 30 seconds permanently, Somfy would block your account.
As for the door connection, could you send me the device log from the Configure App screen so I can see the capabilities. If it supports more then I can add them.

**Comment by AdyRock** [comment]
I have the log and will look at it ASAP.

**Comment by joakimroer** [comment]
Thanks.
Not so hurry for me just wanted to know if there is something that is fixable.



Mvh Joakim Roer
41475363



-------- Opprinnelig melding --------
Fra: Adrian Rockall ***@***.***>
Dato: 04.04.2022 14:39 (GMT+01:00)
Til: "AdyRock/com.somfy.tahoma" ***@***.***>
Ko: joakimroer ***@***.***>, Author ***@***.***>
Emne: Re: [AdyRock/com.somfy.tahoma] Problem Dexxo Smart - Connexoon - Homey (Issue #60)


I have the log and will look at it ASAP.

**Comment by AdyRock** [comment]
Which flow card are you missing?
The partial door should have the Open / Close and My positions as it can't be set to 'any' position.

**Comment by joakimroer** [comment]
I want the "THEN-CARD" set set to %.
But that is maybe not possible in the partial?



Mvh Joakim Roer
41475363



-------- Opprinnelig melding --------
Fra: Adrian Rockall ***@***.***>
Dato: 04.04.2022 14:47 (GMT+01:00)
Til: "AdyRock/com.somfy.tahoma" ***@***.***>
Ko: joakimroer ***@***.***>, Author ***@***.***>
Emne: Re: [AdyRock/com.somfy.tahoma] Problem Dexxo Smart - Connexoon - Homey (Issue #60)


Which flow card are you missing?
The partial door should have the Open / Close and My positions as it can't be set to 'any' position.

**Comment by AdyRock** [comment]
Unfortunately, there isn't a command to do that with that device.

**Comment by joakimroer** [comment]
Oh, so the Dexxo Smart 800 doesn't support % status?



Mvh Joakim Roer
41475363



-------- Opprinnelig melding --------
Fra: Adrian Rockall ***@***.***>
Dato: 04.04.2022 14:54 (GMT+01:00)
Til: "AdyRock/com.somfy.tahoma" ***@***.***>
Ko: joakimroer ***@***.***>, Author ***@***.***>
Emne: Re: [AdyRock/com.somfy.tahoma] Problem Dexxo Smart - Connexoon - Homey (Issue #60)


Unfortunately, there isn't a command to do that with that device.

**Comment by AdyRock** [comment]
Correct, It only has commands for Open, Close and Partial (the My button in the Homey App). None of those command take any parameters, so no way to set the %, and sending Open will open it all the way, etc.
You can presumably set the Partial position in the Somfy app or via the Remote so it allows you to walk in / out? If so you can select that position via the My button / flow action in Homey.

**Comment by joakimroer** [comment]
Can you see if Somfy Dexxo Smart 1000 have more options? Or if it has the same as Dexxo Smart 800.



Mvh Joakim Roer
41475363



-------- Opprinnelig melding --------
Fra: Adrian Rockall ***@***.***>
Dato: 04.04.2022 15:06 (GMT+01:00)
Til: "AdyRock/com.somfy.tahoma" ***@***.***>
Ko: joakimroer ***@***.***>, Author ***@***.***>
Emne: Re: [AdyRock/com.somfy.tahoma] Problem Dexxo Smart - Connexoon - Homey (Issue #60)


Correct, It only has commands for Open, Close and Partial (the My button in the Homey App). None of those command take any parameters, so no way to set the %, and sending Open will open it all the way, etc.
You can presumably set the Partial position in the Somfy app or via the Remote so it allows you to walk in / out? If so you can select that position via the My button / flow action in Homey.

**Comment by AdyRock** [comment]
Unfortunately I can't find out the difference between them.

**Comment by joakimroer** [comment]
133a7c7d-2c91-46d2-aab7-dfeb9b659f31

Error.



Mvh Joakim Roer
41475363



-------- Opprinnelig melding --------
Fra: Adrian Rockall ***@***.***>
Dato: 02.05.2022 18:05 (GMT+01:00)
Til: "AdyRock/com.somfy.tahoma" ***@***.***>
Ko: joakimroer ***@***.***>, Author ***@***.***>
Emne: Re: [AdyRock/com.somfy.tahoma] Problem Dexxo Smart - Connexoon - Homey (Issue #60)


Closed #60<https://github.com/AdyRock/com.somfy.tahoma/issues/60>.

**Comment by AdyRock** [comment]
I have replied directly to your log report.
