### ISSUE TITLE
Lux sensor no longer working

### ISSUE THREAD

**Issue by FPPMvB** [AdyRock/com.somfy.tahoma#62]
After the update from today 02-05-2022 the light sensor are no longer working correctly

**Comment by AdyRock** [comment]
Could you give me some more information so I can try to diagnose the problem?
Do you have a Homey Pro? If so could you enabled the Information log (blue tick) and then send the log to me after a few minutes.
Is the light sensor getting any updates?
I have also noticed that my Homey had issues logging in to my Somfy account this afternoon, but it is working again now, so maybe Somfy had a general server issue for a while.

**Comment by FPPMvB** [comment]
Hi, I have restarted the app and it seems to be working now. However i see the following remark which is new to me



Perhaps this will give you some more info

Met vriendelijke Groeten,
Frank van Berkel

**Comment by AdyRock** [comment]
I'm not seeing the remark!

**Comment by FPPMvB** [comment]
It says status sensor defect, and it shows this message on 3 different sensors

Met vriendelijke Groeten,
Frank van Berkel

**Comment by FPPMvB** [comment]
It seems i have to re-start the app everytime before I get the correct information in from the sensors…
It doesn’t seem to update the values automaticly anymore…..

Met vriendelijke Groeten,
Frank van Berkel

**Comment by AdyRock** [comment]
> It says status sensor defect, and it shows this message on 3 different sensors

 This is a new status report, but I am guessing the information is empty ( - )?
If there is any error (such as a low battery) then the - will be replaced with the text of the error reported by the device.

> It seems i have to re-start the app everytime before I get the correct information in from the sensors…

Another user has reported the same phenomena and I believe, by looking at the log they sent, in their case it is because the polling interval is too long. The new version uses the preferred Somfy OAuth login method which has a shorter timeout on the events.

Could you try reducing the polling interval to 30 or 60 seconds to see if that solves the problem?

**Comment by FPPMvB** [comment]
It was 300 s now reduced to 45 s
Logged in again but still no result
I have send the log file a minute ago

**Comment by AdyRock** [comment]
I think you sent a device log but to see if there are any errors I need the Information log. Could you send that one to me please.
FYI: the other user with a similar problem reduced the interval from 600 to 60 and that fixed it for him so I think reducing it to 45 should fix for you. Hopefully the Information log will give me an idea of what is going wrong.

**Comment by FPPMvB** [comment]
8cce4796-367b-4f2a-bfbd-e60c6b6cb14e

Like this?

**Comment by AdyRock** [comment]
That shows me a little bit that suggests it's working but the Information log is on the tab next to the device log.
If you make sure the log is enabled (blue tick) then it will log each call to the API. Once it has logged for a few minutes, tap on the send log button.

**Comment by FPPMvB** [comment]
Information log send.
I currently made a flow which re-starts the app every 5 min to retrieve the correct lux data from Tahoma, as a work around for the moment

**Comment by AdyRock** [comment]
As far as I can see the app is working fine. It is receiving regular events with the lux value from the light sensor. 
{
    "time": "[2022-05-03T17:17:12](calendar:T7:2022-05-03T17:17:12).748Z",
    "source": "Fetching Events",
    "data": {
      "message": "Complete",
      "stack": [
        {
          "timestamp": [1651598229666](tel:1651598229666),
          "setupOID": "17202c7d-5d46-4dbc-a513-5665edf65808",
          "deviceURL": "io://[1209-3246-0223](tel:1209-3246-0223)/[13863970](tel:13863970)",
          "deviceStates": [
            {
              "name": "core:LuminanceState",
              "type": 2,
              "value": "5430.0"
            }
          ],
          "name": "DeviceStateChangedEvent"
        }
      ]
    }
  },

**Comment by FPPMvB** [comment]
I'm afraid thats because I re-start the app every 5 minutes.
The app itselve doesn't show up to date information every 60 s. But only after 5 min. (After the re-start)
If I stop that flow, i won't get any updates. I will send a new information log in 30 min

**Comment by AdyRock** [comment]
The latest one looks OK.
If you look through the log you can see the messages like the one above and the values are changing. They might not change every 60 seconds as Somfy only sends updates when the lux value changes by some amount.

**Comment by AdyRock** [comment]
Hopefully this is all working OK for you now, but let me know if you are still having problems with the app.

**Comment by FPPMvB** [comment]
Sorry for the somewhat late reply.
But yes all seems to be working fine👍🏻
Thxzz for your support
