### ISSUE TITLE
Temperature and solar sensors not working after update

### ISSUE THREAD

**Issue by Robw82** [AdyRock/com.somfy.tahoma#63]
Since the somfy connexoon app was updated this afternoon, the status of temp and solar are not updated anymore.
![Screenshot_20220502-222920_Homey](https://user-images.githubusercontent.com/104798201/166331593-4bdd7f06-9073-41bd-8605-2db7ff6dc845.jpg)
![Screenshot_20220502-222902_Homey](https://user-images.githubusercontent.com/104798201/166331598-5d8b04e8-36a2-435e-89e8-805dd8975218.jpg)
![Screenshot_20220502-222845_Homey](https://user-images.githubusercontent.com/104798201/166331599-3a7d6ae8-8671-4bd9-bb8c-0d79aa6f3906.jpg)

**Comment by Robw82** [comment]
Diagnostic report

bd867331-1807-4e64-a42c-ced8b2286b8c

**Comment by AdyRock** [comment]
Thanks for the report. I think you might have the polling interval set too long for the new connection method. This is just a guess from the limited information that I get from those reports. The new version uses the Somfy preferred OAuth2 login method and I believe the timeout between registering events and requesting the status is lower.

Could you set the Polling Interval to 30 or 60 seconds and see if that fixes the problem?

**Comment by Robw82** [comment]
Everything seems to be working again. Thanks again!

Regards,
Rob

Op di 3 mei 2022 08:21 schreef Rob Wintermans ***@***.***>:

**Comment by Robw82** [comment]
Hi Adrian,

Thanks for the fast reply!
I have set it to 60 (down from 600). I will let you know tonight 😊

Kind regards,
Rob

Op di 3 mei 2022 07:58 schreef Adrian Rockall ***@***.***>:
