### ISSUE TITLE
Logins fail 

### ISSUE THREAD

**Issue by jaboh** [AdyRock/com.somfy.tahoma#64]
My sun screens are no longer accessible. Somfy app works fine.
All Somfy login attempts with Homey fail.

**Comment by AdyRock** [comment]
Did you send me a log about an hour ago?

**Comment by jaboh** [comment]
Hi Adrian,

Yes I did.

Jan

**Comment by AdyRock** [comment]
Ok, the log is showing timeouts, which suggests Homey can't connect to the server. This could be an issue on the Somfy server, router or Homey. 
You could try restarting your router and / or Homey to see if that solves the problem.

**Comment by jaboh** [comment]
The logins only fail when done via the Homey app. Same credentials used in Tahoma/Connexoon app just work every time without delay.
Restarted Homey app, Homey itself, iphone, nothing seems to help.
Up to the May 3rd my screens were retracted by a flow at sunset, which is very convenient. It has worked flawlessly for a long time. But I had a similar issue about a year ago. The problem disappeared after a week or so.
Thanks for your work and help, when it works it is so useful.

Kind regards- Jan

**Comment by AdyRock** [comment]
Does Homey connect to the internet via a proxy server?
There error returned is not so much a login failure as in the credentials are not accepted, but Homey is just failing to reach the Somfy server so the requests are timing out.

Could you ensure the App Information log is enabled (blue tick) and then restart the app. After allowing a few minutes for the app to start up and initialise everything, can you send the Information log again. I just want to see if it fails from the start or if there is something that is causing an issue part way through the start up.

**Comment by jaboh** [comment]
d725638d-d090-488d-b6af-060a5edad9ee

**Comment by AdyRock** [comment]
I have got the Homey Diagnostic log but it is very limited on information as it only shows errors and not what leads up to the error. So, could you go to https://tools.developer.homey.app/tools/app-settings, select the Tahoma & Connexoon app, open the Information Tab and make sure the Log Enable has a blue tick.
Then restart the app. To send the log go back to the Information Tab and then click on Send Log.

**Comment by jaboh** [comment]
Strange, the blue tick was on all the time.
Then I got a message about my homey backups failing. The pro was not connected to the cloud, so it was a generic problem.
The combination of rebooting the router and power cycling the pro got the connection restored.
Thanks so much for your patience, sorry for not searching for a more generic cause. Learned something today…
Best regards 
Jan

**Comment by AdyRock** [comment]
No problem. It's not always easy to see were a problems is so you have to start somewhere and that is normally with the visible sign of failure.
