### ISSUE TITLE
Support for io:SwitchMicroModuleSomfyIOComponent

### ISSUE THREAD

**Issue by sundeqvist** [AdyRock/com.somfy.tahoma#66]
Hey! Great work on this app, everything works flawlessly so far. 

I've just moved into a new place where a Somfy setup was preinstalled and I've been trying to reverse engineer why this app is not picking up the power outlets. As I didn't get to install these myself I'm not 100% sure what is what, but looking at the device log I can tell their `controllableName` is set to `io:SwitchMicroModuleSomfyIOComponent`. I do not see any hits when searching for that in this repository so it looks like they're not supported. Is this the case, and is there a reason for it? Alternatively, am I just completely wrong in that assumption? 😄 

I just sent over a device log to you according to the docs in https://github.com/AdyRock/com.somfy.tahoma/issues/1 -- hopefully that contains all that is needed.

If you're strapped for time I can definitely try helping out with the implementation if you can point me to a contribution guide.

Thanks!

**Comment by AdyRock** [comment]
No problem. I will add then in today.

**Comment by AdyRock** [comment]
Are actual plug sockets or are they modules added to sockets?
Would it be acceptable to add then to an existing device, such as the "Switch (RTS & io)"?

**Comment by sundeqvist** [comment]
They are modules added to sockets, so "Switch (RTS & io)" sounds like a good fit.

**Comment by Tomskogsberg** [comment]
I have the exact same problem. You are the MAN @AdyRock ! 👏

**Comment by AdyRock** [comment]
I have added it as a new device so it appears in the wall plug section
![image](https://user-images.githubusercontent.com/38184396/171426065-8f0ce2c2-eab8-4f3b-9fc7-75a4eec731fe.png)

**Comment by AdyRock** [comment]
It is now in the test in the store
https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/

**Comment by sundeqvist** [comment]
It works like a charm @AdyRock 👑 

Many thanks for the support!
