### ISSUE TITLE
Misal Ecowitt and homey

### ISSUE THREAD

**Issue by Alexuskoi** [AdyRock/com.somfy.tahoma#67]
Hi I can't add my gateway to Misal and ecowitt app. My ecowitt (gw1100) is on the same router as my Homey pro but the homey cannot detect my gateway. What could be the cause of this? regards Alexuskoi

**Comment by AdyRock** [comment]
Have you configured the gateway as shown in the forum https://community.homey.app/t/app-pro-misol-and-ecowitt-version-0-1-10-and-test-0-1-11/47076?u=adrian_rockall

**Comment by Alexuskoi** [comment]
> Have you configured the gateway as shown in the forum https://community.homey.app/t/app-pro-misol-and-ecowitt-version-0-1-10-and-test-0-1-11/47076?u=adrian_rockall

thanks it works 👍
