### ISSUE TITLE
my somfy devices will not appear in homey

### ISSUE THREAD

**Issue by Arne1313** [AdyRock/com.somfy.tahoma#68]
Hi,

When i install your app it has connection to somfy but it does not see any devices.
I says every time no new devices but i'm logged in.
Already de-installed and installed, restarted app etc but nothing worked.
Maybe u have a tiup/solution?

thanks in advance

**Comment by AdyRock** [comment]
Could you send the Device log from the Configure App screen?
Maybe your devices are not yet supported in which case that information will help me add them to the app.

**Comment by Arne1313** [comment]
Hi,

I just send the log from the app in homey.
I hope that is enough :-)

regards
Arne

**Comment by AdyRock** [comment]
I have received a few logs today so I am going by the latest one as I think that must be yours based on the timing.
If so then the blinds in the log should be added to Homey using the "Exterior blind (io)" or "Verticale buitenzonwering (io)" option, and the lights via the "Switch (RTS & io)" or "Schakelaar (RTS & io)" option.

**Comment by Arne1313** [comment]
Hi Adrian,

The light is working only my 6 shutters are not.
I tried all different options in the app, even velux and garage opener ones
but every time i get "no new devices have been found"
Unfortunately :-(


[image: image.png]

[image: image.png]

**Comment by AdyRock** [comment]
This is what I see when I run your log through my simulator:
![image](https://user-images.githubusercontent.com/38184396/174657257-a692a84d-9bdf-44cf-804d-d416cf95efd6.png)

So that is by selecting the "Exterior blind (io)" option:
![image](https://user-images.githubusercontent.com/38184396/174657379-5e762417-9d50-4651-9715-6f4d447d02e6.png)

**Comment by Arne1313** [comment]
Hi Adrian,

Sorry i feel like a fool :-(
Did not see the sunshade part, just looked at the blinds part.
So when I chose the sunshine exterior blind it just worked :-)

Thanks for your patience

warm regards,
Arne

**Comment by AdyRock** [comment]
No problem, the app supports a lot of devices and manufacturers tend to mix up the motors, so it's not always easy to find the right option.
