### ISSUE TITLE
Impossible to add io devices

### ISSUE THREAD

**Issue by blisstbg** [AdyRock/com.somfy.tahoma#69]
Hello Adrian,

I am contacting you as I had installed the Somfy Tahoma and Connexoon application. 
I have managed to add my Connexoon box, that I use to monitor 7 exterior blinds and an Atlantic heating and cooling device. 
First thing that seems strange to me is that the box appears only as a led device. 
Then, if I try to add on the Homey app my exterior blinds, it is simply impossible. It just says that there are no device to add. 
I have got the log and then sent it. Not sure if anything will happen then. 
Would you have any idea on why I can not add my Somfy io devices onto the app?

Many thanks,
blisstbg

**Comment by AdyRock** [comment]
I have a log this morning which I hope is yours.
Try Adding the following devices: 
"Roller shutter with quiet mode (io)",
"Atlantic Heating And Cooling System",
"Temperature Sensor (io)",
"Atlantic Water Boiler",
"Energy Meter"

Your "Conso. ECS" is not currently supported so I will add it to the next version.

**Comment by blisstbg** [comment]
Good evening Andy,

I have just one word: Waow…

You are a master! Thank you so much, you helped a lot!

I wish you a very nice evening.

Respectfully,
Guillaume


Le 9 juil. 2022 à 21:05, Adrian Rockall ***@***.***> a écrit :

﻿

I have a log this morning which I hope is yours.
Try Adding the following devices:
"Roller shutter with quiet mode (io)",
"Atlantic Heating And Cooling System",
"Temperature Sensor (io)",
"Atlantic Water Boiler",
"Energy Meter"

Your "Conso. ECS" is not currently supported so I will add it to the next version.

**Comment by blisstbg** [comment]
Good morning Adrian,

Within my installation and through the Somfy and Tahoma App, I have 3 temperature sensors: one for the outside and two for the inside zones.
I have noticed that they all display the same value and when I do a maintenance/repair on one of the 3 sensors, the 3 sensors then display the correct values. But only for a short time…

Would you have any idea on how to fix this?

Many thanks,
Guillaume

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Guillaume Vetter ***@***.***>
Envoyé : Saturday, July 9, 2022 9:37:53 PM
À : AdyRock/com.somfy.tahoma ***@***.***>
Objet : Re: [AdyRock/com.somfy.tahoma] Impossible to add io devices (Issue #69)

Good evening Andy,

I have just one word: Waow…

You are a master! Thank you so much, you helped a lot!

I wish you a very nice evening.

Respectfully,
Guillaume


Le 9 juil. 2022 à 21:05, Adrian Rockall ***@***.***> a écrit :

﻿

I have a log this morning which I hope is yours.
Try Adding the following devices:
"Roller shutter with quiet mode (io)",
"Atlantic Heating And Cooling System",
"Temperature Sensor (io)",
"Atlantic Water Boiler",
"Energy Meter"

Your "Conso. ECS" is not currently supported so I will add it to the next version.

**Comment by AdyRock** [comment]
Could you make sure the Information log is enabled (blue tick), wait for the devices to update to the same value and then send me log?

**Comment by blisstbg** [comment]
Hello Adrian,

Thank you for your feedback.

The information log is all clear, whereas the device log shows datas.
Is this normal?
The 3 devices always shows the same value.

Best regards,
Guillaume



Le 3 août 2022 à 08:30, Adrian Rockall ***@***.***> a écrit :

﻿

Could you make sure the Information log is enabled (blue tick), wait for the devices to update to the same value and then send me log?

**Comment by AdyRock** [comment]
Does the information log page have a blue tick. The style of the tick can look like it is enabled when it's not, so has caught out some users. 
When it's enabled you should see massages coming in as it's polling.

**Comment by blisstbg** [comment]
Now I see what you mean. 
You were correct, the log was not enabled. 

I just sent it to you. 

Thank you, again.

**Comment by blisstbg** [comment]
Hello Adrian,

Just wanted to know if you have any feedbach on that.
Thank you,
Guillaume

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Guillaume Vetter ***@***.***>
Envoyé : Thursday, August 4, 2022 2:49:47 PM
À : AdyRock/com.somfy.tahoma ***@***.***>
Objet : Re: [AdyRock/com.somfy.tahoma] Impossible to add io devices (Issue #69)

Now I see what you mean.
You were correct, the log was not enabled.

I just sent it to you.

Thank you, again.

**Comment by AdyRock** [comment]
I'm really sorry for the late response, I have no idea how I missed your reply. 

From the log I am only seeing temperature reports from one device. Each device is identified by the "deviceURL". I'm intrigued by the different source information though, but as I'm out at the moment I can't check that. 
However, all the reported temperatures are the same.

**Comment by blisstbg** [comment]
No problem.
Let me know if you need anything else from me.
Best regards,
Guillaume.

Envoyé de mon iPhone

Le 29 août 2022 à 13:45, Adrian Rockall ***@***.***> a écrit :

﻿

I'm really sorry for the late response, I have no idea how I missed your reply.

From the log I am only seeing temperature reports from one device. Each device is identified by the "deviceURL". I'm intrigued by the different source information though, but as I'm out at the moment I can't check that.
However, all the reported temperatures are the same.

**Comment by blisstbg** [comment]
Let me just add (not sure if I already told you and if it is of interest) that I manage to have the 3 sensors showing their proper temperature when I do a repair of one of the 3 sensors.
Cheers,
Guillaume

**Comment by AdyRock** [comment]
At the moment my suspicion is with the # in the URL. I have a bit of code that process the URL up to the # to cope with sub URLs that appear on some devices. In the log you sent before, all the URLs end in # 9, but I wonder if the other devices have the same URL but with a different # number on the end. That could explain why they end up with the same value.
Maybe you could enable the log for longer and watch for the lines with  "deviceURL": "io://0836-3654-3982/11961543# and see if different numbers appear. If you see that then send me the log.

**Comment by AdyRock** [comment]
I have published a new test version that changes the way it handles the # in the URL. Can you try that to see if it solves the problem?

**Comment by blisstbg** [comment]
Thank you Adrian, I will.
How should I proceed? Should I desinstall first the version I have? Will I loose all the flows I have?


Envoyé de mon iPhone

Le 31 août 2022 à 00:13, Adrian Rockall ***@***.***> a écrit :

﻿

I have published a new test version that changes the way it handles the # in the URL. Can you try that to see if it solves the problem?

**Comment by AdyRock** [comment]
No, install over the top of the current version and then your flows will remain intact.

**Comment by blisstbg** [comment]
I have updated the app. So far it looks promising, the 3 sensors are reading 3 different temperatures. I will confirm it is definitely solved shortly.
Thanks a lot!

Envoyé de mon iPhone

Le 31 août 2022 à 10:58, Adrian Rockall ***@***.***> a écrit :

﻿

No, install over the top of the current version and then your flows will remain intact.

**Comment by blisstbg** [comment]
Too bad. Actually after a couple of new closures and openings of the App, the 3 sensors were again showing the same temperature. I did a repair and now they read differently.

Envoyé de mon iPhone

Le 31 août 2022 à 12:55, Guillaume Vetter ***@***.***> a écrit :

﻿ I have updated the app. So far it looks promising, the 3 sensors are reading 3 different temperatures. I will confirm it is definitely solved shortly.
Thanks a lot!

Envoyé de mon iPhone

Le 31 août 2022 à 10:58, Adrian Rockall ***@***.***> a écrit :

﻿

No, install over the top of the current version and then your flows will remain intact.

**Comment by AdyRock** [comment]
Fingers crossed 🤞 🙂

**Comment by blisstbg** [comment]
No, they all read the same again…



Le 31 août 2022 à 13:21, Adrian Rockall ***@***.***> a écrit :

﻿

Fingers crossed 🤞 🙂

**Comment by AdyRock** [comment]
Could you send the Device log and the information log again please. The new version has a bit more information to help me track down the # issue.

**Comment by AdyRock** [comment]
If it was you that just sent me the logs, then you are still on the old version Tahoma device log(655678716 : 3.0.35). can you update to the test version https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/ and try again.

**Comment by blisstbg** [comment]
﻿Sorry.
Strange, I did not see the one you sent earlier when I went on the app page.

I installed the correct version and rebooted homey. It looks promising so far.
I will keep you posted.

Thank you again.


Le 31 août 2022 à 16:38, Adrian Rockall ***@***.***> a écrit :

﻿

If it was you that just sent me the logs, then you are still on the old version Tahoma device log(655678716 : 3.0.35). can you update to the test version https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/ and try again.

**Comment by blisstbg** [comment]
Hello Adrian,

I had a look at the log. When I started to see it, the first of the 3 temperature sensors was showing #11. Then there has been like a refresh of the screen. I scrolled down and see another sensors showing #8 and the last one also #8. And when I saw again the first one that was previously #11 he was also showing #11.

Guillaume


Le 29 août 2022 à 19:42, Adrian Rockall ***@***.***> a écrit :

﻿

At the moment my suspicion is with the # in the URL. I have a bit of code that process the URL up to the # to cope with sub URLs that appear on some devices. In the log you sent before, all the URLs end in #9<https://github.com/AdyRock/com.somfy.tahoma/issues/9>, but I wonder if the other devices have the same URL but with a different # number on the end. That could explain why they end up with the same value.
Maybe you could enable the log for longer and watch for the lines with "deviceURL": "io://0836-3654-3982/11961543# and see if different numbers appear. If you see that then send me the log.

**Comment by blisstbg** [comment]
Hello Adrian,
So far so good. The temperature sensors are working properly.

Many thanks for everything that you did.
Guillaume


Le 31 août 2022 à 16:48, Guillaume Vetter ***@***.***> a écrit :

﻿
﻿Sorry.
Strange, I did not see the one you sent earlier when I went on the app page.

I installed the correct version and rebooted homey. It looks promising so far.
I will keep you posted.

Thank you again.


Le 31 août 2022 à 16:38, Adrian Rockall ***@***.***> a écrit :

﻿

If it was you that just sent me the logs, then you are still on the old version Tahoma device log(655678716 : 3.0.35). can you update to the test version https://homey.app/en-gb/app/com.somfy.tahoma/Somfy-TaHoma-&amp;-Connexoon/test/ and try again.

**Comment by blisstbg** [comment]
I just sent you those 2 logs.



Le 31 août 2022 à 15:41, Adrian Rockall ***@***.***> a écrit :

﻿

Could you send the Device log and the information log again please. The new version has a bit more information to help me track down the # issue.

**Comment by AdyRock** [comment]
I am just looking through old issues and noticed this didn't show as being resolved, so could you let me know if you still need help?

**Comment by blisstbg** [comment]
Hello Adam,
It is working properly, thanks for checking.
Guillaume


Le 24 juil. 2024 à 06:32, Adrian Rockall ***@***.***> a écrit :

﻿

I am just looking through old issues and noticed this didn't show as being resolved, so could you let me know if you still need help?
