### ISSUE TITLE
Somfy/Tahoma app does not Connect anymore

### ISSUE THREAD

**Issue by josgroenewegen** [AdyRock/com.somfy.tahoma#71]
Dear Andy,

Atom Rolf me to report this problem to you.

sinds A couple of days I can’t connect anymore via the homey app. I tried to reinstalling the app and reboot homey bridge, but it doesn’t work

I get code 401 while connecting to Somfy 

can you help me out please?

kind regards

jos

**Comment by AdyRock** [comment]
The code 401 means the communications with Somfy is unauthorised.
Can you still log into your Somfy account through their website?
Could you try the repair option located on the right click menu in the Homey web app and follow the instruction to reauthenticate?

**Comment by josgroenewegen** [comment]
Yes I tried this option to repair, but that didn't work. Now I tried to reinstall the app but when I want to add a device I get the 401 code.

(Devices are lost due to reinstalling the app)

I checked login in via website this works also the Somfy app work correct 

Is there something else I can try?

Thanks in advance 

Jos

**Comment by AdyRock** [comment]
Unfortunately, I have no way to see what is happen with Homey (cloud), as Athom haven't provided any diagnostics methods.

What version of the app are you using?

I did see this problem when Homey was first introduced and that was due to the IP sharing, so Somfy detected many login attempts from the same IP (one for each user).

**Comment by josgroenewegen** [comment]
I will contact Somfy, if they can help me out?
When I try to login web based (Somfy connect) I get an error.

The app version I don't know

If they can't help me I will try to make a new account, but I haven't figured out to reset my Connexoon yet. Because it was working fine before, and I don't hear other homey users having this issue with the app.

Thanks for your feedback and time to respond to my messages:)

Jos

**Comment by josgroenewegen** [comment]
I just found out that this happens after a box update from Somfy, after the update homey doesn't work anymore. I can't find out what software version is loaded at the moment

**Comment by AdyRock** [comment]
As you can't log in to Somfy via their website, that does explain why the Homey app is having issues. I'm not sure why the box update would cause that though. 
I was wondering what version of the Homey Tahoma app you have installed?

**Comment by josgroenewegen** [comment]
Version v3.0.35

**Comment by Camille-D** [comment]
Hi,
I get the same 401 error when I try to login.  Did you find the problem?

Thank you

Device : Homey bridge

**Comment by AdyRock** [comment]
Unfortunately not. It appears that the Somfy server are having some issues for some people.

**Comment by josgroenewegen** [comment]
Hi Andy and Camille,

Somfy fixed my problem yesterday. I am not quite sure what they did but it looked like a hard reset from their side.

The box was unavailable for 10/15 minutes rebooted a couple of times but after that it was possible to connect and add devices.

So the best option is call Somfy report that you have code 401 while trying to connect. They will tell you to first reinstall the app and restart Homey. I even tried to connect with Olisto although I could connect, my devices where not shown in this app.

Hopefully Somfy can help you as well Camille

With kind regards, thanks for all your help Andy!!

**Comment by bijvejos** [comment]
Same issue here, with Tahoma mini. 
Will contact Somfy for help.

**Comment by josgroenewegen** [comment]
This week again connection problems with my Connexoon, called Somfy again only this time their reset (or what they did) didn't work this time.

I asked to put back the previous version of the software, this is still ongoing.

**Comment by bijvejos** [comment]
401 issue as well. Somfy reset the tahoma (mini), but no change. 

Obviously, there is no proper log at the Homey cloud when this occurs.
I put in a a Homey beta issue at Athom, but no response yet.

**Comment by Mironman** [comment]
Hello,

I've Conectivity kit, and it doesn't work anymore.
The problem is the connection.
I checked with somefy-connect and it doesnt work. Somfy says that this website is not accesible for connectivity kit.
I asked Atom for support and they bring me to the github because they didn't develop this app.
I try with IFTTT and it worked (only launch scene availlable in IFTTT), so there is a way to connect... I hope so.

I hope this few informations / confirmations will help.

Br,

**Comment by thezahir1** [comment]
Hi @AdyRock and @josgroenewegen, i have the same issie too, since I installed the Somfy update on the Connexoon box. It's really annoying since, in my house, so many flows rely directly or indirectly on my Somfy motorized screens (especially with the latest tropical temperatures....🌞. Anyone know how this may be solved or is this going to be a waiting game for Somfy to fix it?

**Comment by AdyRock** [comment]
Are you also using Homey cloud or do you have a Pro?

**Comment by thezahir1** [comment]
I have a Homey pro

**Comment by AdyRock** [comment]
Could you open the Configure App screen and enable the log then try to connect. Once it has failed could you send me the log on here. Don't use the Send log button as my Internet in the area is down at the moment.

**Comment by bijvejos** [comment]
I tried again on Homey cloud:
82a006c8-ac5d-4941-b28f-6ee372ebca4c

Plus I logged a request  (44704) at Athom,
which was sent to development team. They could be contacting you about this.

Cheers
Jos Bijvelds


Op ma 15 aug. 2022 20:22 schreef Adrian Rockall ***@***.***>:

**Comment by josgroenewegen** [comment]
Hi, Andy tried a reset today. Somfy deleted all, started with a new account, new activation of the product but still no change. I can't connect via the homey app (error 401)

**Comment by AdyRock** [comment]
I have been trying to get Athom to look into why I'm not getting any logged data via the Diagnostics report on Homey. It works fine on the Pro and Emile says it should work on Homey.

**Comment by thezahir1** [comment]
> Could you open the Configure App screen and enable the log then try to connect. Once it has failed could you send me the log on here. Don't use the Send log button as my Internet in the area is down at the moment.

It seems like the issue has resolved itself. Repeatedly logging in is successful. Did not (consciously) do something differently though...

**Comment by Mironman** [comment]
FYI : Always not ok for me with homey béta. still 401

**Comment by josgroenewegen** [comment]
Just wondering, is this only on homey beta? So if I would buy a pro I shouldn't have this problem?

**Comment by AdyRock** [comment]
I have no problem with my Pro even though I can't connect via Homey.
The test version of the app on the Pro also works locally with most devices connect to the Tahoma box

**Comment by keitje** [comment]
I also have the Homey Bridge and the Somfy Connexoon and get a 401 error. Couple of months ago we couldn't connect because of the many beta apps on Homey Cloud connecting to Somfy datacenter at same time from same IP adress. That problem has been fixed. But now I get the 401 every time. Shouldn't have bought the Bridge.....

**Comment by Mironman** [comment]
Hello,
triing with the last version (not test) it's still 401 error  with my bridge.

**Comment by josgroenewegen** [comment]
Hi,

Today Somfy is using the Tahoma app also for the connexoon. Does that bring any possibility's to connect the connexoon and the homey bridge again?
Still got the 401 error at the moment

**Comment by AdyRock** [comment]
I'm not sure it will change anything as the issue affects Tahoma users as well.

**Comment by AdyRock** [comment]
Looks like the Homey (cloud) connection is working again for me.

**Comment by keitje** [comment]
I'm running 4.0.15 experimental. Is that the latest version of the app for the Homey Bridge?

**Comment by AdyRock** [comment]
I'm not near a computer right now so I can't check. But the same version of the app runs on both Homey and Homey Pro.

**Comment by keitje** [comment]
I've just tested it. Homey Bridge, app version 4.0.15. Somfy Connexoon with the new Tahoma app and reconnected the devices to Homey. Works like a charm!
