### ISSUE TITLE
Does not find External Blind (IO) 

### ISSUE THREAD

**Issue by catohauk** [AdyRock/com.somfy.tahoma#72]
Hi,

I've set up Somfy Tahoma with 3 external blinds with Somfy IO motor. Works fine in the Tahoma app and with remote control. When trying to add in Homey is states that no new items can be found. Tried adding "roller shutter with quiet mode" and "roller shutter" as well as this was suggested. No luck :(

**Comment by catohauk** [comment]
I've sent the logs btw. The screens are called "Solskjerming TV", "Solskjerming Sofa" and "Solskjerming Kontor"

**Comment by AdyRock** [comment]
Thanks for the logs. Pick the "Awning / Pergola (io)" / "Buitenzonwering / Pergola (io)" device when adding them to Homey.

**Comment by catohauk** [comment]
Wow. Quick reply. I did that, and that works, so thank you very much! 

Any idea why I had to select this and not the blinds?

**Comment by AdyRock** [comment]
Hopefully this will explain it :-) https://community.homey.app/t/app-pro-somfy-tahoma-connexoon-v3-0-35-test-v4-0-2/35206/1229?u=adrian_rockall

**Comment by catohauk** [comment]
It does. Thank you once again. Have a great one.
