### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by Shinai87** [AdyRock/com.somfy.tahoma#74]
Hey Adrian,

I entered Homey Beta and everything is working fine so far.
The only thing I can't get to work is the Tahoma Switch.
Every time I try to log in to add a device, I get the error message: Request failed with status code 401
Things to note:
1.) I was never able to once successfully log in to the app
2.) I can log in fine in my Somfy Account and in the Somfy Tahoma App
3.) I cannot log in to https://www.tahomalink.com (Error Message: An error has occurred on the server)

Things I've tried:
1.) I have changed my Somfy credentials and verified they are not the problem
2.) I have tested different versions of the Homey Somfy App including the latest test version 4.0.6
3.) I enabled developer mode on the Tahoma Switch
4.) I called Somfy Support and asked for assistance

And here things get interesting... Somfy Support said, that it is no longer possible for Tahoma Switch User to https://www.tahomalink.com. They also verified that there is some kind of account restriction, which prevents the Tahoma Switch User from logging in to https://www.tahomalink.com. When I asked if it's possible to remove this restriction, they denied it and pointed out that Tahoma Switch is designed to solely work with the app.

Can anyone confirm this information? Ist there some kind of workaround or are the Tahoma Switch Users out of luck?
Thank you very much for your assistance.

**Comment by Shinai87** [comment]
Update:
I just called Somfy Support again and they verified, that my account is not locked on their side. Furthermore the support agent stated, that Tahoma Switch uses a new API, namely https://developer.somfy.com/. The old API https://www.tahomalink.com/ is not used anymore for new Somfy products.

**Comment by prochazkajp** [comment]
Hi!
I have the same issue as described above, but with regural TaHoma box (no switch). I activated the developer mode and everything but I still can't connect from the Homey app... any advice?

**Comment by AdyRock** [comment]
I presume you have a Homey Pro?
Are you using the latest test version of the app?
If so, could you enable the log in the Configure App screen, then try to connect and then copy the log screen to here. Don't use the Send Log button as my Internet is down at the moment.

**Comment by prochazkajp** [comment]
Actually, I have Homey Bridge with Homey beta. I can see the app installed (test version 4.0.6) but there is no logging option in to enable - only send diagnostic report (send button not working) and remove the app.

**Comment by AdyRock** [comment]
Ok, Homey cloud  / bridge is cloud to cloud only so the local access via developer mode won't work. 
The app should still work cloud to cloud but there is an issue with Somfy at the moment causing Homey connections to fail. 
Unfortunately, the diagnostics option in Homey is not working, so I can't even get any good diagnostics but I think Somfy are rejecting connections from Homey servers.

**Comment by AdyRock** [comment]
There is a new test version that changes the way the information is logged to see if Homey can report it with the Create Diagnostic report function.

**Comment by MisterMister66** [comment]
Hey Adrian,
I experience the same problem actually with the homey bridge.
Is it solved with Pro?
Thank you... for help

**Comment by AdyRock** [comment]
Homey Pro doesn't have the same problem because each Homey has its own IP address rather than lots of Homey's running on the same server.

**Comment by MisterMister66** [comment]
Ok, thank you. But what will be the solution if I need the integration? Do somfy know the issue?
I think about changing to Pro, but actually they are not available.

**Comment by Hpgithub77** [comment]
Here also Homey bridge and Homey beta. I keep getting error code 401 when trying to login the newest Tahoma connexoon App. I want my Somfy protect smoke alarms in Homey. I can login the newest Tahoma App. What is wrong here?

**Comment by AdyRock** [comment]
Somfy block the Homey server IP addresses because too many failed login attempts from them.

**Comment by Hpgithub77** [comment]
What am I to do then.. Wait and see?

**Comment by AdyRock** [comment]
Unfortunately I don't know the answer. I have been making changes in the app to try and solve the problem but so far no luck.

**Comment by Hpgithub77** [comment]
Thanks anyway! and I will wait a little longer..
