### ISSUE TITLE
Problem adding RTS blinds

### ISSUE THREAD

**Issue by SweZoo2** [AdyRock/com.somfy.tahoma#75]
Hi Adrian

I have som issues adding 3 RTS blinds I have connected to Somfy Tahoma Connectivity kit. I send you a device log a few minutes ago.

When I try to add them they can't be found. The scenes work fine though 😀

Please let me know if you need any more information.

Kind regards //Sam

**Comment by AdyRock** [comment]
I have the log so will take a look this evening.

**Comment by AdyRock** [comment]
I'm really sorry for the delay in responding as I forgot to check.
The blinds should be found if you select the "Velux interior blind (io)"

**Comment by SweZoo2** [comment]
Sorry for the late reply. Been having some connection issues last week to the Tahoma box. 

I'm not able to find any under "Velux interior blind (io)". I have tried  a few different options as well, but don't seems to be able to find them anywhere. 

Let me know if you need any more logs from me.

**Comment by AdyRock** [comment]
Could you send the log again and also let me know on here what names you gave them in Tahoma?

**Comment by SweZoo2** [comment]
Hi
Log sent.
Uterum (mitten), Uterum (höger), Uterum (vänster).
In total 3 blinds (sorry for the Swedish in the names).

**Comment by AdyRock** [comment]
The blinds show up as "Velux interior blind (io)"
![image](https://user-images.githubusercontent.com/38184396/185778610-949a5251-64b9-4ed4-91e4-58684bfb234c.png)

However, I see that Somfy are changing the rules as the previous cases for "controllableName": "ogp:Blind" have been IO devices. Now I see they are using that as a more generic term and have include other features to determine the sub type.

So, for now, I think you should be able to add them but ignore the position slider as that won't work, instead just use the Up / Stop / Down buttons. When I get a bit of time I will have to change the way the app treats the "ogp:Blind" to filter the controls.
