### ISSUE TITLE
Connect Somfy switch to Homey

### ISSUE THREAD

**Issue by Dkoster01** [AdyRock/com.somfy.tahoma#76]
Dear Adrian,

After a defect in my Somfy Connexoon, I had bought a Somfy Switch in order to connect my blind in the roof. (i/O engines)
I am now able to control them with the Somfy app on my phone. But unfortunately I am not able to add the blinds in the Homey app. Homey can't find the blinds/engines.

What did I do wrong?

Looking forward to your reply.

Kind regards,
Dennis Koster

**Comment by AdyRock** [comment]
Could you send the Device log from the Configure App screen?

**Comment by Dkoster01** [comment]
Hi Adrian,

Thanks for your swift reply.
Just send you the Device log.

Kind regards,
Dennis Koster
________________________________
Van: Adrian Rockall ***@***.***>
Verzonden: Wednesday, August 31, 2022 11:27:34 AM
Aan: AdyRock/com.somfy.tahoma ***@***.***>
CC: Dkoster01 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.somfy.tahoma] Connect Somfy switch to Homey (Issue #76)


Could you send the Device log from the Configure App screen?

**Comment by AdyRock** [comment]
They should be found using the "Awning / Pergola (io)"/"Buitenzonwering / Pergola (io)" device.

**Comment by Dkoster01** [comment]
And do i have to press any “learn” button of the pergola?
________________________________
Van: Adrian Rockall ***@***.***>
Verzonden: Wednesday, August 31, 2022 10:17:49 PM
Aan: AdyRock/com.somfy.tahoma ***@***.***>
CC: Dkoster01 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.somfy.tahoma] Connect Somfy switch to Homey (Issue #76)


They should be found using the "Awning / Pergola (io)"/"Buitenzonwering / Pergola (io)" device.

**Comment by Dkoster01** [comment]
Thanks Adrian ! It works.
________________________________
Van: Adrian Rockall ***@***.***>
Verzonden: Wednesday, August 31, 2022 10:17:49 PM
Aan: AdyRock/com.somfy.tahoma ***@***.***>
CC: Dkoster01 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.somfy.tahoma] Connect Somfy switch to Homey (Issue #76)


They should be found using the "Awning / Pergola (io)"/"Buitenzonwering / Pergola (io)" device.
