### ISSUE TITLE
Somfy Sliding Gate Device not shown in homeykit

### ISSUE THREAD

**Issue by tbard1** [AdyRock/com.somfy.tahoma#77]
Hi there, thanks for your great app !

I Installed successfully the tahoma app, but I don't understand how to get it showed in homeykit ?

Thanks !

**Comment by AdyRock** [comment]
Is the gate showing in Homey?

**Comment by tbard1** [comment]
Yep



Le dim. 25 sept. 2022 à 15:06, Adrian Rockall ***@***.***> a
écrit :

**Comment by AdyRock** [comment]
The app uses the windowcoverings_state for the main capability as Homey doesn't have anything specific for a gate. So, maybe you could add in Homeykit as a curtain. I don't use Homeykit so I'm not sure how it determines devices.

**Comment by tbard1** [comment]
Ok, I'll check it out.

Le dim. 25 sept. 2022 à 19:18, Adrian Rockall ***@***.***> a
écrit :
