### ISSUE TITLE
Unable to connect connexoon to homey app

### ISSUE THREAD

**Issue by JurgenJacobs76** [AdyRock/com.somfy.tahoma#78]
I enherited a homey and connexoon setup. After I had my connexoon moved to my somfy account I'm unable to connect to it through the homey app. Message shown upon entering my new somfy credentials "unable to login". As long as the connexoon was still registered to the previous owner there where no issues.

I am able to login to the connexoon Windows app so my credentials are correct. (Unable to login to tahoma)

**Comment by AdyRock** [comment]
Could you send me the Information Log from the Apps - Somfy TaHoma & Connexoon - Configure App screens

**Comment by JurgenJacobs76** [comment]
Thanks Adrian, i have been able to get it working but forgot about my earlier post. Sorry for that.
