### ISSUE TITLE
raquest failed wit status code 400

### ISSUE THREAD

**Issue by Jurgendv83** [AdyRock/com.somfy.tahoma#79]
I get this message when pressing on a io shutter. It works but every time i press on it i get this message. Have deleted the app and reinstalled it. Now it works without getting the message. second time this month i have to do this, what can be the reason? i'm i doing something wrong or?

**Comment by AdyRock** [comment]
Sorry I have taken so long to get back to.
Somfy have been having a few server issues recently so maybe that is the problem.
Has the problem resolved it's self since you posted?
