### ISSUE TITLE
Automatic uninstallation every day

### ISSUE THREAD

**Issue by wahlen-bastien** [AdyRock/com.somfy.tahoma#80]
After installing the application and the peripherals, everything works perfectly.
Only after a day the app uninstalls itself from the box, and the peripherals no longer work. All you have to do is restart an installation on the box and it works again... for a short day.

Do you have any help for this.

Best regards

**Comment by wahlen-bastien** [comment]
#Somfy connexoon

**Comment by AdyRock** [comment]
I have not seen that before. I will need to check with Athom to see if they can help.

**Comment by wahlen-bastien** [comment]
Great thank you, for the moment it punctuates my start to the day.

**Comment by AdyRock** [comment]
Just to be sure, does it uninstall or just crash?
Is it possible to still see the app in the list of installed apps and just restart it?
Do you have a Homey Pro or Homey cloud?
What version of the app are you using?

**Comment by wahlen-bastien** [comment]
For the presence of the app, I tell you again because I reinstalled it this morning.
For the material used it is:
Homey Pro
software version: V8.0.6

**Comment by AdyRock** [comment]
Feedback from Athom said that's not possible. How are you installing the app?
Sorry to go back to the same question that you have answered, but can you confirm that you have looked in the Apps list section of the phone app to verify the app has not crashed?
![Screenshot_20221009-192914_Homey](https://user-images.githubusercontent.com/38184396/194773451-d1247182-2ec2-485c-aa23-d66c1201282c.jpg)
