### ISSUE TITLE
Tahoma app will take over from Connexoon

### ISSUE THREAD

**Issue by runely** [AdyRock/com.somfy.tahoma#81]
Hi

I got a mail from Somfy that the Connexoon app will disappear and we should start using the Tahoma app instead.

When I signed in to the new Tahoma app I'm being asked to move my screen from the Connexoon app into the Tahoma app and **that this step is not recordable..**

Will the homey app still work with my screen after the move?

**Comment by AdyRock** [comment]
As far as I know it should still work. The app communicates with the Somfy server and it can't see a difference between Tahoma and Connexoon accounts, so I have no reason to believe it won't work. Also one user on the Homey forum has said they had no issues.

**Comment by runely** [comment]
Thank you for the clarification, and you are right, my screen still works from the homey app 👍
