### ISSUE TITLE
Problem adding my Somfy devices 

### ISSUE THREAD

**Issue by Em1974** [AdyRock/com.somfy.tahoma#82]
Hi, I am trying to add my Tahoma switch to Homey, but could only find Tahoma Connexoon box.
Then what do I have to do to add my RTS shutter? Because when I select the Venetian shutter it does not find anything.
Can you please help me? 
thanx a lot
Emiliano

**Comment by AdyRock** [comment]
The motor maybe reported as a different type. Could you go to the Device Log in the Configure App screen, tap on Get Log and when the list is populated tap on Send Log. 
I will then make sure the device is supported and let you know which option to select when adding it.

**Comment by Em1974** [comment]
Hi thanx for the answer, I sent the log yesterday. Can you confirm me it went well?ThanxEmiliano Inviato da iPhoneIl giorno 11 nov 2022, alle ore 07:22, Adrian Rockall ***@***.***> ha scritto:﻿
The motor maybe reported as a different type. Could you go to the Device Log in the Configure App screen, tap on Get Log and when the list is populated tap on Send Log.
I will then make sure the device is supported and let you know which option to select when adding it.

**Comment by AdyRock** [comment]
I got some Information logs yesterday but not any device logs.

**Comment by Em1974** [comment]
May it be because I don’t know how to add the devices    ?Emiliano Inviato da iPhoneIl giorno 11 nov 2022, alle ore 10:46, Adrian Rockall ***@***.***> ha scritto:﻿
I got some Information logs yesterday but not any device logs.

**Comment by Em1974** [comment]
I am sorry for my bad English, I will try to explain it better.I have bought a Tahoma switch box, three shutters, an Homey pro (late 2019).I added all the devices to my Tahoma app on my iPhone and all works well.I added the app Tahoma also to Homey but I could not add the Tahoma switch, i only found a Tahoma connexoon generic device. I added that and that’s all I got.When I try to add the shutters I do not find them.Emiliano Inviato da iPhoneIl giorno 11 nov 2022, alle ore 10:46, Adrian Rockall ***@***.***> ha scritto:﻿
I got some Information logs yesterday but not any device logs.

**Comment by AdyRock** [comment]
Yes. I understand (your English is fine), but to help you I need the Device Log so I can see what the devices are reporting as.
So, go to the Configure App screen,
Select the Device Log tab,
Tap on Get Log,
Wait for a few seconds so the list fills up, 
Tap on Send Log.

**Comment by Em1974** [comment]
I do that and nothing changes, o have waited 15 minutes but no log appears Emiliano Inviato da iPhoneIl giorno 11 nov 2022, alle ore 14:30, Adrian Rockall ***@***.***> ha scritto:﻿
Yes. I understand (your English is fine), but to help you I need the Device Log so I can see what the devices are reporting as.
So, go to the Configure App screen,
Select the Device Log tab,
Tap on Get Log,
Wait for a few seconds so the list fills up,
Tap on Send Log.

**Comment by AdyRock** [comment]
Ok, just to be sure we are talking about the same thing, the log appears in the box at the bottom of the page:
![Screenshot_20221111_163947_Homey](https://user-images.githubusercontent.com/38184396/201388156-5416e3d9-a74f-4a15-8d03-c4bfb7f506be.jpg)

**Comment by Em1974** [comment]
Exactly I am sending a video of my iPhone screen so you can see it Emiliano Inviato da iPhoneIl giorno 11 nov 2022, alle ore 17:43, Adrian Rockall ***@***.***> ha scritto:﻿
Ok, just to be sure we are talking about the same thing, the log appears in the box at the bottom of the page:

**Comment by AdyRock** [comment]
I haven't received the video. Where did you send it?

**Comment by Em1974** [comment]
Was attached to the mail. I will put it in this mail too.Here Can you see it?Emiliano Inviato da iPhoneIl giorno 11 nov 2022, alle ore 20:53, Adrian Rockall ***@***.***> ha scritto:﻿
I haven't received the video. Where did you send it?

**Comment by AdyRock** [comment]
No, GitHub doesn't support attachments.
Could you send it to ady@rockall.plus.com

**Comment by AdyRock** [comment]
No, GitHub doesn't support attachments. 
Could you send it to ady@rockall.plus.com.

**Comment by Em1974** [comment]
Sent Inviato da iPhoneIl giorno 11 nov 2022, alle ore 21:27, Adrian Rockall ***@***.***> ha scritto:﻿
No, GitHub doesn't support attachments.
Could you send it to ***@***.***

**Comment by AdyRock** [comment]
Ok, that is strange. After pressing the button, can you tap on the Send Log button just incase it is a screen refresh issue?
Are you using the latest versions of the Homey app, Somfy Tahoma and Connexoon app and Homey firmware?
Also could you check the Information log and if there is something in there, tap on Send Log on that screen.

**Comment by Em1974** [comment]
Information log sent, the other log it says no data to sendInviato da iPhoneIl giorno 11 nov 2022, alle ore 21:40, Adrian Rockall ***@***.***> ha scritto:﻿
Ok, that is strange. After pressing the button, can you tap on the Send Log button just incase it is a screen refresh issue?
Are you using the latest versions of the Homey app, Somfy Tahoma and Connexoon app and Homey firmware?
Also could you check the Information log and if there is something in there, tap on Send Log on that screen.

**Comment by Em1974** [comment]
Yes I am using all the latest updates and firmware Inviato da iPhoneIl giorno 11 nov 2022, alle ore 21:40, Adrian Rockall ***@***.***> ha scritto:﻿
Ok, that is strange. After pressing the button, can you tap on the Send Log button just incase it is a screen refresh issue?
Are you using the latest versions of the Homey app, Somfy Tahoma and Connexoon app and Homey firmware?
Also could you check the Information log and if there is something in there, tap on Send Log on that screen.

**Comment by AdyRock** [comment]
So the information log seems to show the app is logged in OK. 
Could you try via the developer portal.:
https://tools.developer.homey.app/tools/app-settings

**Comment by Em1974** [comment]
I performed a search of my devices via the developers page and it worked suddenly.Thanx a lot .Emiliano Inviato da iPhoneIl giorno 11 nov 2022, alle ore 22:42, Adrian Rockall ***@***.***> ha scritto:﻿
So the information log seems to show the app is logged in OK.
Could you try via the developer portal.:
https://tools.developer.homey.app/tools/app-settings

**Comment by AdyRock** [comment]
Does that mean you have now added you devices to Homey?
If you still can't add them, then send the device log from the developer portal so I can check the information.

**Comment by Em1974** [comment]
Yes exactly I added in that page that you sent me and now everything works well.Thanx a lotEmiliano Inviato da iPhoneIl giorno 12 nov 2022, alle ore 09:37, Adrian Rockall ***@***.***> ha scritto:﻿
Does that mean you have now added you devices to Homey?
If you still can't add them, then send the device log from the developer portal so I can check the information.
