### ISSUE TITLE
wn30 integration to homey without gateway

### ISSUE THREAD

**Issue by miszterx** [AdyRock/com.somfy.tahoma#83]
Hi,

I have a WN30 ecowitt temperature sensor. Can I add it to the homey directly without separated gateway? Or it is required for homey integration to pair the WN30 to a gateway and then I can add it just to the homey?

**Comment by AdyRock** [comment]
This app needs one of the gateways as it communicates via the LAN. Also it will use the Misol and Ecowitt app.
