### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by Meki1984** [AdyRock/com.somfy.tahoma#85]
Hello

Since a few days, I receive in the Homey Pro / Homey app with your application the following failure message "Request failed with status code 400", if I select a shutter device. A restart of the application didn't bring a positive result.

Homey Pro App: 4.0.13
Tahoma Box Version: 2022.6.4

Do you have any idea what happened?

Many thanks in advance.

Best regards 

Meki

**Comment by AdyRock** [comment]
Sorry I have taken so long to get back to.
Somfy have been having a few server issues recently so maybe that is the problem.
Has the problem resolved it's self since you posted?
