### ISSUE TITLE
Unable to add Somfy buitenzonwering RTS to Tahoma app

### ISSUE THREAD

**Issue by bijvejos** [AdyRock/com.somfy.tahoma#88]
Hi Andy. 
Could not add Buitenzonwering RTS to Homey cloud using Tahoma app.
I get panel saying No new devices found.
I am able to add Screens or Blinds RTS.

Updated tahoma app (also tried v15)  and firmware today because it had been failing since last summer. Most functions now work, except for this one.

Thanks for checking,
Cheers 
Jos.

**Comment by AdyRock** [comment]
Wow, not sure how I have missed this issue for so long.
If you haven't already got it working, could you send me the Device Log from the App - Settings.

**Comment by bijvejos** [comment]
Thanks for reviewing Adrian.
Here's the report id:

7d53203c-f125-4327-bf03-8ad61a227baa

Cheers,
Jos

Op vr 4 aug. 2023 10:52 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
Ah, OK you are using Homey cloud. Could you go through the add device procedure, select any of the devices in my Tahoma app, then when you see no devices to add send the Diagnostics log again. Hopefully the log will capture the list of devices discovered during the procedure.

**Comment by bijvejos** [comment]
New log:

08005b10-bbe1-4897-8d1d-62243b6afe75

Op vr 4 aug. 2023 13:52 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
I hate Homey cloud as it is bad a providing diagnostic data. Unfortunately the ne log doesn't contain enough information either. 
All I can suggest is trying every type of blind, shutter, etc, as manufacturers often use different motors than expected.

**Comment by bijvejos** [comment]
Thanks Adrian.
You can close the issue,
I am now looking at Home Assistant and that picks up the Thomas stuff in
one go and works like a charm.

Cheers, and thx again for your help.


Op vr 4 aug. 2023 19:50 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
Ok, hope HA goes well.
