### ISSUE TITLE
adding tahoma smoke detectors

### ISSUE THREAD

**Issue by Hpgithub77** [AdyRock/com.somfy.tahoma#89]
Every time I want to add my smoke detectors, homey says: I found no new devices.
What am I doing wrong here? I have Homey app 6.11.13.1051 and not Homey pro.
And Somfy TaHoma & Connexoon v4.0.13
Thanks in advance,
Herbert

**Comment by Hpgithub77** [comment]
I did a diagnostic report and the code is:
d36d050f-af1d-4d15-8f65-446307f67367

**Comment by AdyRock** [comment]
oops, another issue I have missed, so sorry.
I presume you mean you are using the Homey (cloud) version (Athom's naming is very confusing).
If you still haven't solved the problem, can you update to the latest version and send a log again please.

**Comment by AdyRock** [comment]
Did this get resolved?
