### ISSUE TITLE
Couldn't add device on connectivity kit

### ISSUE THREAD

**Issue by Batidoi** [AdyRock/com.somfy.tahoma#92]
I just buy a connectivity kit for my exavia star but I can't add it. I log to my Somfy account with no problem.
When I try to add my device I've got the fellowing message : No device found
I just send you the log.

Can you help me please.

**Comment by AdyRock** [comment]
I have added your device to the new version 4.0.16. It can be found under 'Gate / Garage Door Opener (RTS)'.

**Comment by Batidoi** [comment]
It works.👍 Thank you so much. 🙏
