### ISSUE TITLE
Far too many login attempts (blocked for 15 minutes) and Failed to send command

### ISSUE THREAD

**Issue by rpkbs** [AdyRock/com.somfy.tahoma#93]
![Left](https://user-images.githubusercontent.com/86825929/221169652-8af50238-208d-4269-9407-6ad03c893c06.png)
![Right](https://user-images.githubusercontent.com/86825929/221169659-a4707374-f1b0-46af-ad71-e539fad46623.png)

Hi,

I've got a problem with the app.
I've got 2 sunscreens.
when clicking on the left one I get "Far too many login attempts (blocked for 15 minutes)" failure
an the right one "Failed to send command"

In the advanced settings Login is Succesfull

Can you help me solve this issue

gr
Robin

**Comment by AdyRock** [comment]
This is normally caused by a temporary issue on the Somfy servers. Try again after about an hour and if it still happens then send me the log from the Configure App screen.

**Comment by rpkbs** [comment]
Thanks, but this is not a new issue, is already for weeks now.

I will now send 3 logs

gr

Van: Adrian Rockall ***@***.***>
Verzonden: vrijdag 24 februari 2023 14:21
Aan: AdyRock/com.somfy.tahoma ***@***.***>
CC: rpkbs ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.somfy.tahoma] Far too many login attempts (blocked for 15 minutes) and Failed to send command (Issue #93)


This is normally caused by a temporary issue on the Somfy servers. Try again after about an hour and if it still happens then send me the log from the Configure App screen.

**Comment by rpkbs** [comment]
Do you have a solution?

gr

**Comment by AdyRock** [comment]
From the logs, I can see that after the delay, it is logging in, so the app is doing what it is supposed to. The error code 502 indicates a temporary server issue.

**Comment by AdyRock** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

**Comment by rpkbs** [comment]
ok, thanks for your effort and replying.
keep up the good work....
