### ISSUE TITLE
syncLoop - Old Sync State = false

### ISSUE THREAD

**Issue by tkroon89** [AdyRock/com.somfy.tahoma#96]
Hi Adrian,

I just sent you an informatioin log from the Somfy Tahoma & Connexoon app. Timestamp around 19-03-2023 07:08.

It says local = true, fetching complete, but old sync state = false. And then "next cloud sync in 9s". Could you confirm this is working properly? Is the app truly getting its data local from my Connexoon? 

Thank you!

Kind regards,

Thomas

**Comment by AdyRock** [comment]
Yes, it is using local. It still runs the cloud timer to update any devices that are not supported locally. 
Basically, the app fetches the list of cloud devices (everything) and the list of local devices (possibly not everything). Then, when a device update is requested, it tries local first but if that fails it tries the cloud. 
However, I have fixed a bug in on of  the test versions, as I found some devices were not using the cloud to control them.
