### ISSUE TITLE
Can Not find my io chutters on the connectiviteit hub

### ISSUE THREAD

**Issue by AdriHerman** [AdyRock/com.somfy.tahoma#97]
HOI
I have 5 chutters somfy io and 1 remote controller Situo 5io PURE II
Can Not find my io chutters on the connectivity hub, ith the tahoma app

**Comment by AdyRock** [comment]
Can you got to https://tools.developer.homey.app/tools/app-settings, select the Somfy TaHoma & Connexoon app, go to the Device Log tab and click on Get Log. Once the list has filled up, click on Send Log.

**Comment by AdriHerman** [comment]
I just send you the logs

**Comment by AdyRock** [comment]
Try with the "Velux roller shutter(io)" device, that should find them.

**Comment by AdriHerman** [comment]
OK it works. Thanks
