### ISSUE TITLE
Try to add Somfy app. Login problems to Somfy 

### ISSUE THREAD

**Issue by Piet48** [AdyRock/com.somfy.tahoma#98]
I'm new with Homey. Trying to add Somfy app for my somfy remote control. I have to enter Somfy account but that does not work. Says: Error    OK. I tried several times. What can be wrong?

**Comment by AdyRock** [comment]
Do you have one of the Somfy hubs, such as Tahoma or Connexoon?

**Comment by Piet48** [comment]
No

Op ma 27 mrt. 2023 12:43 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
Ah, OK, this app needs one of the hubs and an online Somfy account. 

Are your devices RTS or IO?

**Comment by Piet48** [comment]
Answer loud and clear. Thanks!

Op ma 27 mrt. 2023 12:53 schreef Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
If you have RTS devices then you could try the Athom Somfy RTS app.

If they are IO then the only option is to purchase at least the Somfy Connectivity Kit. The main advantage of the Tahoma or Connexoon hubs being local control versus the cloud only connection for the Connectivity kit.
