### ISSUE TITLE
Problem with Rollers shutter

### ISSUE THREAD

**Issue by Davdu07** [AdyRock/com.somfy.tahoma#99]
Hello, i have problem with the tahoma app, i could install the app but i can't find my roller shutter with quiet mode, i'm french, i copy you my device log

            },
            {
              "commandName": "setName",
              "nparams": 1
            },
            {
              "commandName": "stop",
              "nparams": 0
            }
          ],
          "states": [
            {
              "type": "DataState",
              "qualifiedName": "core:ActivatedOptionsState"
            },
            {
              "type": "DiscreteState",
              "values": [
                "available",
                "unavailable"
              ],
              "qualifiedName": "core:AvailabilityState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:AvailableOptionsState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:ClosureState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ErrorState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ErrorsState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareHashState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareRevisionState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NameState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NewFirmwareAvailableState"
            },
            {
              "type": "DiscreteState",
              "values": [
                "closed",
                "open"
              ],
              "qualifiedName": "core:OpenClosedState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ReachedAliasesState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RecommendedOptionsState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RemovableState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:SignalQualityState"
            }
          ],
          "dataProperties": [],
          "widgetName": "DynamicShutter",
          "uiProfiles": [
            "StatefulCloseableShutter",
            "StatefulCloseable",
            "Closeable",
            "StatefulOpenClose",
            "OpenClose"
          ],
          "uiClass": "Shutter",
          "qualifiedName": "ogp:Shutter",
          "type": "ACTUATOR"
        },
        "states": [
          {
            "name": "core:NameState",
            "type": 3,
            "value": "Volet cuisine "
          },
          {
            "name": "core:AvailabilityState",
            "type": 3,
            "value": "available"
          },
          {
            "name": "core:ErrorsState",
            "type": 10,
            "value": []
          },
          {
            "name": "core:FirmwareRevisionState",
            "type": 3,
            "value": "5128569B00"
          },
          {
            "name": "core:FirmwareHashState",
            "type": 3,
            "value": "5128569B00"
          },
          {
            "name": "core:OpenClosedState",
            "type": 3,
            "value": "open"
          },
          {
            "name": "core:ClosureState",
            "type": 1,
            "value": 0
          },
          {
            "name": "core:ActivatedOptionsState",
            "type": 10,
            "value": []
          }
        ],
        "attributes": [
          {
            "name": "core:SupportedOptions",
            "type": 10,
            "value": [
              "silence"
            ]
          },
          {
            "name": "core:SubType",
            "type": 3,
            "value": "rolling"
          },
          {
            "name": "core:Technology",
            "type": 3,
            "value": "io2way"
          },
          {
            "name": "core:ManufacturerReference",
            "type": 3,
            "value": "shutter"
          },
          {
            "name": "ogp:Features",
            "type": 10,
            "value": [
              {
                "name": "firmware",
                "commandLess": true
              },
              {
                "name": "openClosePosition"
              },
              {
                "name": "openClose"
              },
              {
                "name": "optionControl"
              },
              {
                "name": "stop"
              },
              {
                "name": "identification"
              },
              {
                "name": "diagnosis"
              },
              {
                "name": "alias"
              }
            ]
          },
          {
            "name": "core:SupportedAliases",
            "type": 10,
            "value": [
              {
                "id": "1",
                "type": "favorite1",
                "features": [
                  "openClosePosition"
                ]
              }
            ]
          },
          {
            "name": "core:Manufacturer",
            "type": 3,
            "value": "Somfy"
          }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "e9c34204-ab4e-4df7-8f1f-411a9c4b2a38",
        "type": 1,
        "widget": "DynamicShutter",
        "oid": "73b6a345-bf64-4b4c-8f26-333ba131bb7e",
        "uiClass": "Shutter"
      },
      {
        "creationTime": 1679687368000,
        "lastUpdateTime": 1679687368000,
        "label": "Connectivity kit-ledBox",
        "deviceURL": "ogp://2106-5255-7643/15728639",
        "shortcut": false,
        "controllableName": "ogp:Light",
        "definition": {
          "commands": [
            {
              "commandName": "identify",
              "nparams": 0
            },
            {
              "commandName": "setIntensity",
              "nparams": 1
            },
            {
              "commandName": "setName",
              "nparams": 1
            }
          ],
          "states": [
            {
              "type": "DiscreteState",
              "values": [
                "available",
                "unavailable"
              ],
              "qualifiedName": "core:AvailabilityState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:IntensityState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:LightIntensityState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NameState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RemovableState"
            }
          ],
          "dataProperties": [],
          "widgetName": "DynamicLight",
          "uiProfiles": [
            "StatefulLightDimmer",
            "StatefulDimmable",
            "Dimmable"
          ],
          "uiClass": "Light",
          "qualifiedName": "ogp:Light",
          "type": "ACTUATOR"
        },
        "states": [
          {
            "name": "core:NameState",
            "type": 3,
            "value": "Connectivity kit-ledBox"
          },
          {
            "name": "core:AvailabilityState",
            "type": 3,
            "value": "available"
          },
          {
            "name": "core:IntensityState",
            "type": 1,
            "value": 100
          },
          {
            "name": "core:LightIntensityState",
            "type": 1,
            "value": 100
          }
        ],
        "attributes": [
          {
            "name": "core:ManufacturerReference",
            "type": 3,
            "value": "ledBox"
          },
          {
            "name": "core:Manufacturer",
            "type": 3,
            "value": "Overkiz"
          },
          {
            "name": "core:Technology",
            "type": 3,
            "value": "BoxTHmini"
          },
          {
            "name": "ogp:Features",
            "type": 10,
            "value": [
              {
                "name": "dimming"
              },
              {
                "name": "identification"
              }
            ]
          },
          {
            "name": "core:SubType",
            "type": 3,
            "value": "status"
          }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "d48cf8ad-eefd-4dfc-a410-56bbfbdd4be0",
        "type": 1,
        "widget": "DynamicLight",
        "oid": "10be1c07-62d1-4395-b266-c464ec7d5546",
        "uiClass": "Light"
      },
      {
        "creationTime": 1679687368000,
        "lastUpdateTime": 1679687368000,
        "label": "io2way",
        "deviceURL": "ogp://2106-5255-7643/16777212",
        "shortcut": false,
        "controllableName": "ogp:Bridge",
        "definition": {
          "commands": [
            {
              "commandName": "discover",
              "nparams": 0
            },
            {
              "commandName": "joinSetup",
              "nparams": 0
            },
            {
              "commandName": "sendPrivate",
              "nparams": 1
            },
            {
              "commandName": "shareSetup",
              "nparams": 0
            },
            {
              "commandName": "update",
              "nparams": 0
            }
          ],
          "states": [
            {
              "type": "DiscreteState",
              "values": [
                "available",
                "unavailable"
              ],
              "qualifiedName": "core:AvailabilityState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareHashState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareRevisionState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NameState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NewFirmwareAvailableState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private10State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private1State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private2State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private3State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private4State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private5State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private6State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private7State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private8State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private9State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RemovableState"
            }
          ],
          "dataProperties": [],
          "widgetName": "DynamicBridge",
          "uiProfiles": [
            "Specific"
          ],
          "uiClass": "ProtocolGateway",
          "qualifiedName": "ogp:Bridge",
          "type": "ACTUATOR"
        },
        "states": [
          {
            "name": "core:NameState",
            "type": 3,
            "value": "io2way"
          },
          {
            "name": "core:AvailabilityState",
            "type": 3,
            "value": "available"
          },
          {
            "name": "core:FirmwareRevisionState",
            "type": 3,
            "value": "dev-43144AFB24B202BF012416491223CF57"
          },
          {
            "name": "core:FirmwareHashState",
            "type": 3,
            "value": "43144AFB24B202BF012416491223CF57"
          }
        ],
        "attributes": [
          {
            "name": "core:Manufacturer",
            "type": 3,
            "value": "Overkiz"
          },
          {
            "name": "ogp:Features",
            "type": 10,
            "value": [
              {
                "name": "discovery"
              },
              {
                "name": "setupManagement"
              },
              {
                "name": "firmware"
              },
              {
                "name": "private"
              },
              {
                "name": "identification",
                "commandLess": true
              }
            ]
          },
          {
            "name": "core:Technology",
            "type": 3,
            "value": "io2way"
          },
          {
            "name": "core:ManufacturerReference",
            "type": 3,
            "value": "bridge"
          }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "d48cf8ad-eefd-4dfc-a410-56bbfbdd4be0",
        "type": 1,
        "widget": "DynamicBridge",
        "oid": "86566a36-a35b-4b1b-8024-48747cc30c2b",
        "uiClass": "ProtocolGateway"
      },
      {
        "creationTime": 1679687368000,
        "lastUpdateTime": 1679687368000,
        "label": "rts",
        "deviceURL": "ogp://2106-5255-7643/16777214",
        "shortcut": false,
        "controllableName": "ogp:Bridge",
        "definition": {
          "commands": [
            {
              "commandName": "sendPrivate",
              "nparams": 1
            },
            {
              "commandName": "pair",
              "nparams": 3
            }
          ],
          "states": [
            {
              "type": "DiscreteState",
              "values": [
                "available",
                "unavailable"
              ],
              "qualifiedName": "core:AvailabilityState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NameState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private10State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private1State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private2State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private3State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private4State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private5State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private6State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private7State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private8State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private9State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RemovableState"
            }
          ],
          "dataProperties": [],
          "widgetName": "DynamicBridge",
          "uiProfiles": [
            "Specific"
          ],
          "uiClass": "ProtocolGateway",
          "qualifiedName": "ogp:Bridge",
          "type": "ACTUATOR"
        },
        "states": [
          {
            "name": "core:NameState",
            "type": 3,
            "value": "rts"
          },
          {
            "name": "core:AvailabilityState",
            "type": 3,
            "value": "available"
          }
        ],
        "attributes": [
          {
            "name": "core:Manufacturer",
            "type": 3,
            "value": "Overkiz"
          },
          {
            "name": "core:Technology",
            "type": 3,
            "value": "rts"
          },
          {
            "name": "ogp:Features",
            "type": 10,
            "value": [
              {
                "name": "pairing"
              },
              {
                "name": "private"
              },
              {
                "name": "identification",
                "commandLess": true
              }
            ]
          },
          {
            "name": "core:SupportedNodeDefinitions",
            "type": 10,
            "value": [
              {
                "name": "outlet",
                "subTypes": [
                  {
                    "name": "default",
                    "definitions": [
                      "favorite1"
                    ]
                  }
                ]
              },
              {
                "name": "light",
                "subTypes": [
                  {
                    "name": "default",
                    "definitions": [
                      "favorite1"
                    ]
                  }
                ]
              },
              {
                "name": "shutter",
                "subTypes": [
                  {
                    "name": "rolling",
                    "definitions": [
                      "favorite1"
                    ]
                  },
                  {
                    "name": "sliding",
                    "definitions": [
                      "favorite1"
                    ]
                  },
                  {
                    "name": "swinging",
                    "definitions": [
                      "favorite1"
                    ]
                  }
                ]
              },
              {
                "name": "gate",
                "subTypes": [
                  {
                    "name": "swinging",
                    "definitions": [
                      "pedestrian"
                    ]
                  },
                  {
                    "name": "sliding",
                    "definitions": [
                      "pedestrian"
                    ]
                  }
                ]
              },
              {
                "name": "curtain",
                "subTypes": [
                  {
                    "name": "single",
                    "definitions": [
                      "favorite1"
                    ]
                  },
                  {
                    "name": "dual",
                    "definitions": [
                      "favorite1"
                    ]
                  }
                ]
              },
              {
                "name": "awning",
                "subTypes": [
                  {
                    "name": "default",
                    "definitions": [
                      "favorite1"
                    ]
                  }
                ]
              },
              {
                "name": "blind",
                "subTypes": [
                  {
                    "name": "indoor",
                    "definitions": [
                      "favorite1"
                    ]
                  },
                  {
                    "name": "outdoor",
                    "definitions": [
                      "favorite1"
                    ]
                  }
                ]
              },
              {
                "name": "venetianBlind",
                "subTypes": [
                  {
                    "name": "indoor",
                    "definitions": [
                      "favorite1"
                    ]
                  },
                  {
                    "name": "outdoor",
                    "definitions": [
                      "favorite1"
                    ]
                  },
                  {
                    "name": "indoor",
                    "definitions": [
                      "tiltOnlyWithFavorite1"
                    ]
                  }
                ]
              },
              {
                "name": "garageDoor",
                "subTypes": [
                  {
                    "name": "rolling",
                    "definitions": [
                      "ventilation"
                    ]
                  },
                  {
                    "name": "sliding",
                    "definitions": [
                      "pedestrian"
                    ]
                  }
                ]
              },
              {
                "name": "pergola",
                "subTypes": [
                  {
                    "name": "default",
                    "definitions": [
                      "favorite1"
                    ]
                  }
                ]
              }
            ]
          },
          {
            "name": "core:ManufacturerReference",
            "type": 3,
            "value": "bridge"
          }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "d48cf8ad-eefd-4dfc-a410-56bbfbdd4be0",
        "type": 1,
        "widget": "DynamicBridge",
        "oid": "fe367de7-8796-4f9b-844f-a3ae25314bc7",
        "uiClass": "ProtocolGateway"
      },
      {
        "creationTime": 1679687368000,
        "lastUpdateTime": 1679687368000,
        "label": "Connectivity kit-box",
        "deviceURL": "ogp://2106-5255-7643/16777215",
        "shortcut": false,
        "controllableName": "ogp:Gateway",
        "definition": {
          "commands": [
            {
              "commandName": "reboot",
              "nparams": 0
            },
            {
              "commandName": "reset",
              "nparams": 0
            },
            {
              "commandName": "sendPrivate",
              "nparams": 1
            },
            {
              "commandName": "setTimezone",
              "nparams": 1
            },
            {
              "commandName": "update",
              "nparams": 0
            }
          ],
          "states": [
            {
              "type": "DiscreteState",
              "values": [
                "available",
                "unavailable"
              ],
              "qualifiedName": "core:AvailabilityState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ErrorState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ErrorsState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareHashState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareRevisionState"
            },
            {
              "eventBased": true,
              "type": "DataState",
              "qualifiedName": "core:LocalAccessProofState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NameState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NewFirmwareAvailableState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private10State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private1State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private2State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private3State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private4State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private5State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private6State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private7State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private8State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:Private9State"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RemovableState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:SSIDState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:SignalQualityState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:TimezoneState"
            }
          ],
          "dataProperties": [],
          "widgetName": "DynamicGateway",
          "uiProfiles": [
            "Specific"
          ],
          "uiClass": "ProtocolGateway",
          "qualifiedName": "ogp:Gateway",
          "type": "ACTUATOR"
        },
        "states": [
          {
            "name": "core:NameState",
            "type": 3,
            "value": "Connectivity kit-box"
          },
          {
            "name": "core:AvailabilityState",
            "type": 3,
            "value": "available"
          },
          {
            "name": "core:SignalQualityState",
            "type": 1,
            "value": 100
          },
          {
            "name": "core:FirmwareRevisionState",
            "type": 3,
            "value": "v-2022.7.4-2-67c8c4f"
          },
          {
            "name": "core:FirmwareHashState",
            "type": 3,
            "value": "2022.7.4-2:67c8c4fb764cd28557bac79439c840c73e463fcc:bed0b25e537868738a278d354f238bcc"
          },
          {
            "name": "core:SSIDState",
            "type": 3,
            "value": "HUAWEI-B528-CF44"
          },
          {
            "name": "core:TimezoneState",
            "type": 3,
            "value": "Europe/Paris"
          },
          {
            "name": "core:LocalAccessProofState",
            "type": 3,
            "value": "localAccessProof"
          }
        ],
        "attributes": [
          {
            "name": "ogp:Features",
            "type": 10,
            "value": [
              {
                "name": "reset"
              },
              {
                "name": "localAccess"
              },
              {
                "name": "firmware"
              },
              {
                "name": "private"
              },
              {
                "name": "identification",
                "commandLess": true
              },
              {
                "name": "diagnosis"
              },
              {
                "name": "supervision"
              },
              {
                "name": "time"
              },
              {
                "name": "wifi"
              },
              {
                "name": "networkv4"
              }
            ]
          },
          {
            "name": "core:Technology",
            "type": 3,
            "value": "BoxTHmini"
          },
          {
            "name": "core:ManufacturerReference",
            "type": 3,
            "value": "gateway"
          },
          {
            "name": "core:Manufacturer",
            "type": 3,
            "value": "Overkiz"
          },
          {
            "name": "core:Private1",
            "type": 10,
            "value": [
              {
                "supportedPrivateCommands": "scheduledUpdate"
              }
            ]
          }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "d48cf8ad-eefd-4dfc-a410-56bbfbdd4be0",
        "type": 1,
        "widget": "DynamicGateway",
        "oid": "face54dc-603e-4e9c-9030-b5ff0d16bb60",
        "uiClass": "ProtocolGateway"
      },
      {
        "creationTime": 1679726549000,
        "lastUpdateTime": 1679726549000,
        "label": "Volet salon 2",
        "deviceURL": "ogp://2106-5255-7643/4618234",
        "shortcut": false,
        "controllableName": "ogp:Shutter",
        "definition": {
          "commands": [
            {
              "commandName": "activateOption",
              "nparams": 1
            },
            {
              "commandName": "close",
              "nparams": 0
            },
            {
              "commandName": "deactivateOption",
              "nparams": 1
            },
            {
              "commandName": "goToAlias",
              "nparams": 1
            },
            {
              "commandName": "identify",
              "nparams": 0
            },
            {
              "commandName": "open",
              "nparams": 0
            },
            {
              "commandName": "saveAlias",
              "nparams": 1
            },
            {
              "commandName": "setClosure",
              "nparams": 1
            },
            {
              "commandName": "setName",
              "nparams": 1
            },
            {
              "commandName": "stop",
              "nparams": 0
            }
          ],
          "states": [
            {
              "type": "DataState",
              "qualifiedName": "core:ActivatedOptionsState"
            },
            {
              "type": "DiscreteState",
              "values": [
                "available",
                "unavailable"
              ],
              "qualifiedName": "core:AvailabilityState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:AvailableOptionsState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:ClosureState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ErrorState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ErrorsState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareHashState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareRevisionState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NameState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NewFirmwareAvailableState"
            },
            {
              "type": "DiscreteState",
              "values": [
                "closed",
                "open"
              ],
              "qualifiedName": "core:OpenClosedState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ReachedAliasesState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RecommendedOptionsState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RemovableState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:SignalQualityState"
            }
          ],
          "dataProperties": [],
          "widgetName": "DynamicShutter",
          "uiProfiles": [
            "StatefulCloseableShutter",
            "StatefulCloseable",
            "Closeable",
            "StatefulOpenClose",
            "OpenClose"
          ],
          "uiClass": "Shutter",
          "qualifiedName": "ogp:Shutter",
          "type": "ACTUATOR"
        },
        "states": [
          {
            "name": "core:NameState",
            "type": 3,
            "value": "Volet salon 2"
          },
          {
            "name": "core:AvailabilityState",
            "type": 3,
            "value": "available"
          },
          {
            "name": "core:ErrorsState",
            "type": 10,
            "value": []
          },
          {
            "name": "core:FirmwareRevisionState",
            "type": 3,
            "value": "5128569B00"
          },
          {
            "name": "core:FirmwareHashState",
            "type": 3,
            "value": "5128569B00"
          },
          {
            "name": "core:OpenClosedState",
            "type": 3,
            "value": "open"
          },
          {
            "name": "core:ClosureState",
            "type": 1,
            "value": 0
          },
          {
            "name": "core:ActivatedOptionsState",
            "type": 10,
            "value": []
          }
        ],
        "attributes": [
          {
            "name": "core:Technology",
            "type": 3,
            "value": "io2way"
          },
          {
            "name": "core:Manufacturer",
            "type": 3,
            "value": "Somfy"
          },
          {
            "name": "ogp:Features",
            "type": 10,
            "value": [
              {
                "name": "firmware",
                "commandLess": true
              },
              {
                "name": "openClosePosition"
              },
              {
                "name": "openClose"
              },
              {
                "name": "optionControl"
              },
              {
                "name": "stop"
              },
              {
                "name": "identification"
              },
              {
                "name": "diagnosis"
              },
              {
                "name": "alias"
              }
            ]
          },
          {
            "name": "core:SubType",
            "type": 3,
            "value": "rolling"
          },
          {
            "name": "core:SupportedOptions",
            "type": 10,
            "value": [
              "silence"
            ]
          },
          {
            "name": "core:SupportedAliases",
            "type": 10,
            "value": [
              {
                "id": "1",
                "type": "favorite1",
                "features": [
                  "openClosePosition"
                ]
              }
            ]
          },
          {
            "name": "core:ManufacturerReference",
            "type": 3,
            "value": "shutter"
          }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "01b66fd8-cb02-4e44-89da-b0c5c7322649",
        "type": 1,
        "widget": "DynamicShutter",
        "oid": "f31a00fd-46af-464a-a622-b34ab3181163",
        "uiClass": "Shutter"
      },
      {
        "creationTime": 1679726455000,
        "lastUpdateTime": 1679726455000,
        "label": "Volet salon 1",
        "deviceURL": "ogp://2106-5255-7643/9689876",
        "shortcut": false,
        "controllableName": "ogp:Shutter",
        "definition": {
          "commands": [
            {
              "commandName": "activateOption",
              "nparams": 1
            },
            {
              "commandName": "close",
              "nparams": 0
            },
            {
              "commandName": "deactivateOption",
              "nparams": 1
            },
            {
              "commandName": "goToAlias",
              "nparams": 1
            },
            {
              "commandName": "identify",
              "nparams": 0
            },
            {
              "commandName": "open",
              "nparams": 0
            },
            {
              "commandName": "saveAlias",
              "nparams": 1
            },
            {
              "commandName": "setClosure",
              "nparams": 1
            },
            {
              "commandName": "setName",
              "nparams": 1
            },
            {
              "commandName": "stop",
              "nparams": 0
            }
          ],
          "states": [
            {
              "type": "DataState",
              "qualifiedName": "core:ActivatedOptionsState"
            },
            {
              "type": "DiscreteState",
              "values": [
                "available",
                "unavailable"
              ],
              "qualifiedName": "core:AvailabilityState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:AvailableOptionsState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:ClosureState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ErrorState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ErrorsState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareHashState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:FirmwareRevisionState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NameState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:NewFirmwareAvailableState"
            },
            {
              "type": "DiscreteState",
              "values": [
                "closed",
                "open"
              ],
              "qualifiedName": "core:OpenClosedState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:ReachedAliasesState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RecommendedOptionsState"
            },
            {
              "type": "DataState",
              "qualifiedName": "core:RemovableState"
            },
            {
              "type": "ContinuousState",
              "qualifiedName": "core:SignalQualityState"
            }
          ],
          "dataProperties": [],
          "widgetName": "DynamicShutter",
          "uiProfiles": [
            "StatefulCloseableShutter",
            "StatefulCloseable",
            "Closeable",
            "StatefulOpenClose",
            "OpenClose"
          ],
          "uiClass": "Shutter",
          "qualifiedName": "ogp:Shutter",
          "type": "ACTUATOR"
        },
        "states": [
          {
            "name": "core:NameState",
            "type": 3,
            "value": "Volet salon 1"
          },
          {
            "name": "core:AvailabilityState",
            "type": 3,
            "value": "available"
          },
          {
            "name": "core:ErrorsState",
            "type": 10,
            "value": []
          },
          {
            "name": "core:FirmwareRevisionState",
            "type": 3,
            "value": "5128569B00"
          },
          {
            "name": "core:FirmwareHashState",
            "type": 3,
            "value": "5128569B00"
          },
          {
            "name": "core:OpenClosedState",
            "type": 3,
            "value": "open"
          },
          {
            "name": "core:ClosureState",
            "type": 1,
            "value": 0
          },
          {
            "name": "core:ActivatedOptionsState",
            "type": 10,
            "value": []
          }
        ],
        "attributes": [
          {
            "name": "core:SupportedOptions",
            "type": 10,
            "value": [
              "silence"
            ]
          },
          {
            "name": "core:SupportedAliases",
            "type": 10,
            "value": [
              {
                "id": "1",
                "type": "favorite1",
                "features": [
                  "openClosePosition"
                ]
              }
            ]
          },
          {
            "name": "core:Technology",
            "type": 3,
            "value": "io2way"
          },
          {
            "name": "core:ManufacturerReference",
            "type": 3,
            "value": "shutter"
          },
          {
            "name": "core:SubType",
            "type": 3,
            "value": "rolling"
          },
          {
            "name": "core:Manufacturer",
            "type": 3,
            "value": "Somfy"
          },
          {
            "name": "ogp:Features",
            "type": 10,
            "value": [
              {
                "name": "firmware",
                "commandLess": true
              },
              {
                "name": "openClosePosition"
              },
              {
                "name": "openClose"
              },
              {
                "name": "optionControl"
              },
              {
                "name": "stop"
              },
              {
                "name": "identification"
              },
              {
                "name": "diagnosis"
              },
              {
                "name": "alias"
              }
            ]
          }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "01b66fd8-cb02-4e44-89da-b0c5c7322649",
        "type": 1,
        "widget": "DynamicShutter",
        "oid": "8d3b57a1-716c-4c0d-854a-fe622cf2f5c3",
        "uiClass": "Shutter"
      }
    ],
    "local": {
      "ip": null
    }
  }
}

**Comment by AdyRock** [comment]
Unfortunately, the log is not complete so I can't see all the devices.
Could you Click on the Send Log button in the Configure App, Device Log log page so I can get the full log.
